### ISSUE TITLE
Proposal: extend product definition for measurements to include scaling factors

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#1003]
Pixel data is typically stored using integer types, like `(u)int16`, but the real value that those integers encode is usually a floating point number, often in `[0,1]` range. Often the mapping from raw pixel value space to the real space is a simple linear transformation of the form:

```
real_value = pixel_value*scale_factor + add_offset  IF pixel_value != nodata
real_value = NaN                                    IF pixel_value == nodata
```
For example for an upcoming USGS Landsat collection 2 reflectance band pixels need to be scaled by 2.75e-5 and then offset by -0.2 to get normalised reflectance out. But for collection 1 those factors are different. 

It was previously proposed to perform scaling automatically during load in here #839, but that was for netcdf sources that include scaling information inside the file being read. However I believe there is a need for similar functionality when dealing with COG data as well. For data sources like Landsat and Sentinel, mapping from pixel value to "real" value is fixed for all datasets, but can differ from band to band. Capturing this information in the product definition would allow for better data loading experience to be developed later on.

My proposal is to add optional `scale_factor: Optional[float]` and `add_offset: Optional[float]` fields to product measurement schema here:

https://github.com/opendatacube/datacube-core/blob/072cd118fcb11efd68a455b2ecc21b99c7f73f3a/datacube/model/schema/dataset-type-schema.yaml#L51-L57

and to expose it via `Measurement` class, and to propagate those via `ds.band.attrs[..]` up to user code.

Names were chosen to be the same as defined by NetCDF, see here http://www.bic.mni.mcgill.ca/users/sean/Docs/netcdf/guide.txn_18.html

**Comment by uchchwhash** [comment]
I should probably mention that virtual products can do this.

**Comment by Kirill888** [comment]
can do what? Use this information automatically when it becomes available? Or encode scaling information in python code, which will require new code for every new sensor?

**Comment by uchchwhash** [comment]
Can specify scaling transformations in the recipe of a virtual product. But I see why you want to do this.
