### ISSUE TITLE
OSGeo patch installer for v2019

### ISSUE THREAD

**Issue by darkblue-b** [opendatacube/datacube-core#1009]
[OSGeoLive 2019](https://live.osgeo.org) ships with a python and postgres environment that closely matches ODC requirements for Ubuntu Linux.  **IDEA** to create a patch installer script for a stable ODC on OSGeoLive, if and when a demonstration is brought forward in the near future.

**Comment by Kirill888** [comment]
@darkblue-b is there some resource you can link that describes what "patch installer script" is and how one goes about creating one?
