### ISSUE TITLE
New feature: load hints in product definition

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#1011]
Currently when using `dc.load(..)` on a non-ingested product user must specify output `CRS` and `resolution` to use for loading data. This has been raised numerous times as a number one usability concern for non-ingested products.

I believe an easy solution to this problem is to specify an "appropriate projection and resolution" to use when loading data at the product definition time. For example for Australian installation that uses Landsat 8, one could define default projection to be Australian Albers and default resolution to be 30m.

```yaml
load:
  crs: 'epsg:3577'
  resolution: 
    y: -30
    x: 30
  align:
    y: 0
    x: 0
```

To fully define pixel grid one also needs to "anchor" grid lines, default anchoring is to have pixel boundaries go through `0,0`, this is where `load.align.{x,y}` comes in. Code snippet above translates to something like

*When loading data for this product default to Australian Albers projection, use 30m pixels with inverted y-axis. Align pixel grid such that lines `x=0m` and `y=0m` fall on the pixel edge.*

With this data defined on a product, `dc.load` would use data specified in the product definition only if user hasn't supplied alternative configuration. Behavior of `dc.load` will remain the same for products that do not define `load` section in their metadata.

To be consistent with ingestor and `storage` configurations one would need to use `longitude,latitude` keys when default CRS is defined to be `epsg:4326`.

**Comment by robbibt** [comment]
My first thought is that this sounds really great, and will hopefully ease the user experience a lot.

The only draw back is that the naive user will now be reverting back to having their data reprojected by default (e.g. just like back when all data was ingested vs. indexed). That means that unless they are careful, their data is going to be affected by some of the resampling issues that come with that (the only nice thing about the annoying UX flaw was it forced users to make careful decisions about resampling, which is something that often goes under the radar).

Not saying I disagree with the new feature proposal (I think it's great), just that it might require some careful explanation of what is happening behind the scenes so users can make an informed decision about how they load their data in the future.

**Comment by cbur24** [comment]
I think this is a great idea, as I have observed a lot of confusion around projections and pixel alignments among users with less of a background in remote sensing.  I agree with @robbibt that if this change takes place we should make a concerted effort to document the default settings (and their downstream impacts) in the relevant notebooks/docs.

**Comment by Kirill888** [comment]
Agree with @robbibt, ideally this feature would be complemented with `dc.load(.., resolution='native')` or similar. Problem with native load is "what to do when querying across UTM boundaries" for products like Landsat and Sentinel, do you fail or do you pick some kind of "majority". And then of course datacube can contain "anything", typically resolution is fixed per product-band pair, but there is no guarantee that it actually is, and a completely generic solution is kinda hard. Even picking majority is not that straightforward, is it just majority of datasets? Cause ideally it should be "majority of clear pixels", but that's much harder, and what if some pixels are different size? Looks like one would have to define a number of "policies" things like, "error if you can't use native projection for all the data", "use majority to pick projection", "use highest/lowest resolution across all bands/datasets being loaded".

Maybe this should also be augmented with per-band resampling configuration as was discussed here #779.

**Comment by Kirill888** [comment]
While implementing this feature I have stumbled into a realization that `storage` section has been coerced into the role I'm proposing for load hints, albeit without sufficient documentation.

https://github.com/opendatacube/datacube-core/blob/53374cc823f79cc720249a7a709aef686e4a69b5/datacube/api/core.py#L660-L668

Looks like partially defined `GridSpec` was used to communicate "desired CRS, and optionally resolution" to `dc.load(..)`. This behaviour has been "fixed" by #1012, from that change onward product will not report GridSpec if it's not fully defined, and so if people relied on this undocumented feature it will not work anymore, unless we repurpose `storage` to mean either

1. Fully specified gridding regime of an ingested product
2. Load hints, possibly partially specified (omitting resolution is allowed by current implementation by the looks of it)

I feel that having such an overloaded meaning for `storage` component of product definition is asking for trouble and might hinder future optimizations for ingested products. Also creating `GridSpec` class with missing components just to pass on information from product definition to loading code is just wrong. As a recipient of GridSpec object I should not need to check if it's fully defined.

**Comment by clausmichele** [comment]
If loading the data with default projection will be allowed, maybe it would solve this #1014 
And furthermore, maybe it could also solve #1007, allowing to index not geo-referenced data .

**Comment by Kirill888** [comment]
@clausmichele #1007 is very different, this requires rasterio backed reader driver detect and handle GCPs properly, at this stage I'm not even sure if this is even possible, it might require much broader changes than that.
