### ISSUE TITLE
Confusing error message from dc.load when misspelling product name

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#1015]
### Expected behaviour

When calling `dc.load` with misspelled product:

```python
xx = dc.load(product="no_such_product", time='2018', lon=.., lat..)
```

I expect to see an error message like `No such product: "no_such_product"`.

### Actual behaviour

Error message reads:

```
ValueError: No products match search terms: {'time': Range(begin=datetime.datetime(2018, 1, 1, 0, 0, tzinfo=), end=datetime.datetime(2018, 12, 31, 23, 59, 59, 999999, tzinfo=tzutc())), 
'lat': Range(begin=-20.25, end=-20.05), 
'lon': Range(begin=24.6, end=24.8), 'product': 'no_such_product'}
```

If `product=` is explicitly supplied by the user then error message should be more precise than above. Most users are not aware that `product=` can be omitted in some rare cases and instead can be inferred from the search terms used. This is not a feature that is commonly used, not sure how useful it is really, but it does make for confusing error reporting as above.

**Comment by uchchwhash** [comment]
I think it is safe to deprecate the product finding feature, perhaps refactor it into a `find_products` method, and make lookup by name only the default.
