### ISSUE TITLE
New feature proposal: query product by description as well as name

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#1016]
Product names have certain constraints, no spaces allowed, preference for shorter names, that sort of thing. It would be nice if one can reference product by a more descriptive alias that can contain spaces and other punctuation. For example

```python
xx = dc.load(product="Water Observations from Space April to October Statistics", ...)
```

Product definition already contains a field called `description`, we can use that. 

### Implementation Details

Resolving `product=` parameter will go something like that

1. If product with supplied name exists -- use that **DONE**
2. If product with supplied description exists and there is only one -- use that **DONE**
3. Report error: either ambiguous (several products with the same description), or "no such product".

**Comment by robbibt** [comment]
I like this idea, but if this goes ahead, I think we need to carefully decide what gets used in the `description` metadata for Collection 3 products. For example, the [description field here for Collection 3 WOfS](https://github.com/GeoscienceAustralia/digitalearthau/blob/025420bb3d3edc3833d8148becbba6e8db1126b4/digitalearthau/config/eo3/products-aws/ga_ls_wofs_3.yaml) contains "Historic Flood Mapping Water Observations from Space", which is descriptive but doesn't match either the product's technical name or short name on CMI, and so wouldn't be any help for trying to load a product using datacube.

If people are going to be able to load products based on their ODC `description`, I think this metadata field needs to be populated with either the short name or technical name from CMI (https://cmi.ga.gov.au/data-products?program[dea]=dea) for consistency. Out of those two options, I would possibly prefer the short name as it's more user friendly and easier to type than the extremely long technical name.

**Comment by alexgleith** [comment]
This is an easy method, I guess. Simpler than implementing a new 'alias' process.

Just thinking about context and what others are doing: https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR

GEE uses a simple unique identifier field, like `ee.ImageCollection('COPERNICUS/S2_SR')`

**Comment by jeremyh** [comment]
I'm slightly hesitant about this because it makes changing the description a breaking change for users. Descriptions also have often changed in the past (eg, describing something as a legacy collection now, fixing mistakes, improving consistency after new product releases etc), and it's also a very long unwieldy string for something that has to match exactly. 

I'd probably prefer doing the same thing as measurements and have a dedicated "aliases" field with friendly short name(s), like Alex mentions.

**Comment by Kirill888** [comment]
I don't mind aliases as an alternative, but I'm not too sure about aliases being defined within the product itself, like what currently happens with measurements. The reason is: no way to ensure uniqueness of the alias. I realize that same problem applies to `description` field, but that's fine as we just re-purposing an already existing field.

I think this should be a standalone "site configuration" thingy that creates a mapping from "human facing unique name", to whatever current product name is/has become. Question is: should this be stored in the database itself (this needs a new table), or placed into a config file (might differ from user to user).

That way one can have an alias, say `LS8` that always points to the most current Landsat 8 collection, and when the new one comes in, previous product definition does not need changing, only site configuration will need a change.

**Comment by Kirill888** [comment]
@jeremyh can you remind us why product name is limited to "python variable name format", I don't recall any uses of `some_function(product_name=something)` anywhere.

**Comment by Kirill888** [comment]
Thinking more about this, I think I prefer a database-backed "site configuration" section. Doesn't need to be anything fancy just a json blob stored somewhere. We can then extend it for other useful things like

- Default projection to use for loading data
- Default timezone to use for deciding day boundaries
- "Simple virtual products", like ls5+ls7+ls8
- Any other experimentation
- And product aliases too

**Comment by jeremyh** [comment]
> @jeremyh can you remind us why product name is limited to "python variable name format", I don't recall any uses of `some_function(product_name=something)` anywhere.

It was limited as an identifier to be usable safely and unmodified in urls (eg explorer), file paths, sql table/view/index names (like the postgres driver), and potentially python/js property usage (... which was not used here? but is used for some other entities using the same rules, like fields: `dataset.metadata.blah`).

**Comment by jeremyh** [comment]
> I'm not too sure about aliases being defined within the product itself, like what currently happens with measurements. The reason is: no way to ensure uniqueness of the alias. 

I kinda already viewed the product definition as "this is how this local datacube interprets the data", so putting it there fits my admittedly-limited world view. Writing products also already requires careful consideration of uniqueness with fields like the metadata-match rules.

Thinking out loud, but I'd maybe rather add validation of uniqueness to `product.add` (which is already long overdue for the uniqueness of metadata-match rules) and make sure the fields are easy to change via `datacube product update`.

**Comment by Kirill888** [comment]
Fair enough. I guess even when constrained to identifier syntax it can be human usable. But with the current convention at GA, and the desire to include it in the file name, and hence wanting to use shorter names, it's becoming unwieldy.

Regarding you second comment, it's probably easier to implement another field `alias|query_name|short_name` or whatever you call it that can contain any characters including `/:-`. And suggest that as a preferred `dc.load(..)` identifier to use when querying.

But then one either have to make it optional or develop migration tools to populate that field (copy product name in there?)

I feel like product definition should not be tied to a given installation, I should be able to export product from one DB to another and not worry too much about it breaking things for me (although it currently might due to auto-matching rules).

**Comment by alexgleith** [comment]
I think that including product aliases in a product definition makes sense. And we could use the same logic as you proposed above, Kirill, and just cleverly inform users of an alias collision.

Uniqueness doesn't need to be enforced on the DB level. And if the alias value isn't in the JSON in the DB, then ignore it! Also no index required, because there's only a small number of rows in the product table.

**Comment by Kirill888** [comment]
Ok fine, let's go with an extra "any string" field, that is expected to be unique, but not enforced to be unique. Next question is what should that be called.

- `title:` :heavy_check_mark: 
- `alias:` :grey_question: 
- `full_name:` :grey_question: 

I'm not too keen on allowing several aliases for a product, it somewhat makes sense for bands, but I feel like it's not right for a product. My preference is to go with `title:`.

**Comment by jeremyh** [comment]
A fourth option is 'label', which is what dataset's short human-readable strings are called (which are also usually, but not enforced to be, unique).

**Comment by alexgleith** [comment]
+1 for `title`. It's more standard.

**Comment by woodcockr** [comment]
Be useful to have `namespace` as well. We use DEA and CSIRO data and they can be the identical product aside who is managing it. Some namespace capability would allow us to keep product names consistent with GA but have them managed in a different namespace.
