### ISSUE TITLE
S3 suport for datacube ingest

### ISSUE THREAD

**Issue by tushar10sh** [opendatacube/datacube-core#1018]
Currently, datacube ingest only supports netCDF on filsystem. Any chances of integration with S3 like storage system. I am using minIO for cloud object storage and my indexed data is present there. Would like to generate ingested data on s3. 
Any solution? 
Thanks in advance.

**Comment by woodcockr** [comment]
`datacube ingest` is mostly not used now (and likely to be deprecated). The more common operating mode is to prepare the data beforehand and then index the result to `datacube`. This provides more control over the preparation process for specific circumstances
In our ODC environment we use workflow automation (Argo) and a `data-pipelines` library to manage order, download, metadata preparation and data conversion to S3 (e.g. COGS, and Zarr coming soon). There are also a set of `odc-tools` that can be used to do metadata preparation and indexing.

**Comment by Kirill888** [comment]
I'm always curious to know what benefit people expect to/do obtain from ingestion process. @tushar10sh  can you describe your use-case a bit? 

I agree with Rob that ingestion is not really needed in most cases. Particularly with the current ingestion strategy where duplicated pixels in the source product are preserved as they were. As a consequence of this choice number of datasets  in the ingested product is always strictly larger than what was in the source product (often 10 times larger). Furthermore density of valid pixels per image file goes down as a result of ingestion. And of course reprojection is fundamentally a lossy operation, so you either lose some data or pay double in storage costs.

Some of us at GA are working on developing tools for running large statistical workflows in the cloud (k8s on AWS in our case). Typical application is to perform some sort of annual statistical computation, like a median for example. I feel that ingestion can be implemented within the context of that work, as it shares all the major components with a usual stats process: figuring out which source datasets overlap with which output grid cell, loading data with reprojection for every output tile, generating COGs and writing them to S3, doing it all at "continental scale". We then also get an option to de-duplicate overlap pixels as part of the ingestion process, which is what I would expect from re-gridding process.

**Comment by tushar10sh** [comment]
Got it. Thanks a lot.
