### ISSUE TITLE
Mozilla Science Lab Global Sprint 2016: 2nd & 3rd June

### ISSUE THREAD

**Issue by Spaxe** [opendatacube/datacube-core#102]
Hey there,

Mozilla is hosting a global open science hackathon, and they are [open for project submissions](https://www.mozillascience.org/global-sprint-2016). This means you can get interested software people to contribute to this project over 2 days. Of course, you will also be able to contribute to other open science projects on the day.

The only requirement is that projects must be open source, advance science, and have someone to lead the project on the two days of 2 and 3 June (Thurs & Fri).

You can see [2015's Mozilla global sprint here](https://mozillascience.org/global-sprint-2015).

I'm personally keen on this (read: would attend & facilitate logistics), but to get a AGDC submission we would need someone from your core team to champion this idea. Would this be a yay?

**Comment by v0lat1le** [comment]
Doesn't look like we're doing this...
