### ISSUE TITLE
Use of postgres+postgis for future releases? 

### ISSUE THREAD

**Issue by tushar10sh** [opendatacube/datacube-core#1021]
Since the datacube docs imply the db schema to be NoSQL, I wonder why the team didnot consider mongoDb as the choice of database for datacube. There is significant difference in the container image size of potgres+postgis vs mongodb (which supports geospatial queries as well). Postgres + postgis has been very good in terms of features they provide but the features that are being used are supported by mongo as well. Its just that we at ISRO had used mongo db for our dataset discovery services internally. Just a query. Thanks in advance.

**Comment by uchchwhash** [comment]
It would be an interesting exercise to port ODC to NoSQL databases. Fortunately the index layer in ODC is replaceable, and you can try implementing it NoSQL yourself! The `datacube-core` team as of now however has no intention of spending a significant amount of time on this. We are keen to have more PostGIS support though. Closing, but we would be happy to hear from you if you are interested in collaboration on this.
