### ISSUE TITLE
Open Data Cube License Headers

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-core#1025]
### Overview

In order for the ODC to become an ODC Community Project, we need to include license headers in all source files. Initially, this will be in the `datacube-core` project, but we should role it out in other key projects.

### Current situation

We have inconsistent headers currently.

### Suggested headers

```
#
# Copyright (c) 2015-2020 ODC Contributors
#
# This file is part of the Open Data Cube
# See https://opendatacube.org for more information
#
# SPDX-License-Identifier: Apache-2.0
#
```

The command to add these headers to all files in a folder is this: `licenseheaders --tmpl license-template.txt --years 2015-2020 --dir datacube` and uses this tool: https://github.com/johann-petrak/licenseheaders

**Comment by omad** [comment]
Closed by #1028
