### ISSUE TITLE
datacube.load with malformed single-measurement queries

### ISSUE THREAD

**Issue by benjimin** [opendatacube/datacube-core#1026]
If `datacube.Datacube().load` is passed a string as the `measurements=` argument (instead of a list containing only that string) then it tries to iterate over the characters in the string (as separate, if somewhat terse, band names). 

This inevitably results in an error, that is not necessarily beginner-friendly. Instead I think the API function should validate the input (and either tolerate a single measurement as a string, or provide a more helpful error message).

**Comment by robbibt** [comment]
This seems like a similar issue to #1033, and could probably return a similar error message to direct the user to provide a valid input

**Comment by Kirill888** [comment]
I think in this case `measurements="red"` should be treated as `measurements=("red",)` without any error or warning.

**Comment by benjimin** [comment]
Does anybody really want to close and tag this issue as "wontfix"?

IMO worth keeping this issue open because:

- It seems quite _easy_ to implement.
- Validating the API function input (then producing a more friendly error message for a common mistake) seems like an _uncontentious_ change.
- It would be a good exercise for any _new contributor_ who may be looking to gain familiarity with the codebase and/or processes.
- Low priority doesn't mean not worth doing, and it is harder to track outstanding tasks if they are closed.
- It's still a problem (still produces a terse `KeyError` message, that relates to the input in an unobvious way).

**Comment by sjaddya** [comment]
I found this issue on ovio.org and would love to contribute! I am new contributor, and since it seemed to be labeled easy, I would like to give it a try

**Comment by Kirill888** [comment]
@sjaddya that's great, go ahead, we need to make a new release soonish, so clean up like this is welcome.
