### ISSUE TITLE
'DatasetType' object has no attribute '_all_measurements' with dask

### ISSUE THREAD

**Issue by jankovicgd** [opendatacube/datacube-core#1027]
Hey all, I am receiving an error when using dask to perform some computations. Not sure entirely if this is an ODC/Dask/xarray issue though. Any help would be appreciated. The code example below was extracted from a jupyter notebook.

### Expected behaviour
Computed data and plot

### Actual behaviour

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-37a4078ad80d> in <module>
----> 1 resampled.compute().plot(size=10)

/opt/conda/envs/datacube/lib/python3.6/site-packages/xarray/core/dataarray.py in compute(self, **kwargs)
    832         """
    833         new = self.copy(deep=False)
--> 834         return new.load(**kwargs)
    835 
    836     def persist(self, **kwargs) -> "DataArray":

/opt/conda/envs/datacube/lib/python3.6/site-packages/xarray/core/dataarray.py in load(self, **kwargs)
    806         dask.array.compute
    807         """
--> 808         ds = self._to_temp_dataset().load(**kwargs)
    809         new = self._from_temp_dataset(ds)
    810         self._variable = new._variable

/opt/conda/envs/datacube/lib/python3.6/site-packages/xarray/core/dataset.py in load(self, **kwargs)
    652 
    653             # evaluate all the dask arrays simultaneously
--> 654             evaluated_data = da.compute(*lazy_data.values(), **kwargs)
    655 
    656             for k, data in zip(lazy_data, evaluated_data):

/opt/conda/envs/datacube/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    450         postcomputes.append(x.__dask_postcompute__())
    451 
--> 452     results = schedule(dsk, keys, **kwargs)
    453     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    454 

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2712                     should_rejoin = False
   2713             try:
-> 2714                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2715             finally:
   2716                 for f in futures.values():

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1991                 direct=direct,
   1992                 local_worker=local_worker,
-> 1993                 asynchronous=asynchronous,
   1994             )
   1995 

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    832         else:
    833             return sync(
--> 834                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    835             )
    836 

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    337     if error[0]:
    338         typ, exc, tb = error[0]
--> 339         raise exc.with_traceback(tb)
    340     else:
    341         return result[0]

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/utils.py in f()
    321             if callback_timeout is not None:
    322                 future = asyncio.wait_for(future, callback_timeout)
--> 323             result[0] = yield future
    324         except Exception as exc:
    325             error[0] = sys.exc_info()

/opt/conda/envs/datacube/lib/python3.6/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1850                             exc = CancelledError(key)
   1851                         else:
-> 1852                             raise exception.with_traceback(traceback)
   1853                         raise exc
   1854                     if errors == "skip":

/home/ubuntu/.local/lib/python3.6/site-packages/datacube/api/core.py in fuse_lazy()

/home/ubuntu/.local/lib/python3.6/site-packages/datacube/api/core.py in _fuse_measurement()

/home/ubuntu/.local/lib/python3.6/site-packages/datacube/storage/_base.py in __init__()

/home/ubuntu/.local/lib/python3.6/site-packages/datacube/model/__init__.py in lookup_measurements()

/home/ubuntu/.local/lib/python3.6/site-packages/datacube/model/__init__.py in _resolve_aliases()

AttributeError: 'DatasetType' object has no attribute '_all_measurements'
```

### Steps to reproduce the behaviour

```python
from dask.distributed import Client
import datacube
import xarray
client = Client('cluster_address')
dc = datacube.Datacube()
query = {
    'lat': (48.15, 48.35),
    'lon': (16.3, 16.5),
    'time': ('2017-01-01', '2020-12-31')
}
data = dc.load(product='product', 
               output_crs='EPSG:32633', 
               resolution=(-10,10),
               dask_chunks={'x': 250, 'y': 250, 'time':20},
                **query)
arr = data.band_1
resampled = arr.resample(time='1w').mean().mean(axis=(1,2))
resampled.compute().plot(size=10)
```

### Environment information

There are some slight mismatches in the versions I hope that these aren't the issue:
```
/opt/conda/envs/datacube/lib/python3.6/site-packages/distributed/client.py:1130: VersionMismatchWarning: Mismatched versions found

+-------------+----------------+---------------+---------------+
| Package     | client         | scheduler     | workers       |
+-------------+----------------+---------------+---------------+
| dask        | 2.27.0         | 2.27.0        | 2.28.0        |
| distributed | 2.27.0         | 2.27.0        | 2.28.0        |
| numpy       | 1.19.1         | 1.19.2        | 1.19.2        |
| python      | 3.6.11.final.0 | 3.6.9.final.0 | 3.6.9.final.0 |
| toolz       | 0.11.1         | 0.10.0        | 0.11.1        |
+-------------+----------------+---------------+---------------+
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
```

* Which ``datacube --version`` are you using? 1.8.3
* What datacube deployment/enviornment are you running against? Jupyterhub running in docker

**Comment by luigidifraia** [comment]
Hi @jankovicgd.

I was able to run the notebook you shared, with the necessary modifications for product and area/time extents, without stumbling on the issue you are reporting. I am using ODC core 1.8.3 and a distributed Dask cluster running Dask 2.23.0.

Just a couple of things you might want to check:

- does your query return a non-empty dataset? You can use the `find_datasets` method for that purpose, e.g.:
    ```
    dss = dc.find_datasets(product='product', **query)
    len(set(ds.time for ds in dss))
    ```
- did you try equivalent code (possibly with smaller extents in order not to exhaust local resources) without using a distributed Dask cluster and only moved to using it after the former was working?

**Comment by jankovicgd** [comment]
Hello @luigidifraia,

Thanks for the recommendations!

The query is not empty, it returns some 400 datasets. I've just tried without the cluster and a smaller time difference and all works fine. I've also different mean calculations but with the same issue. I might try and get the versions sorted, and I will try dask 2.23.

**Comment by luigidifraia** [comment]
> I might try and get the versions sorted, and I will try dask 2.23.

Hi @jankovicgd. Getting the version of Dask-related Python modules for client (i.e. JupyterHub), scheduler and worker aligned is definitely paramount. Also, I'd make sure that the same version of Python and various Python modules involved in the computation itself are installed across all containers. The fact the computation works locally, suggests this might not be the case at the moment?

**Comment by jankovicgd** [comment]
It indeed does seem so. I have synchronized the versions (& dask 2.23) and seem to be getting some progress, the computation works if I specify LocalCluster (although I forgot to try this before), but the same error with the remote cluster.

**Comment by jankovicgd** [comment]
I have setup datacube on the worker nodes as well, previously I got the ModuleNotFound so I have also datacube 1.8.3 on the worker.

**Comment by jankovicgd** [comment]
One thing to note, I hope it doesn't matter that the lab clients are running in conda environments and the dask/datacube on the cluster are installed through pip.

**Comment by luigidifraia** [comment]
If you can ensure all versions are the same, then you might be fine. I myself use mostly `conda` for all images, in order to keep everything in sync (and avoid installing `gcc`, as example). See below:

[Scheduler/worker image for Dask distributed](https://github.com/luigidifraia/dask-docker-images/blob/master/datacube/Dockerfile)
[Single user image for JupyterHub](https://github.com/luigidifraia/docker-stacks/blob/master/datacube-notebook/Dockerfile)

**Comment by jankovicgd** [comment]
I have setup everything and no longer get the version mismatch warning, just the error. Really weird that the LocalCluster works and a remote doesn't.

**Comment by luigidifraia** [comment]
> I have setup everything and no longer get the version mismatch warning, just the error. Really weird that the LocalCluster works and a remote doesn't.

Did you fetch the logs from your Dask worker containers? There are usually some useful insights you can gather from them.

**Comment by Kirill888** [comment]
@jankovicgd when using Dask one HAS TO run everything from exactly the same environment, not just the same versions of some libraries, it has to be exactly the same python environment, anything less than that and all bets are off. Sure, it might work some of the time for some trivial cases, but it's not guaranteed to work. This is due to the way Dask is using data and code serialisation (pickle) to send tasks around, the assumption is that everything is operating within exactly identical python environment.

**Comment by jankovicgd** [comment]
Thanks for the help, really appreciate it. I will try to setup dask with conda in docker to match the docker/jupyterhub setup environment.

**Comment by jankovicgd** [comment]
Small update, before I try to update and create conda/docker environments, I have tested in a similar regular pip venv and a separate VM and the example works, so probably the solution would be that the environments would need to match.

**Comment by jankovicgd** [comment]
Hello again,

I have setup dask/datacube in conda environments inside docker swarm, got the matching versions for everything and regular dask arrays and examples work, but I still get the same error when using ODC. If you want I might be able to provide you with an account on our hub to test yourself. I can only confirm that it worked with pip.

**Comment by jankovicgd** [comment]
The workers display many instances of this error.

```
dask_worker.2.8m51ifu8447z@dask-worker    | 
dask_worker.2.8m51ifu8447z@dask-worker    | distributed.worker - WARNING -  Compute Failed
dask_worker.2.8m51ifu8447z@dask-worker    | Function:  fuse_lazy
dask_worker.2.8m51ifu8447z@dask-worker    | args:      ([Dataset <id=b0b61ad5-619c-4b09-9a88-06131cbc38d4 product=FAPAR_Sentinel_2 location=file:///eodc/private/eodc_acube/datasets/acube/BOKU_FAPAR_S2/BOKU_FAPAR_S2_20170703000000_20170703000000_EU010M_E052N016T1.yml>], GeoBox(526, 250, Affine(10.0, 0.0, 606310.0,
dask_worker.2.8m51ifu8447z@dask-worker    |        0.0, -10.0, 5336290.0), EPSG:32633), Measurement({'name': 'band_1', 'dtype': 'int16', 'units': 'fraction', 'nodata': 32767, 'aliases': ['band_01', 'Band1', 'Band_1'], 'fuser': None}), False, 1)
dask_worker.2.8m51ifu8447z@dask-worker    | kwargs:    {}
dask_worker.2.8m51ifu8447z@dask-worker    | Exception: AttributeError("'DatasetType' object has no attribute '_all_measurements'",)
dask_worker.2.8m51ifu8447z@dask-worker    | 
```

**Comment by luigidifraia** [comment]
Quick question: where are you hosting your datasets? Would they be accessible from within Dask nodes?

**Comment by jankovicgd** [comment]
Do you mean the .yml datasets or the imagery? With yml datasets they are zipped and wouldn't actually be available and with imagery there is a network share. I did forget to bind mount that at first to docker, but even with mounting its the same error. Would the .yml files need to be available as well? This wouldn't explain pip baremetal working though.

**Comment by jankovicgd** [comment]
Figured it out. It seems the client had datacube 1.8.0 instead of 1.8.3. I am not sure how this slipped by but it works now, sorry for the inconvenience :sweat_smile: You may close
