### ISSUE TITLE
Change Install requires to psycopg2-binary

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-core#1030]
### Expected behaviour
Datacube core can be easily pip installed from PyPI in GDAL nightly Ubuntu 20.04 based Docker image.

### Actual behaviour
Install gets stuck attempting to compile psycopg2 from source.

### Steps to reproduce the behaviour
`docker run -it osgeo/gdal`
`python3 -m pip install datacube`

With a few steps in between to get pip in place in the stripped down docker image. It would be nice to move to the psycopg2 binary wheel to avoid compilation and lower the barrier to entry : 
https://pypi.org/project/psycopg2-binary/

### Environment information

* Which ``datacube --version`` are you using? 1.8.3 (latest on PyPI)
* What datacube deployment/enviornment are you running against? GDAL nightly docker image built on Ubuntu 20.04

**Comment by Kirill888** [comment]
no, won't happen. Binary wheel will not be able to talk to db via unix sockets because the way ubuntu compiles postgres is different from CentOS which is what binary wheels usually target

**Comment by Kirill888** [comment]
Also this will make datacube uninstallable on platforms not supported by `psycopg2-binary`

**Comment by whatnick** [comment]
Can `psycopg2` be made an over-rideable dependency if `psycopg2-binary` is present ?

**Comment by omad** [comment]
To add to Kirill's comment, the [readme for psycopg2](https://pypi.org/project/psycopg2/) states:

    The binary package is a practical choice for development and testing but in production it is advised to use the package built from sources.

I would maybe consider adding `psycopg2-binary` to a `requirements.txt` file or Docker build script, but it should never be added to the `setup.py` requirements, which is what `pip install` uses.
