### ISSUE TITLE
Better interop with `xr.open_dataset` for data in geographic projection

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#1031]
### Expected behaviour

```python
import xarray as xr
import datacube

xx = xr.open_rasterio("file-in-epsg4326.tif")
assert xx.dims == xx.geobox.dimensions
```

### Actual behaviour

For data loaded via `xr.open_rasterio` dimension names as reported by `.geobox.dimensions`  and actual dimension names disagree, that leads to all sort of problems when interacting with datacube. Basically `xr.open_` functions always return data with spatial dimensions labelled as `y,x` while datacube uses `y,x` for projected and `latitude,longitude` for geographic.

### Proposed Fix

Currently `Geobox.dimensions` is just a wrapper over `CRS.dimensions` and that is hard-coded to be this:

https://github.com/opendatacube/datacube-core/blob/7a913bb8214dcd0bfe908fcbd1ba89755ff8ec73/datacube/utils/geometry/_base.py#L228-L232

If we allow to override `.dimensions` on a GeoBox class by optionally supplying dimension names during constructor, then we can have consistent names between geobox and array it is "attached to". This would then make sure that `dc.load(.., like=xx.geobox)` would return array with compatible dimension names even for `xx` loaded from xarray library.
 
cc: @robbibt

**Comment by robbibt** [comment]
There is an example of this issue in the "Loading datacube data to match a raster" section of this notebook here; note that this code must be used to get the `xr.open_rasterio` data to have `xarray` dimension names that match its geobox dimension namers:
```
if raster.geobox.crs.geographic:
    raster = raster.rename({'x': 'longitude', 'y': 'latitude'})
```

https://github.com/GeoscienceAustralia/dea-notebooks/blob/733cd13c8ebc98ee961d7b984bc4db01f450e3e6/Testing/Reprojecting_data.ipynb
