### ISSUE TITLE
Standardise geobox parameter names across reprojection functions

### ISSUE THREAD

**Issue by robbibt** [opendatacube/datacube-core#1032]
### Expected/actual behaviour
The following two functions can be used for reprojecting `xarray` objects and raster files respectively:
```
from odc.algo import xr_reproject
from datacube.testutils.io import rio_slurp_xarray
```

Currently, the two functions require different parameter names to specify a geobox, e.g. `xr_reproject` requires a parameter called `geobox`, while `rio_slurp_xarray` requires `gbox`. For example:

```
xr_reproject(src=ds, geobox=raster.geobox)
rio_slurp_xarray(fname=..., gbox=ds.geobox)
```

To improve the user experience, it would be nice to have parameter names standardised across these functions and others that require a geobox as an input, e.g. use `geobox` consistently across all ODC functions.

### Environment information

* Which ``datacube --version`` are you using? `'1.8.3'`
* What datacube deployment/enviornment are you running against? `Sandbox`

**Comment by robbibt** [comment]
Still relevant

**Comment by Ariana-B** [comment]
Note that with odc-geo migration, this will also require a PR to odc-geo

**Comment by Ariana-B** [comment]
Taken care of in #1441
