### ISSUE TITLE
Celery tests are failing, code is drifting out of date with upstream celery

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-core#1037]
### Expected behaviour

Celery tests and code that uses celery should be updated if it's being used. It doesn't seem to be being used.

We should deprecate celery executors and disable tests.

### Actual behaviour

Celery tests work to test useful code.

### Steps to reproduce the behaviour

Run tests in Docker...

**Comment by alexgleith** [comment]
Pinning celery to `4.4.7` may fix the skipped test.

**Comment by alexgleith** [comment]
I still think we should delete the celery code!

**Comment by Kirill888** [comment]
@alexgleith then re-open the issue and add pinned tag

**Comment by SpacemanPaul** [comment]
Celery has been deprecated - will remove after 1.8.7 release.
