### ISSUE TITLE
Expose native CRS as searchable product metadata

### ISSUE THREAD

**Issue by robbibt** [opendatacube/datacube-core#1040]
### Expected behaviour
It would be valuable for users to be able to search for datacube data by a dataset's native CRS. For example, this could be used to load only `EPSG:32656` data along a UTM boundary where a query returns datasets with both `EPSG:32655` and `EPSG:32656` CRSs (e.g. to ensure all data is loaded in native CRS with no resampling):

```
dc.load(product='ga_ls8c_ard_3',
             output_crs='EPSG:32656',
             epsg='EPSG:32656',
             **query)
```

This CRS metadata does seem to exist within in the `grid_spatial` metadata, but as far as I know this can't be used when searching for data. 

### Actual behaviour
There is currently no searchable CRS metadata available for ODC products:

```
dataset = dc.find_datasets(product='ga_ls8c_ard_3', limit=1)[0]
dir(dataset.metadata)
>> ['cloud_cover', 'creation_dt', 'creation_time', 'dataset_maturity', 'eo_gsd', 'eo_sun_azimuth', 'eo_sun_elevation', 'fmask_clear', 'fmask_cloud_shadow', 'fmask_snow', 'fmask_water', 'format', 'gqa', 'gqa_abs_iterative_mean_x', 'gqa_abs_iterative_mean_xy', 'gqa_abs_iterative_mean_y', 'gqa_abs_x', 'gqa_abs_xy', 'gqa_abs_y', 'gqa_cep90', 'gqa_iterative_mean_x', 'gqa_iterative_mean_xy', 'gqa_iterative_mean_y', 'gqa_iterative_stddev_x', 'gqa_iterative_stddev_xy', 'gqa_iterative_stddev_y', 'gqa_mean_x', 'gqa_mean_xy', 'gqa_mean_y', 'gqa_stddev_x', 'gqa_stddev_xy', 'gqa_stddev_y', 'grid_spatial', 'id', 'instrument', 'label', 'lat', 'lon', 'measurements', 'platform', 'product_family', 'region_code', 'sources', 'time']
```

### Environment information

* Which ``datacube --version`` are you using? 1.8.3
* What datacube deployment/enviornment are you running against? Sandbox, NCI

**Comment by robbibt** [comment]
From discussion on slack: https://opendatacube.slack.com/archives/G3YHHD6QH/p1605070292272900
![image](https://user-images.githubusercontent.com/17680388/98874582-a41a9300-24ce-11eb-84c4-2637e00bf5d9.png)

**Comment by robbibt** [comment]
Thoughts @Kirill888 @alexgleith @jeremyh?

**Comment by Kirill888** [comment]
Agree with @jeremyh, crs field is way too flexible to support direct comparison in SQL. One could, I suppose, inject `epsg` code field at index time for those datasets that do have CRSs that are standard enough to have epsg code, and then expose that field as a searchable thing. Or one can do it already without any changes to the code, by simply including epsg code in the metadata and creating a metadata search field for it.

Problem with "automatic version" is the extreme flexibility of the current metadata system, we simply can not assume that users have not created their own searchable epsg code already, so if we add that field as "standard", we can either risk aliasing user defined field or need to write complex logic to verify that we are not doing that, and then also implement reasonable fallback behaviour (behaviour that won't get used very often and hence will be likely to fail in some edge cases).

Other major cost for "automatic version", is implementing migration tooling, so that those searchers would work on already indexed data.

**Comment by robbibt** [comment]
OK, fair enough. Perhaps this is better dealt with as a Collection 3 product-specific searchable metadata field? If so, I might make an equivalent issue here https://github.com/GeoscienceAustralia/digitalearthau/issues

**Comment by alexgleith** [comment]
it's further complicated by Proj supporting non-epsg codes (which STAC is poorly handling too).

Can this be handled in the short term by allowing searching across the whole parameter space in the metadata? It requires knowledge of the metadata for the dataset you're searching, but opens up a whole range of queries.

**Comment by robbibt** [comment]
Hey @alexgleith, what do you mean by `searching across the whole parameter space in the metadata`?

(ah, as in, being able to search all metadata fields, not just those that have been specifically declared searchable?)

**Comment by Kirill888** [comment]
@alexgleith yes, we should allow "ad-hoc" queries that do not require update to `metadata_type` just to lookup random paths within JSON docs.

**Comment by alexgleith** [comment]
hey @robbibt what Kirill says.

If the metadata has a field like `properties: robbis_magic: true` then we should be able to have a parameter in dc.load that can query that out of the Postgres JSON field. It's possible with SQL, but with the ODC we only expose some of them that are listed in the metadata definition that the product uses.

**Comment by robbibt** [comment]
Yep OK, makes sense - yeah, to me that would be incredibly useful. Pretty much all of the properties I've wanted to filter/search data by recently have actually existed in metadata, just not in the subset of fields that are exposed as searchable via `dc.load`.

**Comment by Kirill888** [comment]
It might look something like this:

```python
xx = dc.load(
Field('properties.epsg', int) == 3699,
Field('properties.cloud_cover', float) >= 95,
product="...",
...
)
```
the annoying part is those will have to be placed before named arguments.

**Comment by Kirill888** [comment]
The alternative syntax would be something like
```python
xx = dc.load(...,
custom_search=[
    Field('properties.epsg', int) == 3699,
    Field('properties.cloud_cover', float) >= 95,
])
```

or whatever better name is for `custom_search`.

**Comment by robbibt** [comment]
Out of those two I prefer the second one; it would be easier to explain that functionality to users if it's a discrete named thing (also a bit easier to assign the entire `custom_search` object to a variable and re-use it for different loads).

**Comment by robbibt** [comment]
Superseded by https://github.com/GeoscienceAustralia/digitalearthau/issues/280 which will hopefully implement a DEA-specific update that won't require changes to `datacube-core`

**Comment by robbibt** [comment]
Superseded by https://github.com/GeoscienceAustralia/digitalearthau/issues/280 which will hopefully implement a DEA-specific solution that won't require changes to `datacube-core`
