### ISSUE TITLE
Development branch: 6 Integration tests failed 

### ISSUE THREAD

**Issue by romulogoncalves** [opendatacube/datacube-core#1054]
### Expected behaviour
Each test result should either be green or yellow, but we are getting 6 off them (most of them related with S3 storage) red. In case a connection to Amazon S3 is required, then the tests should be skipped when we do not have one configured.

### Actual behaviour
... eg. Incorrect result, python stacktrace, etc. ...

We are getting 6 tests red.
```bash
========================================================================================= short test summary info =========================================================================================
SKIPPED [1] ../../anaconda3/envs/odc/lib/python3.8/site-packages/_pytest/doctest.py:448: all tests skipped by +SKIP option
XFAIL tests/test_geometry.py::test_lonalt_bounds_more_than_180
  Bounds computation for large geometries in safe mode is broken
XFAIL tests/test_utils_docs.py::test_merge_with_nan
  Merging dictionaries with content of NaN doesn't work currently
FAILED tests/test_utils_aws.py::test_s3_io - botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location c...
FAILED tests/test_utils_dask.py::test_save_blob_s3_direct[some utf8 string] - botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket oper...
FAILED tests/test_utils_dask.py::test_save_blob_s3_direct[raw bytes] - botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: ...
FAILED tests/test_utils_dask.py::test_save_blob_s3[some utf8 string] - botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: ...
FAILED tests/test_utils_dask.py::test_save_blob_s3[raw bytes] - botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The uns...
FAILED integration_tests/test_celery_runner.py::test_celery_with_worker - Failed: Timeout >30.0s
============================================================== 6 failed, 607 passed, 1 skipped, 2 xfailed, 21 warnings in 175.28s (0:02:55) ===============================================================
```

### Steps to reproduce the behaviour
... Include code, command line parameters as appropriate ...

We did all the steps from the installation manual. With step number 6, integration tests, it is how we can see the above errors.
```bash
./check-code.sh integration_tests
```

### Environment information
* Which ``datacube --version`` are you using?
* What datacube deployment/enviornment are you running against?

We are testing with development branch using the latest version.
```bash
(odc) datacube-core$ datacube --version
Open Data Cube core, version 1.8.4.dev52+g07bc51a5.d20201217
```
Operating system is Ubuntu LTS 20.04
```bash
(odc) datacube-core$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
Python 3.8.6

If we need to provide more information, please let us know.

**Comment by Kirill888** [comment]
We do not connect to real AWS infrastructure for running S3 related tests. Tests should be succeeding on any developer machine.  And they are succeeding on CI currently:

https://github.com/opendatacube/datacube-core/runs/1497009388?check_suite_focus=true#step:8:291

These kind of problems are usually indicative of broken Python environment, in the case of `test_utils_{aws|dask}` we use `moto` to mock interactions with S3. So check your installation for moto|botocore|boto3 compatibilities.

You can verify that the code does work by running the test in docker with a "known to work" python environment:

`./check-code.sh --with-docker integration_tests`

For celery test failure see #1037, basically you need to downgrade Celery to 4.x.x series.

**Comment by Kirill888** [comment]
Are you installing `datacube` into a virtual environment or are you using conda? If using plain virtual environment you can run `pip check` to see if you have incompatible versions of boto related libraries.

**Comment by Kirill888** [comment]
It could also be that the tests are not fully isolated from some AWS related configurations you might have on your developer machine. Tests do attempt to fully control configuration of the boto library, but I don't think we are particularly thorough in that regard, and there is no easy way to verify that isolation works well. PR with improved test isolation are welcome if you have time to debug that.
