### ISSUE TITLE
Supported data formats for Indexation/ingestion

### ISSUE THREAD

**Issue by christophenoel** [opendatacube/datacube-core#1056]
Hello team,

I can't find in the doc any information about the supported source data formats. 
Do you have a list somewhere ? Does it support JP2K, Zarr, ENVI, HDF5, ... ?

Thank you very much !

**Comment by fivejjs** [comment]
As far as I know, mostly used data format is cloud optimzed GeoTIFF. datacube use rasterio to pick up data. You can start with that first.
