### ISSUE TITLE
Documentation build currently not up-to-date

### ISSUE THREAD

**Issue by maawoo** [opendatacube/datacube-core#1058]
Hi there!

I just checked the [Dataset Documents](https://opendatacube.readthedocs.io/en/latest/ops/dataset_documents.html) page and was wondering why the EO3 format is not mentioned anymore. 
Seeing the actual page in the repository [here](https://github.com/opendatacube/datacube-core/blob/develop/docs/ops/dataset_documents.rst) and reading about problems related to the build process as mentioned in #879, I guess the current build is broken. The links mentioned in #1035 are also broken again and other pages might be affected as well. 

Also the "Edit on Github" button in the top right corner leads to a dead link in an outdated forked repository. Probably a good idea to fix this as well, so people can find the actual source of the documentation more easily.

Cheers, Marco

**Comment by Kirill888** [comment]
@maawoo thanks for bringing this to our attention, looks like read the docs site got somehow reverted to a 2 years ago state, see this page for example: https://readthedocs.org/projects/opendatacube/builds/ for me right now it says last build was 2 years ago

![image](https://user-images.githubusercontent.com/1428024/107279944-cf038b80-6aab-11eb-8b94-85fcd9bbcf1e.png)

Strange, we will have to investigate what is going on.

**Comment by alexgleith** [comment]
Hey @maawoo that was a test docs deployment, which should have been cleaned up 2 years ago.

This is the production ODC Docs page: https://datacube-core.readthedocs.io/en/latest/

**Comment by maawoo** [comment]
Thanks for clearing that up! 
Someone should fix the links on the homepage then (e.g. [here](https://www.opendatacube.org/resources) and [here](https://www.opendatacube.org/installation)) 😉

**Comment by alexgleith** [comment]
Thanks for this! I think I've fixed all the links. Let me know if you find any others!
