### ISSUE TITLE
Ingest features - setting origin & no resampling

### ISSUE THREAD

**Issue by andrewdhicks** [opendatacube/datacube-core#106]
From the hack days in March 2016:
Edward King's sample input data was a global NetCDF in geographic projection.
Issues arising when writing the storage config:
- No way to specify to not to resample the input data. (Instead used 'nearest' and hoped that the rest of the settings were correct.
- No way to specify the origin of the tile index, so the single netCDF file got tiled into 4 because the (0,0) point was in the middle of the range (-180, 180), (90, -90)

**Comment by v0lat1le** [comment]
ingester configuration now has `storage/origin` for setting origin
