### ISSUE TITLE
band  index not used during retrieval

### ISSUE THREAD

**Issue by aashish24** [opendatacube/datacube-core#1062]
### Expected behaviour
 I have a 3 band raster and I generated a dataset json which refers to each band with index. I expected that during retrieval I will get band data from each band but they all are same

Here is the file raw:

```json
{
  "$schema": "https://schemas.opendatacube.org/dataset",
  "id": "b8cf8525-d741-5078-9c5f-1dc3ac63e2e4",
  "crs": "epsg:32639",
  "grids": {
    "default": {
      "shape": [
        257,
        247
      ],
      "transform": [
        10.01740448577763,
        0.0,
        624232.6871839789,
        0.0,
        -9.999193363089173,
        2652485.662655362,
        0.0,
        0.0,
        1.0
      ]
    }
  },
  "product": {
    "name": "s10"
  },
  "label": "7658b5047535294f_2019-07-01_e8cce371",
  "properties": {
    "eo:platform": "s10",
    "datetime": "2019-07-04 13:07:05Z",
    "proj:epsg": 32639,
    "odc:processing_datetime": "2019-07-04 13:07:05Z",
    "odc:file_format": "GeoTIFF"
  },
  "measurements": {
    "band_1": {
      "path": "7658b5047535294f_2019-07-01_e8cce371.tif",
      "band":1
    },
    "band_2": {
      "path": "7658b5047535294f_2019-07-01_e8cce371.tif",
      "band":2
    },
    "band_3": {
      "path": "7658b5047535294f_2019-07-01_e8cce371.tif",
      "band":3
    }
  },
  "lineage": {},
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          624233.0,
          2649916.0
        ],
        [
          624233.0,
          2652486.0
        ],
        [
          626707.0,
          2652486.0
        ],
        [
          626707.0,
          2649916.0
        ],
        [
          624233.0,
          2649916.0
        ]
      ]
    ]
  }
}
```

### Actual behaviour

... eg. Incorrect result, python stacktrace, etc. ...

### Steps to reproduce the behaviour

... Include code, command line parameters as appropriate ...

### Environment information

* Which ``datacube --version`` are you using?
* What datacube deployment/enviornment are you running against?

**Comment by aashish24** [comment]
Open Data Cube core, version 1.8.4.dev53+gafca228

using Conda

**Comment by Kirill888** [comment]
@aashish24 have you verified that bands actually differ within the file? 

- Can you share `7658b5047535294f_2019-07-01_e8cce371.tif` 
- What version of `rasterio` library are you using? There have been bugs around multi-band access in `rasterio` the past, but a while ago.
- If you have been iterating on the dataset document, are you sure that what you are posting here is the same as what you have in the database. `datacube dataset update` might refuse to update metadata for example.
