### ISSUE TITLE
Update documentation for product spec to be EO3 compatible

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#1063]
Confusing old style product specs are here:

https://datacube-core.readthedocs.io/en/latest/ops/indexing.html#product-definition

new product spec example is here:
https://datacube-core.readthedocs.io/en/latest/ops/product.html

**Comment by iteayyy** [comment]
I wonder, is there any difference between EO3 and EO in ingest specification?
I got a problem when I load ingest data(EO3 format), the 'time' item doesn't match.
