### ISSUE TITLE
Need the spatial coords to carry correct `spatial_ref` and `crs`

### ISSUE THREAD

**Issue by emmaai** [opendatacube/datacube-core#1072]
### Expected behaviour
The spatial coordinates `x` and `y` should have correct `spatial_ref` and `crs` after reproject

### Actual behaviour
Only the values are changed but with the old `spatial_ref` and no `crs`. Hence the `results.geobox` crs is wrong.
https://github.com/opendatacube/datacube-core/blob/6ee0462c5de320d820aa4fdd27a4807fe2ab76c2/datacube/virtual/impl.py#L909-L910

### Steps to reproduce the behaviour
N/A

### Environment information

* Which ``datacube --version`` are you using?
  Open Data Cube core, version 1.8.4.dev52+g07bc51a5
* What datacube deployment/enviornment are you running against?
  Sandbox

**Comment by uchchwhash** [comment]
@emmaai I somehow did not manage to reproduce the issue. See PR #1074 please.
