### ISSUE TITLE
Using dataset indexed with vsicurl s3 path does not work for netcdf

### ISSUE THREAD

**Issue by massettiSGM** [opendatacube/datacube-core#1087]
Using dataset indexed with vsicurl s3 path does not work for netcdf.
We tried a number of vsi url options directly on rasterio.open()
Apparently what is not compatible with rasterio is wrapping the path in netCDF:{path}:{variable}:
/vsicurl/https://era5-pds.s3.amazonaws.com/2019/02/data/air_temperature_at_2_metres_1hour_Maximum.nc

https://github.com/opendatacube/datacube-core/blob/baf316ddb0901300140b7d22683741c4489a6b5a/datacube/storage/_rio.py#L268
returning the url_str in _build_hdf_uri without wrapping it as above works. However, it does not work with subdatasets.

```
def _build_hdf_uri(url_str: str, fmt: str, layer: str) -> str:
    if is_vsipath(url_str):
        base = url_str
        return base #add this line
    else:
        url = urlparse(url_str)
        if url.scheme in (None, ''):
            raise ValueError("Expect either URL or /vsi path")

        if url.scheme != 'file':
            raise RuntimeError("Can't access %s over %s" % (fmt, url.scheme))
        base = str(uri_to_local_path(url_str))

    return '{}:"{}":{}'.format(fmt, base, layer)
```

I will add more context as soon as I can

**Comment by Kirill888** [comment]
@massettiSGM at the time that code was written netcdf driver did not support VSI filesystems, I believe it does now with more recent GDAL versions. Still, we have no practical experience dealing with netcdf/hdf files over network. I can do 

```
gdalinfo "/vsicurl/https://era5-pds.s3.amazonaws.com/2019/02/data/air_temperature_at_2_metres_1hour_Maximum.nc"
```

with GDAL installed from Ubuntu 20.04 official repo
```
Subdatasets:
  SUBDATASET_1_NAME=HDF5:"/vsicurl/https://era5-pds.s3.amazonaws.com/2019/02/data/air_temperature_at_2_metres_1hour_Maximum.nc"://air_temperature_at_2_metres_1hour_Maximum
  SUBDATASET_1_DESC=[672x721x1440] //air_temperature_at_2_metres_1hour_Maximum (32-bit floating-point)
  SUBDATASET_2_NAME=HDF5:"/vsicurl/https://era5-pds.s3.amazonaws.com/2019/02/data/air_temperature_at_2_metres_1hour_Maximum.nc"://time1_bounds
  SUBDATASET_2_DESC=[672x2] //time1_bounds (64-bit floating-point)
```

```
gdalinfo HDF5:"/vsicurl/https://era5-pds.s3.amazonaws.com/2019/02/data/air_temperature_at_2_metres_1hour_Maximum.nc"://air_temperature_at_2_metres_1hour_Maximum
```

also seems to work, but slower.

This sample code sort of "works" in my setup, but geo-registration is missing. You need to make sure your `rasterio/gdal` combo supports hdf5+vsicurl.

```python
from datacube.storage._rio import _url2rasterio
import rasterio

url = _url2rasterio("/vsicurl/https://era5-pds.s3.amazonaws.com/2019/02/data/air_temperature_at_2_metres_1hour_Maximum.nc", 
                    fmt="HDF5",
                    layer="//air_temperature_at_2_metres_1hour_Maximum")
print(url)

with rasterio.open(url, "r") as src:
    print(src.meta)
```

**Comment by Kirill888** [comment]
However using `fmt="NETCDF"` didn't work for me, and I guess this is what's needed to parse CRS information. So obviously my setup doesn't have working `NETCDF+vsicurl` combo, not sure if that is supported at all and with what versions of what libraries.
