### ISSUE TITLE
Error message for missing file is confusing

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#1088]
### Expected behaviour

```bash
> datacube dataset add /no/such/file.yaml
ERROR: no such file "/no/such/file.yaml"
```

### Actual behaviour

```
ERROR No supported metadata docs found for dataset /no/such/file.yaml
```

### Steps to reproduce the behaviour

```
datacube dataset add  /no/such/file.yaml
```
observe confusing message.

### Environment information

code in `develop` branch.

### Remediation Suggestions

Error message originates from here:
https://github.com/opendatacube/datacube-core/blob/80d466a2635ab37fbe33bb283b77df305e3c9236/datacube/ui/common.py#L91

There is some pretty involved logic in "locating actual metadata file", code accepts all sorts of inputs:

- directory
- some file in directory with a sibling file named `{base}.{agdc-md,agdc-metadata}.{yaml,yml,json}{,.tar.gz, .tgz}`.

Hence the error message, but really, if input is a "file path" and it is not a path that exists on the filesystem the error message should say just that: `"Supplied path '/no/such/file.yml' does not exist"`. And the current message should only be used when supplied path is an existing file/directory but is not a metadata file, say it is a `.tiff` image, but there is no metadata file next to it, or it's a directory and there are no metadata file in it.

**Comment by SpacemanPaul** [comment]
Slightly trickier than @Kirill888 implied, but not much.  :)
