### ISSUE TITLE
Readthedocs page has outdated links

### ISSUE THREAD

**Issue by james-blitzm** [opendatacube/datacube-core#1098]
### Expected behaviour

Links on https://opendatacube.readthedocs.io/en/latest/dev/api/index.html should lead to relevant reference pages.

### Actual behaviour

HTTP 404 responses for various links on https://opendatacube.readthedocs.io/en/latest/dev/api/index.html, such as "Edit on Github" and "example Jupyter notebooks"

### Steps to reproduce the behaviour

Navigate to the OpenDataCube documentation on readthedocs (as referenced from the resources page of the OpenDataCube website: https://www.opendatacube.org/resources

### Environment information

1. Macbook + Chrome.

**Comment by Kirill888** [comment]
@james-blitzm 
real docs are here:
https://datacube-core.readthedocs.io/en/latest/

@alexgleith I believe you set up the docs pointed by James a while back, any chance you can either

- Update it to point to real docs
- Delete that whole thing
- Set up continuous updating to both 

I have no permissions to do anything to that site it seems.

**Comment by Kirill888** [comment]
we have updated `opendatacube.` to be the same as `datacube-core.`

@james-blitzm did you just google it, or have you followed a link from some documentation site?

**Comment by james-blitzm** [comment]
I arrived at the above after googling Open Data Cube, then reaching the resources page here: https://www.opendatacube.org/resources

**Comment by james-blitzm** [comment]
There are a few links on that page which need to be updated.

**Comment by Kirill888** [comment]
I see it now, the one at the very bottom points to `opendatacube.` while one at the top links to `datacube-core.` docs, @alexgleith who has write permissions to the resources page.

**Comment by Kirill888** [comment]
alright this has been updated now on resources page as well
