### ISSUE TITLE
the command line naming should be reviewed

### ISSUE THREAD

**Issue by zhang01GA** [opendatacube/datacube-core#114]
I found the commandline command can be simplified and made more consistent.
datacube-config, datacube-search, datacube-ingest may be replaced by 

The idea is to mimic good Linux command like git  and awscli.

So let's have a suite of commands like:

agdc ingest [options] argments
agdc config [options] argments
agdc search [options] arguments
agdc list*
agdc verb [options] arguments

**Comment by v0lat1le** [comment]
continue in #137
