### ISSUE TITLE
List products should report licenses

### ISSUE THREAD

**Issue by uchchwhash** [opendatacube/datacube-core#1141]
### Expected behaviour
Declaring licenses for products helps the user map out the usability of the product for specific purposes.

### Actual behaviour
List product lists many things, but a license is not one of them.

### Steps to reproduce the behaviour
Pretty much
```
dc.list_products()
```

### Environment information

* Which ``datacube --version`` are you using?
- 1.8.3
* What datacube deployment/enviornment are you running against?
- Any

**Comment by uchchwhash** [comment]
@robbibt this is now resolved, right?

**Comment by robbibt** [comment]
@uchchwhash Not yet - I need to revise #1145 to match products by name in the dataset count code
