### ISSUE TITLE
Enable search / get data by Landsat GQA threshold

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#115]
Being able to filter get data requests by geometry assessment quality is an essential feature for ensuring pixels line up.

eg. abs_iterative_mean_residual.x < 1and abs_iterative_mean_residual.y < 1 and abs_iterative_mean _residual is not null

**Comment by jeremyh** [comment]
This is doable as a configuration change, not a code change.

**Comment by jeremyh** [comment]
But it'll be a good test to see if search fields are being pushed through all layers (and not being hardcoded anywhere).

**Comment by v0lat1le** [comment]
Searching derived/ingested products could be interesting also

**Comment by jeremyh** [comment]
This will be done when we update the metadata types: #119

**Comment by simonaoliver** [comment]
We're going to have to tackle this one sooner rather than later as workflows will depend on having stackable data.

**Comment by jeremyh** [comment]
We currently have these values in the Level 1 dataset metadata, but you're specifically talking about searching NBAR data, right?

**Comment by simonaoliver** [comment]
You might expect any product using these downstream to use this to filter data out of an analysis - nbar / pq / level 1/ fc etc. As per PQ in that it can be applied to all products from level 1 (including).

**Comment by omad** [comment]
It has been possible to filter by fields on parent datasets for a while now, using `source_filter`.

An example request for Landsat, filtered by GQA would be:
```python
    dc.load(product='ls8_nbar_albers', x=(100.1, 100.2), y=(-35.1, -35.2), 
        source_filter={
            product='ls8_level1_scene',
            gqa_mean_xy: [-1, 1]})
```

When the index is being queried for datasets, this will traverse the tree of parent datasets, until one of the appropriate `product` is found, and then apply the filter.
