### ISSUE TITLE
question

### ISSUE THREAD

**Issue by leaf0917** [opendatacube/datacube-core#1151]
Can I get the results like deformation result through a series of processing of _ODC_ using _Sentinel-1_ scene？

**Comment by whatnick** [comment]
Perhaps @mcgarth has an answer for you.

**Comment by mcgarth** [comment]
As far as I'm aware this is not possible in ODC. If you have Sentinel-1 InSAR data (interferograms) you could try https://github.com/GeoscienceAustralia/PyRate to get deformation

**Comment by leaf0917** [comment]
> As far as I'm aware this is not possible in ODC. If you have Sentinel-1 InSAR data (interferograms) you could try https://github.com/GeoscienceAustralia/PyRate to get deformation

Thanks reply
