### ISSUE TITLE
Virtual products broken

### ISSUE THREAD

**Issue by benjimin** [opendatacube/datacube-core#1152]
Virtual products seem to be broken in the latest dev releases.

This relates to opendatacube/datacube-wps#111.

Code to replicate:
```python
import datacube.virtual, datacube.utils.geometry
print(datacube.__version__)

# declare virtual product
wofs = dict(product='wofs_albers',
            measurements=['water'],
            group_by='solar_day',
            fuse_func='digitalearthau.utils.wofs_fuser')
fc = dict(collate=[dict(product=f'ls{i}_fc_albers', group_by='solar_day', measurements=['BS', 'PV', 'NPV'])
                   for i in [5,7,8]])
product = datacube.virtual.construct(juxtapose=[fc, wofs])

# define query
poly = datacube.utils.geometry.Geometry(
            {
                "type": "Polygon",
                "coordinates": [
                    [
                        (147.28271484375003, -35.89238773935897),
                        (147.03277587890628, -35.663990911348115),
                        (146.65237426757815, -35.90684930677119),
                        (147.09182739257815, -36.15894422111004),
                        (147.28271484375003, -35.89238773935897),
                    ]
                ],
            },
            crs=datacube.utils.geometry.CRS("EPSG:4326"))
time=("2019-03-05", "2019-07-10")

# perform query
dc = datacube.Datacube()
bag = product.query(dc, time=time, geopolygon=poly)
print(len(list(bag.contained_datasets())))

# elicit warnings
box = product.group(bag)

# elicit error
box.shape
```

Output on NCI VDI:
```
1.8.3
68
(17, 2208, 2268)
```

Output on DEA Sandbox:
```
1.8.4.dev81+g80d466a2
/env/lib/python3.6/site-packages/datacube/drivers/postgres/_connections.py:87: SADeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method.
  username=username, password=password,
68
/env/lib/python3.6/site-packages/datacube/virtual/utils.py:17: UserWarning: select_unique may have failed: None is not the same as GeoBox(Geometry({'type': 'Polygon', 'coordinates': (((146.62349744588062, -35.70273335048077), (146.69355477162244, -36.19687547403131), (147.31908398863132, -36.13696212625085), (147.2461000005716, -35.643186470762565), (146.62349744588062, -35.70273335048077)),)}, CRS('EPSG:4326')))
  .format(first, other))
/env/lib/python3.6/site-packages/datacube/virtual/utils.py:17: UserWarning: select_unique may have failed: True is not the same as False
  .format(first, other))
/env/lib/python3.6/site-packages/datacube/virtual/utils.py:17: UserWarning: select_unique may have failed: Geometry({'type': 'Polygon', 'coordinates': (((147.28271484375003, -35.89238773935897), (147.03277587890628, -35.663990911348115), (146.65237426757815, -35.90684930677119), (147.09182739257815, -36.15894422111004), (147.28271484375003, -35.89238773935897)),)}, CRS('EPSG:4326')) is not the same as None
  .format(first, other))
---------------------------------------------------------------------------
VirtualProductException                   Traceback (most recent call last)
<ipython-input-1-570757546974> in <module>
     37 
     38 # elicit error
---> 39 box.shape

/env/lib/python3.6/site-packages/datacube/virtual/impl.py in shape(self)
    132         """
    133         if self.load_natively:
--> 134             raise VirtualProductException("shape requires known geobox")
    135 
    136         return self.box.shape + self.geobox.shape

VirtualProductException: shape requires known geobox
```

**Comment by omad** [comment]
Any idea about this @uchchwhash ?

**Comment by uchchwhash** [comment]
The issue here is that somewhere between `datacube-1.8.3` and `develop` the implementation of `GridSpec` has changed.
The WPS test suite pulls in some product definitions, and for the `wofs_albers` product the `GridSpec` is there where the relevant section of the product definition is:
```
storage:
  crs: EPSG:3577
  dimension_order:
  - [time, y, x]
  resolution:
    x: 25
    y: -25
  tile_size:
    x: 100000.0
    y: 100000.0
```
whereas for the `ls8_fc_albers` product for example:
```
storage:
  crs: EPSG:3577
  resolution:
          x: 25
          y: -25
  dimension_order: ['time', 'y', 'x']
```
the missing `tile_size` key results in a `None` for its `GridSpec`. Here's the current code:
https://github.com/opendatacube/datacube-core/blob/7e6c1825f8ea90f961c36b12f48c03e6f8425e21/datacube/model/__init__.py#L523

Now without going into the philosophical question of what makes a `GridSpec` complete, let me just note that whether or not the datasets have a fixed tile size has hardly anything to do with loading the data with a specified CRS and resolution. Of course, the virtual product mechanism thinks, given that `product.grid_spec` is `None`, that this is not a gridded product with known CRS and resolution, but it actually is.

My personal preference is for @benjimin to update the product catalog CSV that the WPS testsuite uses to point to a version where the FC Albers products report their tile size. Mostly because it is not immediately obvious to me whether a `GridSpec` needs to have a tile size to be legit (I will admit that it sounds rather odd to me).

Thoughts @omad?

**Comment by benjimin** [comment]
I don't think the API should _require_ **tile size**. 

I thought the tile size parameter had only two functions:

- To configure the _ingestor_ for reformatting a collection into tiles, which historically was necessary in the period when stacked NetCDF (rather than GeoTIFF/COG) was strongly preferred and inodes (file counts) were tightly constrained (by NCI policy).
- As a potential optimisation hint, so that continental workflows could size and align their compute chunks to have common factors with the underlying storage scheme and thereby improve data read efficiency.

Nowadays however, many products are indexed without intent to ingest; the ODC supports storage of irregularly overlapped scenes, and of products for which the datasets are not all in the same CRS. I don't think it is meaningful to declare any tile size for products that are not stored in a regular grid. At some point the virtual product API will need to be supplied an output resolution and CRS, but I'm guessing its behaviour has no real dependence on the tile size value?

**Comment by uchchwhash** [comment]
Agreed. If we get @omad 's blessings, we can drop `tile_size` as a requirement for valid grid spec, and this issue is resolved.

**Comment by uchchwhash** [comment]
Looks like we didn't achieve a resolution of the underlying problem here. But this certainly is not a virtual product problem. Closing.
