### ISSUE TITLE
Move `rio_slurp_xarray` and similar `testutils` functions to `datacube.utils`?

### ISSUE THREAD

**Issue by robbibt** [opendatacube/datacube-core#1159]
We currently recommend this function as the best way to stream and resample data from the cloud in Python:
```
from datacube.testutils.io import rio_slurp_xarray
```
For example, in the guide to reprojecting data here: https://docs.dea.ga.gov.au/notebooks/Frequently_used_code/Reprojecting_data.html

However, this `testutils` source location makes it feel like less than an official part of ODC core, and reduces confidence in the tool.

It would be good to promote functions like this to a more central location in `odc-core`, e.g. perhaps somewhere in `datacube.utils`?

**Comment by robbibt** [comment]
I'd also suggest a more intuitive rename for `rio_slurp_xarray` to align with similar `xarray`-related utility functions: `xr_load`? This would also mimic `dc.load`, which is appropriate as this function performs a similar function (loading data into datacube-compatible `xarray` format).

**Comment by woodcockr** [comment]
I'm thinking this should issue should probably be open still since DEA notebooks are using it from its testutils directory. I won't pin it though to stop stalebot in case I am wrong. It will go away again in a few months if it is supposed too.
