### ISSUE TITLE
Implement and demonstrate method for xarray groupby siderial day

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#116]
Observations within a storage unit can be a duplicate with different timestamps.
A groupby solution is required to make statistical sense and avoid double counts in statistics
Because we don't group observations at ingest, we need to do it during get data.

UTC days don't work (acquisitions cross day boundaries)
siderial days look like the best solution https://en.wikipedia.org/wiki/Sidereal_time
Needs to implement order i.e. north over south for southern hemisphere (opposite for northern)
pyephem enables calculation of siderial day for a given position http://rhodesmill.org/pyephem/quick.html 
xarray supports groupby

**Comment by v0lat1le** [comment]
Why not use local timezone days? Much simpler and solves that particular issue.

**Comment by v0lat1le** [comment]
Also, since landsat orbit is sun-synchronous wouldn't [Solar Time](https://en.wikipedia.org/wiki/Solar_time) make more sense? Siderial day will result in a 4 min/day drift.

**Comment by andrewdhicks** [comment]
GDF used the mean latitude to offset from UTC:

```
def solar_date(self, record_dict):
    '''
    Function which takes a record_dict containing all values from a query in the get_db_slices function 
    and returns the solar date of the observation
    '''
    # Assumes slice_index_value is time in seconds since epoch and x values are in degrees
    #TODO: Make more general (if possible)
    # Note: Solar time offset = average X ordinate in degrees converted to solar time offset in seconds 
    return datetime.fromtimestamp(record_dict['slice_index_value'] + (record_dict['x_min'] + record_dict['x_max']) * 120).date()
```

(From https://github.com/GeoscienceAustralia/gdf/blob/master/gdf/__init__.py#L661)
