### ISSUE TITLE
Relocate `dataset_predicate` functionality from `dc.load` to `dc.find_datasets`?

### ISSUE THREAD

**Issue by robbibt** [opendatacube/datacube-core#1160]
This PR (https://github.com/opendatacube/datacube-core/pull/1148) recently added new `dataset_predicate` functionality to `dc.load`, allowing users to filter datasets returned by `dc.find_datasets` prior to loading them.

Further discussion on Slack suggested that this functionality might be better placed directly inside `dc.find_datasets` instead, as this would mean it could be used in both `dc.find_datasets` and called as a kwarg in `dc.load`.

I quite like this idea, but my main hesitation would be discoverability. One of the main motivations for adding it to `dc.load` was that this predicate functionality is one of our top-asked questions on Slack/Stack - if it was moved completely to `dc.find_datasets` I'd worry that it would remain hidden as an undocumented kwarg for most users who chiefly engage with `dc.load`. Could we move the actual code to `dc.find_datasets` but still include a reference to it in the doc string for `dc.load` (or a param that simply calls the `dc.find_datasets` method)?

**Comment by robbibt** [comment]
Would love to hear your thoughts @uchchwhash @walsh-andrew @MatthewJA !

**Comment by walsh-andrew** [comment]
I defo vote for adding this functionality to dc.find_datasets. One thing I am trying to do is answer a question like: "For a given location, what is the probability that it is cloudy during August?" I can easily find out the cloud cover percentage, as a proxy for probability for any given month using find_datasets. I don't believe I can do this with dc.load. So would make sense to have dataset_predicate on find_datasets for this use case at least.

**Comment by robbibt** [comment]
Looks like @uchchwhash already has a PR here that does just this - whoops! #1156
