### ISSUE TITLE
Move `xr_reproject` from `odc-tools` to `datacube-core`

### ISSUE THREAD

**Issue by uchchwhash** [opendatacube/datacube-core#1161]
### Expected behaviour
Reprojecting data is a fundamental GIS operation and is at the heart of what `datacube` does, so it's only fitting that we have this functionality as a library function.

### Actual behaviour
The current implementation still has not left the prototype package despite being widely used and thoroughly tested.

**Comment by snowman2** [comment]
I would prefer to see this: https://github.com/opendatacube/odc-tools/issues/58 🤞

**Comment by uchchwhash** [comment]
You feel rather strongly about this one, don't you @snowman2? Totally agreed.
