### ISSUE TITLE
help wanted 

### ISSUE THREAD

**Issue by mariembensalem** [opendatacube/datacube-core#1163]
hi, after indexed images I try to show the scenes in datacube explorer  (datacube version 1.8.4.dev193+g3997b90f) 
when I try to initialise and create product summaries with cubedash-gen --init --all i have problem with ls8_level1_usgs 
![Capture d’écran de 2021-07-27 14-52-09](https://user-images.githubusercontent.com/83786015/127168918-f521005b-23df-4821-ad5e-4aa4527eb23e.png)

**Comment by whatnick** [comment]
Please include stacktrace as text rather than screenshot for easier readability. Technical support is best requested via GIS stackexchange using the open-data-cube tag.

**Comment by jeremyh** [comment]
Hey Meriem651, thanks for the report.

The traceback looks like quite an old version of Explorer you're pairing with a recent ODC: I recommend trying with the current version of each, as I believe newer Explorer supports missing creation-time metadata fields like you have in your data.

Feel free to post on https://gis.stackexchange.com/questions/tagged/open-data-cube as suggested by whatnick if you still face issues.

**Comment by mariembensalem** [comment]
thank you for your help


Le mer. 28 juil. 2021 à 04:07, Jeremy Hooke ***@***.***> a
écrit :

**Comment by mariembensalem** [comment]
Hi, how can I get the right version of datacube-explorer-2. 5. 4 because a
try to install this one
https://github.com/opendatacube/datacube-explorer/releases but doesn't work
for me

**Comment by jeremyh** [comment]
I recommend posting the error you're getting in a question here: https://gis.stackexchange.com/questions/tagged/open-data-cube

**Comment by mariembensalem** [comment]
Thank you!

Le ven. 30 juil. 2021 à 00:30, Jeremy Hooke ***@***.***> a
écrit :
