### ISSUE TITLE
[Documentation] ops -> Overview page is broken

### ISSUE THREAD

**Issue by EHJ-52n** [opendatacube/datacube-core#1165]
The documentation page "Overview" is  broken.

* **Screenshot**: ![opendatacube_documentation_operations_overview_broken](https://user-images.githubusercontent.com/3839896/127303113-f1bd7a96-4677-4b57-aa1e-7d1da4470d4c.png)
* **Link**: https://datacube-core.readthedocs.io/en/latest/ops/overview.html

**Comment by SpacemanPaul** [comment]
Whatever was causing this, it has apparently now been fixed.
