### ISSUE TITLE
Documentation typo.

### ISSUE THREAD

**Issue by patfla** [opendatacube/datacube-core#1171]
Currently in https://datacube-core.readthedocs.io/en/latest/ops/indexing.html - and wrong.
pip install –extra-index-url=”https://packages.dea.ga.gov.au” odc_apps_dc_tools

Correct - from https://github.com/opendatacube/odc-tools/tree/develop/apps/dc_tools
pip install --extra-index-url="https://packages.dea.ga.gov.au" odc_apps_dc_tools

It seems I 'might' be able to edit this on github except https://github.com/opendatacube/datacube-core/blob/develop/docs/ops/indexing.rst shows double hyphen - which is correct - so something's getting garbled in translation.

**Comment by Kirill888** [comment]
Thanks,

this has been "fixed", these packages are now on PyPi and so extra args are no longer needed
