### ISSUE TITLE
Missing required dependencies in default install

### ISSUE THREAD

**Issue by dlubawy-ama** [opendatacube/datacube-core#1172]
### Expected behaviour

Default datacube-core install also installs required dependency packages.

### Actual behaviour

Default install is missing packages needed for core functionality.

### Steps to reproduce the behaviour

```
pip install datacube

datacube --help
```

Result: `ModuleNotFoundError: No module named 'botocore'`

### Environment information

Fresh Python 3.6.8 virtualenv with pip 21.2.3 

datacube==1.8.4

### Issue

76eb3508096ed94e50c341d1614ed9e6e022e39f - Added AWS packages as a dependency for the default install.

Current workaround is to install datacube-core with 's3' extras: `pip install datacube[s3]`

**Comment by Kirill888** [comment]
There is also this:

https://github.com/opendatacube/datacube-core/blob/e5471533ecb4541009c0cb512ea88fedc7685330/datacube/utils/dask.py#L17-L19

I guess we need to decide whether to keep boto dependency optional, in which case these imports need to be moved into function or guarded with `try:` blocks. Or whether to make botocore/boto3 a non-optional dependency.

@SpacemanPaul one way to fix IAM code is to move `obtain_new_iam_auth_token` out of `utils.aws.` and into db code.

**Comment by Kirill888** [comment]
my preference is to try to keep things working without boto libs installed.

**Comment by omad** [comment]
Agreed, it would be nice to keep things functional without requiring `boto3/core`. I think we're close to the point where most people using datacube are accessing data on `s3`, but ideally we want to remain platform agnostic.

**Comment by Kirill888** [comment]
Ok, I'll make the changes and we can then do `1.8.4.post1` release and then update conda see #1173.

**Comment by omad** [comment]
Awesome, thank you @Kirill888 :-)
