### ISSUE TITLE
 cannot import name 'clock_gettime' from 'time' (unknown location)

### ISSUE THREAD

**Issue by bartzwemmer** [opendatacube/datacube-core#1176]
### Expected behaviour
Import time

### Actual behaviour

  File "C:\ProgramData\Anaconda3\lib\site-packages\datacube\drivers\postgres\_connections.py", line 20, in <module>
    from time import clock_gettime, CLOCK_REALTIME

ImportError: cannot import name 'clock_gettime' from 'time' (unknown location)

cannot import name 'clock_gettime' from 'time' (unknown location)

### Steps to reproduce the behaviour
  from ._connections import PostgresDb

### Environment information
Python 3.8.11
* Which ``datacube --version`` are you using?
Unknown, it's referenced in geocube on conda-forge
* What datacube deployment/enviornment are you running against?
n/a

Additional notes:
time.clock has been removed in Python 3.8 after being deprecated in Python 3.3. The recommendation is to change clock by either time.perf_counter or time.process_time.

**Comment by Kirill888** [comment]
@bartzwemmer looks like it's `1.8.4` version, in the future you can check version with either running `datacube --version` command after activating the environment, or using `pip list` or `conda list` command.

@SpacemanPaul @omad @jeremyh problem was introduced in this PR #1168, `time.clock_gettime` is a Linux only method and will not work on windows. Note that we do not run any tests on windows at all.

**Comment by bartzwemmer** [comment]
Thanks for the quick reply. 
It's indeed datacube 1.8.4. 

On the [project website](https://www.opendatacube.org/) it says "Typical installations run on Linux, MacOS, and Windows."

**Comment by Kirill888** [comment]
> On the project website it says "Typical installations run on Linux, MacOS, and Windows."

But we only run tests on Linux... and code was importing Unix only method from standard library

**Comment by bartzwemmer** [comment]
I can confirm that on Windows in conda, switching to version 1.8.3 can be a work around for now.

**Comment by snowman2** [comment]
Do you want to add a simple test for windows? It is pretty simple to do with GitHub workflows + conda [ref](https://github.com/corteva/geocube/blob/master/.github/workflows/tests.yaml).

**Comment by bartzwemmer** [comment]
Thanks for the quick fixing
