### ISSUE TITLE
Proposal: Add the ability to delete datasets from the database

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#1178]
I think it should be possible to delete datasets from an ODC database.

At the moment, it&rsquo;s not possible with the `datacube` CLI or the API. The closest
option is `datacube dataset archive`, but this leaves dataset records in the
database, but sets an `archived` flag set so that they are invisible to searches
and data loading. Keeping old records will cause problems if there is ever a
dataset ID clash, makes it hard to remove a product, see #177 and for many systems
is just an accumulation of cruft over time.

**Background**

The Open Datacube API, Database and tools was originally built as [a System of
Record](https://en.wikipedia.org/wiki/System_of_record), and doesn&rsquo;t include options for deleting records from the database. This
is reasonable for some Open Datacube deployments, but is user hostile
for:

-   people learning ODC, getting told to delete their database and start again
-   administrators dealing with data issues which can occur with large data
    archives. They need to run raw SQL to complete some tasks, which is
    inconvenient and dangerous.

**Proposal**

I propose that we add a `purge` sub-command to `datacube dataset`. It could take a
list of IDs of archived datasets, and should delete all trace of them from the
Database.

I think that this will be a big improvement over the current lack of
functionality. It&rsquo;s still safe for production systems, being a two step process
of Archive + Purge to delete dataset records. While also being easy enough for
users working in a development or two environment.

**Comment by SpacemanPaul** [comment]
Something similar for `datacube product` seeems a logical extension - but is a squirmier can of worms because of e.g. the index tables used by explorer and ows.

(Edit - sorry fat thumbs hit the "close with comment" button instead of "comment").

**Comment by Kirill888** [comment]
This is certainly a needed feature. We just need to carefully define what behaviours are going to be supported. I guess lineage is where things might become "unsafe". What behaviour do we expect if any active dataset points to the Dataset being purged via lineage? Should the purge be:

- Always refused
- Allowed but with an extra flag e.g.  `--force-lineage-unlink`
- Always allowed but with a warning, or with user confirmation

**Comment by omad** [comment]
> What behaviour do we expect if any active dataset points to the Dataset being purged via lineage? Should the purge be:
> 
>     * Always refused
>     * Allowed but with an extra flag e.g.  `--force-lineage-unlink`

I think we should refuse to purge datasets that are linked to active ones.

If a useful error message is displayed, explaining the error and listing the affected datasets, people could archive them if they want to remove everything.

Lets not over-engineer a feature unless there's significant demand for it.

**Comment by SpacemanPaul** [comment]
Implemented in #1199

> I think we should refuse to purge datasets that are linked to active ones.

I have not *explicitly* handled this case - triggering it will raise a fairly low-level SQLAlchemy foreign key constraint error and the whole transaction will roll back.
