### ISSUE TITLE
Add `get_tile` to API to support v1-style apps

### ISSUE THREAD

**Issue by andrewdhicks** [opendatacube/datacube-core#118]
Tile based processing using v1 style workflows (such as WofS) requires a list of tiles for a particular set of cells.
The v1 implementation provided the following fields:
- acquisition_id
- satellite
- start_datetime
- end_datetime
- end_datetime_year
- end_datetime_month
- x_index
- y_index
- xy
- datasets
  - product_name
  - product_path

**Comment by v0lat1le** [comment]
Should this live in a `legacy` sub-module? Doesn't seem to mix with the existing functions in the API. How are people to know which bits to use?

Anything v1 will be cell/tile based. Doesn't mean it can't be done any other way...

**Comment by andrewdhicks** [comment]
Current API has support for the following version 1 style features:
- `list_cells`
- `list_tiles`
- `get_dataset_by_cell`
- `get_data_array_by_cell`

The `list_tiles` function returns a dictionary that uniquely specifies a tile when unpacked and passed to the `get_[...]_by_cell` functions, removing the need for a specific `get_tile` function.
