### ISSUE TITLE
Task: make new release

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#1180]
Version `1.8.4` was released recently. Some issues have been reported by the community for that release

- Use of `botocore` libraries without a guard (#1172)
  - `pip install datacube` in an empty environment ends up with non-working setup until `boto3` is installed.
  - fixed in #1174 
- Use of Unix only methods without a guard (#1176)
  - Pip and conda installs of `datacube==1.8.4` don't work on Windows
  - fixed in #1177

I feel like these issues are important enough to warrant a new release to be done "soonish". 
Question: should this be `1.8.5` or `1.8.4.post1`, I'm no expert on semantic versioning.
In the past we just incremented version for similar issues `1.5.4 -> 1.5.5` and `1.6.0 -> 1.6.1`, so I would suggest we release `1.8.5`.

**Comment by alexgleith** [comment]
I'm fine with jumping to `1.8.5`.

One question is should we wait a little longer to see if anything else comes up?

**Comment by snowman2** [comment]
Probably fine either way. However, I agree with you on 1.8.5.

**Comment by snowman2** [comment]
> One question is should we wait a little longer to see if anything else comes up?

If releases aren't too onerous to do, making releases regularly is a good thing in my opinion. "release early, release often"

**Comment by Kirill888** [comment]
Release process is not too bad, conda was a bit trickier, but that was because many things changed in a year since last release. Maybe we can make it `1.8.5rc1` and if nothing comes up make it `1.8.5` later.

**Comment by alexgleith** [comment]
I reckon let's just go with a `1.8.5` and keep rolling forward!

So do we need to implement code fixes, @Kirill888? I'm happy to have a stab, if you're ok to review?

**Comment by Kirill888** [comment]
@alexgleith fixes were done, but it would be nice to actually test at least `datacube --help` on windows, I have no windows machine handy though.

**Comment by Kirill888** [comment]
But as @snowman2 pointed out somewhere else it can be done on github actions

**Comment by alexgleith** [comment]
Ok, I'll have a look into it this morning.

**Comment by alexgleith** [comment]
I made a mistake and committed to `develop`. I changed permissions so I can't do that again, sorry.

We have the import error for MacOS, see: https://github.com/opendatacube/datacube-core/runs/3345813391?check_suite_focus=true
