### ISSUE TITLE
DLL load failed: The specified procedure could not be found when import datacube

### ISSUE THREAD

**Issue by Jack-ee** [opendatacube/datacube-core#1187]
Dear all,

  I followed the instructions to install datacube. It's ok for the first five steps described [here](https://github.com/opendatacube/datacube-core)
```python
git clone https://github.com/opendatacube/datacube-core.git
conda create -n odc -c conda-forge python=3.6 datacube pre_commit
conda activate odc
cd datacube-core
pip install --upgrade -e .
pre-commit install
```
The 5-6 steps are not ok because it pump a dialog that need something to execute the .sh file.
When I run conda list, I found datacube 1.8.5 is already installed. I also installed geopandas, rasterio, rasterstats, tqdm packages, without any errors.
However, I got a error when import datacube in jupyter notebook. Here is the message. Can you help me how to solve it?
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-579517c2bb28> in <module>
----> 1 import datacube

c:\users\jack_dell\datacube-core\datacube\__init__.py in <module>
     27     __version__ = 'Unknown/Not Installed'
     28 
---> 29 from .api import Datacube
     30 import warnings
     31 from .utils import xarray_geoextensions

c:\users\jack_dell\datacube-core\datacube\api\__init__.py in <module>
      7 """
      8 
----> 9 from .core import Datacube, TerminateCurrentLoad
     10 from .grid_workflow import GridWorkflow, Tile
     11 

c:\users\jack_dell\datacube-core\datacube\api\core.py in <module>
     14 
     15 from datacube.config import LocalConfig
---> 16 from datacube.storage import reproject_and_fuse, BandInfo
     17 from datacube.utils import ignore_exceptions_if
     18 from datacube.utils import geometry

c:\users\jack_dell\datacube-core\datacube\storage\__init__.py in <module>
     15     RasterWindow)
     16 
---> 17 from ._base import BandInfo, measurement_paths
     18 from ._load import reproject_and_fuse
     19 

c:\users\jack_dell\datacube-core\datacube\storage\_base.py in <module>
      6 from urllib.parse import urlparse
      7 
----> 8 from datacube.model import Dataset
      9 from datacube.utils.uris import uri_resolve, pick_uri
     10 

c:\users\jack_dell\datacube-core\datacube\model\__init__.py in <module>
     18 
     19 from urllib.parse import urlparse
---> 20 from datacube.utils import geometry, without_lineage_sources, parse_time, cached_property, uri_to_local_path, \
     21     schema_validated, DocReader
     22 from .fields import Field, get_dataset_fields

c:\users\jack_dell\datacube-core\datacube\utils\geometry\__init__.py in <module>
      6 """
      7 
----> 8 from ._base import (
      9     Coordinate,
     10     BoundingBox,

c:\users\jack_dell\datacube-core\datacube\utils\geometry\_base.py in <module>
     17 import xarray as xr
     18 from affine import Affine
---> 19 import rasterio
     20 from shapely import geometry, ops
     21 from shapely.geometry import base

~\Anaconda3\envs\odc\lib\site-packages\rasterio\__init__.py in <module>
     20             pass
     21 
---> 22 from rasterio._base import gdal_version
     23 from rasterio.drivers import is_blacklisted
     24 from rasterio.dtypes import (

ImportError: DLL load failed: The specified procedure could not be found.
```
# And here is the packages I already installed
Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
aiohttp                   3.7.4.post0      py36h68aa20f_0    conda-forge
anyio                     3.3.0            py36ha15d459_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               20.1.0           py36h68aa20f_2    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
bleach                    4.0.0              pyhd8ed1ab_0    conda-forge
bokeh                     2.3.3            py36ha15d459_0    conda-forge
boost-cpp                 1.74.0               h5b4e17d_4    conda-forge
boto3                     1.18.26            pyhd8ed1ab_0    conda-forge
botocore                  1.21.26            pyhd8ed1ab_0    conda-forge
bqplot                    0.12.30            pyhd8ed1ab_0    conda-forge
branca                    0.4.2              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py36h68aa20f_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.7.5             haa95532_1
cachetools                4.2.2              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            hb19e0ff_1008    conda-forge
certifi                   2021.5.30        py36haa95532_0
cffi                      1.14.6           py36he58ceb7_0    conda-forge
cfgv                      3.3.0              pyhd8ed1ab_0    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
cftime                    1.5.0            py36h68f0c41_0    conda-forge
chardet                   4.0.0            py36ha15d459_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colour                    0.1.5                      py_0    conda-forge
conda                     4.10.3           py36haa95532_0
conda-package-handling    1.7.3            py36hb5e345e_0    conda-forge
contextvars               2.4                        py_0    conda-forge
cryptography              3.4.7            py36hd0de82c_0    conda-forge
curl                      7.78.0               h789b8ee_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cytoolz                   0.11.0           py36h68aa20f_3    conda-forge
dask                      2021.3.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.3.0           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyh787bdff_2    conda-forge
datacube                  1.8.5                     dev_0    <develop>
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distlib                   0.3.2              pyhd8ed1ab_0    conda-forge
distributed               2021.3.0         py36ha15d459_0    conda-forge
earthengine-api           0.1.279            pyhd8ed1ab_0    conda-forge
editdistance-s            1.0.0            py36he95197e_1    conda-forge
entrypoints               0.3             py36h9f0ad1d_1002    conda-forge
expat                     2.4.1                h39d44d4_0    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
ffmpeg-python             0.2.0                      py_0    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
fiona                     1.8.18           py36h54a71f0_0    conda-forge
folium                    0.12.0             pyhd8ed1ab_1    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
fsspec                    2021.7.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py36ha15d459_3    conda-forge
gdal                      3.1.4           py36h52238aa_15    conda-forge
geeadd                    0.5.4              pyhd8ed1ab_0    conda-forge
geemap                    0.8.18             pyhd8ed1ab_0    conda-forge
geocoder                  1.38.1                     py_1    conda-forge
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_1    conda-forge
geopandas-base            0.9.0              pyhd8ed1ab_1    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.6.0                h8e90983_5    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
git                       2.32.0               haa95532_1
google-api-core           1.31.2             pyhd8ed1ab_0    conda-forge
google-api-python-client  1.12.8             pyhd3deb0d_0    conda-forge
google-auth               2.0.0              pyh6c4a22f_0    conda-forge
google-auth-httplib2      0.1.0              pyhd8ed1ab_0    conda-forge
google-cloud-core         1.6.0              pyhd3eb1b0_0
google-cloud-storage      1.42.0             pyh6c4a22f_0    conda-forge
google-crc32c             1.1.2            py36h0baaa76_0    conda-forge
google-resumable-media    1.3.3              pyh6c4a22f_0    conda-forge
googleapis-common-protos  1.53.0           py36hb0c8f75_0    conda-forge
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
greenlet                  1.1.1            py36he2d232f_0    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
httplib2                  0.19.1             pyhd8ed1ab_0    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
identify                  2.2.13             pyhd8ed1ab_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
idna_ssl                  1.1.0           py36h9f0ad1d_1001    conda-forge
immutables                0.16             py36h68aa20f_0    conda-forge
importlib-metadata        4.6.4            py36ha15d459_0    conda-forge
importlib_metadata        4.6.4                hd8ed1ab_0    conda-forge
importlib_resources       5.2.2              pyhd8ed1ab_0    conda-forge
intel-openmp              2021.3.0          h57928b3_3372    conda-forge
ipyevents                 0.8.2              pyhd8ed1ab_0    conda-forge
ipyfilechooser            0.4.4              pyhd8ed1ab_0    conda-forge
ipykernel                 5.5.5            py36hfacbf0b_0    conda-forge
ipyleaflet                0.14.0             pyhd8ed1ab_1    conda-forge
ipynb-py-convert          0.4.6              pyh9f0ad1d_0    conda-forge
ipython                   7.16.1           py36h7b2dad6_2    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipytree                   0.2.1              pyhd8ed1ab_0    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.17.2           py36ha15d459_1    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_contrib_core      0.3.3                    py36_1    conda-forge
jupyter_contrib_nbextensions 0.5.1            py36h9f0ad1d_1    conda-forge
jupyter_core              4.7.1            py36ha15d459_0    conda-forge
jupyter_highlight_selected_word 0.2.0           py36ha15d459_1002    conda-forge
jupyter_latex_envs        1.4.6           py36ha15d459_1001    conda-forge
jupyter_nbextensions_configurator 0.4.1            py36ha15d459_2    conda-forge
jupyter_server            1.10.2             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
kealib                    1.4.14               h96bfa42_2    conda-forge
kiwisolver                1.3.1            py36he95197e_1    conda-forge
krb5                      1.19.2               hbae68bd_0    conda-forge
lark-parser               0.11.3             pyhd8ed1ab_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      2.2.1                h0e60522_0    conda-forge
libarchive                3.5.1                hb45042f_2    conda-forge
libblas                   3.9.0              11_win64_mkl    conda-forge
libcblas                  3.9.0              11_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcrc32c                 1.1.1                h0e60522_2    conda-forge
libcurl                   7.78.0               h789b8ee_0    conda-forge
libdeflate                1.7                  h8ffe710_5    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.1.4               h966def8_15    conda-forge
libglib                   2.68.4               h1e62bf3_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0              11_win64_mkl    conda-forge
libnetcdf                 4.8.0           nompi_hf689e7d_103    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.3                 hfcc5ef8_0    conda-forge
libprotobuf               3.17.2               h7755175_1    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsolv                   0.7.19               h7755175_5    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1                h6b539a6_4    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libtiff                   4.3.0                h0c97f57_1    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1003    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libxslt                   1.1.33               h65864e5_2    conda-forge
libzip                    1.8.0                hfed4ece_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
logzero                   1.7.0            py36ha15d459_0    conda-forge
lxml                      4.6.3            py36hf8cb5f9_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mamba                     0.15.3           py36h84e1181_0    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py36h68aa20f_0    conda-forge
matplotlib                3.3.4            py36ha15d459_0    conda-forge
matplotlib-base           3.3.4            py36h1abdf75_0    conda-forge
menuinst                  1.4.17           py36ha15d459_1    conda-forge
mistune                   0.8.4           py36h68aa20f_1004    conda-forge
mkl                       2021.3.0           hb70f87d_564    conda-forge
msgpack-python            1.0.2            py36he95197e_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 5.1.0            py36h68aa20f_1    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbclient                  0.5.4              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py36ha15d459_3    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.7           nompi_py36hccab9ff_100    conda-forge
networkx                  2.5                        py_0    conda-forge
nodeenv                   1.6.0              pyhd8ed1ab_0    conda-forge
notebook                  6.3.0            py36ha15d459_0    conda-forge
numpy                     1.19.5           py36h4b40d73_2    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1k               h2bbff1b_0
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.1.5            py36he38d939_0    conda-forge
pandoc                    2.14.1               h8ffe710_0    conda-forge
pandocfilters             1.4.2                    py36_0    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pickleshare               0.7.5           py36h9f0ad1d_1002    conda-forge
pillow                    8.3.1            py36h10c25d6_0    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
poppler                   21.03.0              h9ff6ed8_0    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.3                 h1c22c4f_0    conda-forge
pre-commit                2.14.0           py36ha15d459_0    conda-forge
pre_commit                2.14.0               hd8ed1ab_0    conda-forge
proj                      8.0.0                h1cfcee9_0    conda-forge
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
protobuf                  3.17.2           py36he2d232f_0    conda-forge
psutil                    5.8.0            py36h68aa20f_1    conda-forge
psycopg2                  2.9.1            py36he58ceb7_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycosat                   0.6.3           py36h68aa20f_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrs                     1.0.2                      py_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.0.1            py36h86093ec_1    conda-forge
pyqt                      5.12.3           py36ha15d459_7    conda-forge
pyqt-impl                 5.12.3           py36he2d232f_7    conda-forge
pyqt5-sip                 4.19.18          py36he2d232f_7    conda-forge
pyqtchart                 5.12             py36he2d232f_7    conda-forge
pyqtwebengine             5.12.1           py36he2d232f_7    conda-forge
pyrsistent                0.17.3           py36h68aa20f_2    conda-forge
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1            py36ha15d459_3    conda-forge
python                    3.6.13          h39d44d4_0_cpython    conda-forge
python-box                5.4.0              pyhd8ed1ab_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-mss                6.1.0              pyhd3deb0d_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pywin32                   301              py36h68aa20f_0    conda-forge
pywinpty                  1.1.3            py36hcae0e51_0    conda-forge
pyyaml                    5.4.1            py36h68aa20f_1    conda-forge
pyzmq                     22.2.1           py36h1d5d788_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
rasterio                  1.1.7            py36hc1acebe_0    conda-forge
rasterstats               0.14.0                     py_0
ratelim                   0.1.6                      py_2    conda-forge
reproc                    14.2.1               h8ffe710_0    conda-forge
reproc-cpp                14.2.1               h0e60522_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
requests-unixsocket       0.2.0                      py_0    conda-forge
rsa                       4.7.2              pyh44b312d_0    conda-forge
rtree                     0.9.4            py36h089df06_2    conda-forge
ruamel.yaml               0.17.10          py36h68aa20f_0    conda-forge
ruamel.yaml.clib          0.2.2            py36h68aa20f_2    conda-forge
ruamel_yaml               0.15.80         py36h68aa20f_1004    conda-forge
s3transfer                0.5.0              pyhd8ed1ab_0    conda-forge
scikit-learn              0.24.2           py36h5a51469_1    conda-forge
scipy                     1.5.3            py36h27d303f_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                57.4.0           py36ha15d459_0    conda-forge
shapely                   1.7.1            py36ha9f6fdf_5    conda-forge
simplejson                3.17.3           py36h68aa20f_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.2.0            py36ha15d459_1    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.0.1            py36h9f0ad1d_0    conda-forge
sqlalchemy                1.4.23           py36h68aa20f_0    conda-forge
sqlite                    3.36.0               h8ffe710_0    conda-forge
tbb                       2021.3.0             h2d74725_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
terminado                 0.11.1           py36ha15d459_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.2.0              pyh8a188c0_0    conda-forge
tiledb                    2.2.9                h78dabda_1    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py36h68aa20f_1    conda-forge
tqdm                      4.62.1             pyhd8ed1ab_0    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
traittypes                0.2.1                    py36_0    conda-forge
typing-extensions         3.10.0.0             hd8ed1ab_0    conda-forge
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
uritemplate               3.0.1                      py_0    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
virtualenv                20.4.7           py36ha15d459_0    conda-forge
voila                     0.2.10             pyhd8ed1ab_0    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                    py36_0    conda-forge
websocket-client          0.57.0           py36ha15d459_4    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
whitebox                  1.5.2              pyhd8ed1ab_0    conda-forge
whiteboxgui               0.3.0              pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.5.1            py36ha15d459_4    conda-forge
win_inet_pton             1.1.0            py36ha15d459_2    conda-forge
winpty                    0.4.3                         4    conda-forge
xarray                    0.18.2             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libx11               1.7.2                hcd874cb_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yarl                      1.5.1            py36h779f372_0    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge

**Comment by Kirill888** [comment]
@Jack-ee problems like this often happen when mixing conda and pip packages in one environment. Also python 3.6 is slowly being abandoned by conda packages, so it's no longer the best option, and we should update docs for that. I would recommend bumping your python version to 3.8 or 3.9 and also adding `datacube>=1.8.5` constraint.

There is no need to install datacube from source if you don't need any un-released features (there are none currently as a fresh release was done recently). And all those `pre_commit` things are only needed if you plan to make changes to the code that you would then like to share via github PR.

**Comment by Kirill888** [comment]
and the exact problem you are having is to do with `rasterio` installation being broken, I would NOT recommend attempting to get this environment working unless you **really really** need python 3.6 version and can't move to a more supported newer version.

**Comment by Jack-ee** [comment]
Dear Krirll,

   Thank you for your response. I am a beginner at Python and the stable
version is ok for me. Can you simply list the install command or change
them based on what I have list below?

    git clone https://github.com/opendatacube/datacube-core.git
  conda create -n odc -c conda-forge python=3.8 datacube >=1.8.5

conda activate odccd datacube-corepip install --upgrade -e .pre-commit install

**Comment by Kirill888** [comment]
this should be sufficient:

```
conda create -n odc -c conda-forge "python=3.8" "datacube==1.8.5"
conda activate odc
# Check things work
datacube --version
rio --version
rio --gdal-version
```

**Comment by Jack-ee** [comment]
It's ok now. Thank you.
