### ISSUE TITLE
'eo' metadata type shouldn't use AoS, LoS for the time search field

### ISSUE THREAD

**Issue by v0lat1le** [opendatacube/datacube-core#119]
The indexer code does something like:

``` python
start_time = min(md['acquisition']['aos'], md['extent']['start_dt'])
end_time = max(md['acquisition']['los'], ms['extent']['end_dt'])
```

I suspect it is to support `satellite_telemetry` dataset types, which don't have `extents` field.

Proposed solution:
- only use extents for `eo` metadata types
- define a separate metadata type for `satellite_telemetry`

**Comment by jeremyh** [comment]
I agree with using a separate telemetry metadata type. It will allow us to fix some fields at the same time too: GeoscienceAustralia/eo-datasets#20

**Comment by jeremyh** [comment]
Waiting on the dataset unification work, to avoid duplicate effort.
