### ISSUE TITLE
Aggregate tiles to multi-time storage units 

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#12]
Combine multiple storage units into one by stacking the data along a specified dimension.
- Input storage units **must not** be modified
- Coordinates along the stacked dimension must be sorted in the combined SU
- Fail if the input storage units do not align perfectly; i.e. do not pad data with NDV's

**Comment by v0lat1le** [comment]
Ingester can create timestacked storage units now in batch ingest mode.
The rest is covered by #38
