### ISSUE TITLE
Encourage api users to specify an application name.

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-core#120]
We'd like users to set an application name when using the API.

Currently it's done like this:

``` python
    api = API(application_name='landcover')
```

To make this less cumbersome, we could either 
- rename it to be less verbose  (just `name`?), 
- or make `application_name` the first parameter so that it doesn't need to be specified each time:

``` python
    api = API('landcover')
```

Currently "index" is the first parameter, so the latter will break backwards compatibility with users who are specifying their own index without a name. But I don't know of any users that need to do this yet, and it's a trivial fix if they are, so I think it's worth the trade-off.

**Comment by jeremyh** [comment]
Assigned to Andrew to decide :)

**Comment by andrewdhicks** [comment]
I think the connection that the API represents should remain the first parameter, so that the api instance represents a single "datacube" instance. I'll change `application_name` to `app` with a warning if neither are set.
