### ISSUE TITLE
The workflow of datacube

### ISSUE THREAD

**Issue by leaf0917** [opendatacube/datacube-core#1200]
Can anyone briefly describe the workflow or steps of datacube？
Is the original remote sensing image like landsat8 sence put into the PostgreSQL database or on the local computer？

**Comment by SpacemanPaul** [comment]
Have you read the official documentation at readthedocs?  The "Installation and dataloading" section covers this sort of basic information pretty thoroughly.

https://opendatacube.readthedocs.io/en/latest/ops/overview.html

The postgres database only contains an index.  The actual data is stored in an S3 bucket, or in a file system for a purely local datacube.

Please consider joining the opendatacube Slack: https://opendatacube.slack.com   It is a much more appropriate forum for basic  beginner questions than github issues.
