### ISSUE TITLE
Shapely deprecation warnings

### ISSUE THREAD

**Issue by cbur24** [opendatacube/datacube-core#1206]
Latest release of Shapely is causing Deprecation Warnings when using `dc.load()` . See [here](https://github.com/Toblerity/Shapely/releases/tag/1.8.0) for details

### Actual behaviour

```
/env/lib/python3.8/site-packages/datacube/utils/geometry/_base.py:608: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  return type(geom)([segmentize_shapely(g) for g in geom])
```

### Steps to reproduce the behaviour

```
ds = dc.load(product=product, ...)
```

### Environment information

datacube.__version__: 1.8.6

**Comment by Kirill888** [comment]
this only happens for multi-polygon geometries

https://github.com/opendatacube/datacube-core/blob/3e464c0d528abcad911edb073c55db4d04f8d0c7/datacube/utils/geometry/_base.py#L607-L608

I guess this is Landsat 7 product of some sort?
