### ISSUE TITLE
Support open-ended ranges in dataset search

### ISSUE THREAD

**Issue by MatthewJA** [opendatacube/datacube-core#1217]
### Expected behaviour

`datacube dataset search 'time > 2021-01-01'` should product datasets more recent than 2021-01-01

### Actual behaviour

This isn't supported and an error is shown:

```
time > 2021-01-01
        ^
Expected one of:
  * EQUAL
  * IN
```

**Comment by omad** [comment]
This seems like a nice usability addition.

Eventually people learn to work around it by specifying a really high or really low date as one end of the range, which works, but isn't particularly nice.

The fix implementing this could potentially even work in the same way.
