### ISSUE TITLE
Improve startup of modules on NCI

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-core#122]
Several people have commented that running simple agdc cli commands can take a few seconds on Raijin: for example searches. From the database logs it doesn't appear to be the queries themselves that take up the time.

My suspicion is that it's caused by the startup time of Python itself: it needs to read many python files and their dependencies every time, and lustre isn't designed for large numbers of small file reads.

If true, a simple solution may be to build all Python scripts and dependencies as a single file (eg. [by freezing them](http://docs.python-guide.org/en/latest/shipping/freezing/)), or else investigate if another filesystem is more appropriate for the modules.

**Comment by daleroberts** [comment]
I've had a little play with this and it seems like it is not as nice as hoped on Linux. The python files are packaged into a zip (good!) however all of the .so files are left alongside in the build directory as standalone files and if you are using numpy, scipy, pandas, etc there are a lot of these.

Bundling matplotlib is also a pain, here is supposedly how to bundle it but can't get it to work yet:

https://gist.github.com/joferkington/9214844
