### ISSUE TITLE
SqlAlchemy Warning for database usage

### ISSUE THREAD

**Issue by JackLidge** [opendatacube/datacube-core#1221]
Just installed a new datacube instance on Ubuntu 20.04, most recently released version 1.8.6 and I'm getting warnings about sqlalchemy's caching behaviours, potentially causing performance degradations.

This happened both on running `datacube system init` (init did complete successfully though) and everytime I've run `dc.load()` inside a python terminal.

Full print out here:
`/opt/miniconda3/envs/aws_jhub/lib/python3.9/site-packages/datacube/drivers/postgres/_api.py:564: SAWarning: Class Float8Range will not make use of SQL compilation caching as it does not set the 'inherit_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this object can make use of the cache key generated by the superclass.  Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  return self._connection.execute(select_query)`

This warning is linking into this part of the code:
https://github.com/opendatacube/datacube-core/blob/f19a816f1a8f59041cffe5e53a100c6426e11096/datacube/drivers/postgres/_api.py#L554-L564

The data is loading in fine (albeit slowly but I'm not sure if that is due to a new AWS configuration I'm currently testing). 

Will this warning cause a slow down in loading times or can I just ignore this for the time being? I had a scan around to see if this had already been brought up but couldn't find anything in datacube-core.

**Comment by snowman2** [comment]
Previous errors:
```
/opt/venv/lib/python3.9/site-packages/datacube/drivers/postgres/_api.py:48: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
```
Current error:
```
ImportError: cannot import name 'RangeOperators' from 'sqlalchemy.dialects.postgresql.ranges' (/opt/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/ranges.py)
```

Is there a new datacube release coming soon?
