### ISSUE TITLE
Overly strict assert in `GeoBox` constructor

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#1235]
It's impossible to make a `GeoBox` with arbitrary affine transform.

https://github.com/opendatacube/datacube-core/blob/a01472bfc28e4c5a91b01b330b71fa1a18ce8ef1/datacube/utils/geometry/_base.py#L990

Only some operations of `GeoBox` require affine matrix to be a pure scale and translation. `GeoBox` is also used a container for geo-referencing data, for example in `odc-stac` and this assert is causing issues https://github.com/opendatacube/odc-stac/issues/40.

This assert was added a while back:

https://github.com/opendatacube/datacube-core/commit/ca61414b9004e1026a0aabf3cb20ec300877b1b8

@uchchwhash do you recall why?

But I guess non-axis aligned data sources are rare and so it went unnoticed for a while.

**Comment by SpacemanPaul** [comment]
We were seeing this error in OWS recently.   It appeared to be triggered by somebody getting their lats and longs in the wrong order, so was reasonable in context.

**Comment by Kirill888** [comment]
transposing lon/lat should still produce scale+translation only, just with flipped x instead of flipped y. It came up in deafrica due to incorrect transform recorded in stac (using GDAL order instead of matrix row-major order)

https://github.com/opendatacube/odc-stac/issues/40

**Comment by uchchwhash** [comment]
I think the issue was not with `GeoBox` per se but the xarray coordinate model sort of breaks down for the loaded data. For a skewed `GeoBox` you cannot just assume that the coordinates of the pixels are Cartesian products of the `x` and `y` coordinates.

**Comment by Kirill888** [comment]
thanks Imam, thought so, anyway this should be fixed now
