### ISSUE TITLE
Remove outdated and unused celery integration.

### ISSUE THREAD

**Issue by SpacemanPaul** [opendatacube/datacube-core#1238]
The ODC includes some old celery integration, that:

1. depends on an ancient version of celery with known security issues (and moving to a recent version will require significant code changes on our end.); and
2. has not been used by DEA for many years, and has never been used by DEAfrica.

I'm planning to excise it from the codebase in the near future unless anybody has any objections?  (I feel like if anybody was using it they would have already asked for an upgrade.)

I will add a deprecation warning first.

**Comment by SpacemanPaul** [comment]
Celery executor has been deprecated.

@Kirill888 suggests all other executors should be deprecated as well.

**Comment by omad** [comment]
Celery is no longer a dependency, the executor no longer exists.
