### ISSUE TITLE
API method list_field_values() is too slow

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-core#124]
Reported by @Bis-Bala 

It looks like it's doing a full table scan and calculating the result using python. It will be much faster using a dedicated db query.

**Comment by andrewdhicks** [comment]
Internally it is mis-using `index.datasets.search_summaries()`, which I'm sure wasn't what it was designed for, but it got out some useful data...

**Comment by jeremyh** [comment]
Waiting on the dataset unification work, to avoid duplicate effort.
