### ISSUE TITLE
Change native_geobox handling of eo3 data

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#1243]
1. `native_geobox(ds)` should return "default" grid rather than fail if there are multiple grids in the eo3 dataset
2. should check for eo3 metadata BEFORE checking for grid spec. In the case where product defines grid spec but also uses eo3 metadata, eo3 metadata should be used rather than a complex and error prone computation that is currently used to extract geobox from gridspec and dataset footprint.

**Comment by Ariana-B** [comment]
The implementation of `native_geobox` will change in v2.0 as non-eo3 metadata types will be deprecated.
