### ISSUE TITLE
add datasets to database

### ISSUE THREAD

**Issue by DevenderRaju** [opendatacube/datacube-core#1245]
Dear All,

Can anybody suggest how to add datasets to the datacube database and index, ingest. I have referred to the doc but it is so confusing that working example datasets are not available now.  Anybody help me out pls.

regards,
Raju Devender

**Comment by pindge** [comment]
> Dear All,
> 
> Can anybody suggest how to add datasets to the datacube database and index, ingest. I have referred to the doc but it is so confusing that working example datasets are not available now. Anybody help me out pls.
> 
> regards, Raju Devender

Hey Raju,

I recommend asking this question in opendatacube slack channel https://join.slack.com/t/opendatacube/shared_invite/zt-1bn7hk39i-NOrwIXdtD9b4pfRFphRkJA
