### ISSUE TITLE
Source datasets should be included in NetCDF-embedded metadata

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-core#129]
Optionally the sources could be IDs rather than entire embedded documents, but I assume we do want the source metadata included somewhere for completion.

**Comment by v0lat1le** [comment]
Stacking process currently omits this information

**Comment by v0lat1le** [comment]
Turns out ingestion process omits it also...

**Comment by mpaget** [comment]
I'd suggest that the source datasets should be considered in the larger provenance context, and that the Ingester should capture the source dataset info as part of its provenance updating.

If a list of the source datasets are then desired to be copied into the netcdf metadata then that's fine. Presumably this will go into the 'source' or 'history' global attributes.

**Comment by jeremyh** [comment]
Good points Matt. @omad may know more about what attributes are appopriate in NetCDF CF. To clarify, we do record this information in the Index during ingestion; Greg's only talking about it being omitted from the storage units.
