### ISSUE TITLE
Search API for minimal implementation

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#13]
Search for Storage Units using criteria specified in #11 

Search results must include following Storage Unit information:
- URI
- projection
- dimensions (assume cf conventions + labels)
- variables/measurements
- coordinate extents
- number of measurements along each dimension (coordinate length?)
- DatasetID (provenance tracking)

**Comment by petewa** [comment]
Is this the replacement for gdf.get_descriptor?
If it is, it would be useful to have the following in addition to what you have listed above (if not already included):
- no data value
- data type
- dimension order
- overlap amount (if implemented in the ingester, very useful for certain analytics)
- buffer/chunk size
- index / spatial index information
- resolution information
- storage units that it hits and how, e.g. spatial extents from each.

We need to have a chat about this, perhaps face to face with a whiteboard or over Skype?

This information will help the execution engine work out what gdf.get_data calls to make and when.

**Comment by petewa** [comment]
I have created a page to discuss the Data Access Interface here: http://www.datacube.org.au/wiki/Data_Access_Interface

Here is the style guide for the wiki: http://www.datacube.org.au/wiki/Style_Guide

**Comment by v0lat1le** [comment]
@petewa Indeed it is. Most of the things you mention are already there.

I personally find the wiki unhelpful. There are massive lists of 'requirements' without any context. I need to know who requires those things, and for what purpose.

**Comment by petewa** [comment]
Alex and I designed the existing interface with v2 concepts in mind. If it remains largely unchanged from the gdf trial, it should be ok.

Simon mentioned you changed the nested dicts into an object with gets/sets which is fine.

I'm not sure what you are referring to, most of the array abstracted requirements are quite small.
If you are referring to http://www.datacube.org.au/wiki/V1_API_functionality_review_-_Pass_1
That was the breakdown of v1 api into requirements i.e. what we need to take into account for v2.
The array abstracted requirements is far simpler: http://www.datacube.org.au/wiki/V1_API_functionality_review_-_Pass_2 & http://www.datacube.org.au/wiki/Analysis_Requirements_Matrix.

I personally find the wiki better for discussing design as it is more structured than GitHub, easier to explain concepts and is more accessible for the collaborators. I find GitHub is good to track and discuss bugs but not for design.

Shall we meet up and discuss this, I'll try my best to make it clear for you.

I sincerely hope we can work well together.
