### ISSUE TITLE
Not possible to define a product with default resolution but no default CRS for data loading

### ISSUE THREAD

**Issue by tijmenr** [opendatacube/datacube-core#1301]
In the [dataset type schema](https://github.com/opendatacube/datacube-core/blob/c5486c854dc4fe3e1bef670a5ce01010d0caa938/datacube/model/schema/dataset-type-schema.yaml#L176), both `crs` and `resolution` are specified as mandatory fields for the `load` subsection of a Product definition. So, it is not possible to specify only a default resolution for loading datasets of a product, without having also a default CRS. This seems overly restrictive. While some of the products that we want to store do have a default resolution, they do not have a default CRS (as the CRS depends on the UTM zone of each specific dataset).

Is it possible to enable defining a product with only a default resolution for data loading (i.e. removing the requirement to also specify a CRS)?

**Comment by Kirill888** [comment]
You can pick whatever global CRS for this, say `epsg:3857` or `epsg:6933`, it will only be used as a fallback when output crs is not supplied at load time. The idea here is to provide "load hints" a reasonable default for data loading in the absence of any other configuration from the user, this doesn't have to match metadata of the underlying data.

**Comment by tijmenr** [comment]
The downside of that approach is that users might forget to specify the correct CRS for the data set, so the fallback is used, the data is transformed/warped according to that fallback, and then they only find out several processing steps later that something is wrong with the data.

Taking it a step further, it would be really handy for load operations when, if all the datasets matching the query share the same CRS, that (absent any explicitly specified CRS) that CRS is automatically used in loading the data (and similar for resolution). That would really simplify the load process (for our use case, where we mainly process data in "sentinel-tile" chunks). 

Another thing I'm missing (but maybe I haven't looked deeply enough) is a simple option to skip any transformation/resampling during the load. Currently, data will by default be resampled on load so that the pixel boundaries lie on multiples of the resolution. You can influence that by using the `like`, `align` or `geobox` parameters, but (if you don't know the alignment of the dataset in advance) then loading data without resampling becomes a multi-step process (first retrieving the dataset metadata to determine how it is aligned, and then do the actual load of the data with alignment parameters such that no resampling will be required).

**Comment by Kirill888** [comment]
It looks like code can handle missing CRS in load hints, so it's just a matter of adjusting the schema

https://github.com/opendatacube/datacube-core/blob/c5486c854dc4fe3e1bef670a5ce01010d0caa938/datacube/api/core.py#L839-L847

### Regarding "Native Load"

> Another thing I'm missing (but maybe I haven't looked deeply enough) is a simple option to skip any transformation/resampling during the load. Currently, data will by default be resampled on load so that the pixel boundaries lie on multiples of the resolution. You can influence that by using the like, align or geobox parameters, but (if you don't know the alignment of the dataset in advance) then loading data without resampling becomes a multi-step process (first retrieving the dataset metadata to determine how it is aligned, and then do the actual load of the data with alignment parameters such that no resampling will be required).

it's been a sore point for a while. Before `eo3` we simply didn't capture enough metadata to make it possible. With `eo3` products it should be possible to pick "most appropriate GeoBox" from a collection of Datasets, requested bands and bounding box of a query. It is not possible in general case of course as different datasets can use different grids.

I was going to say that `odc-stac` does it, but actually, after looking at the code again, it only picks most appropriate resolution and CRS and so will introduce pixel shift for center-pixel aligned data like Landsat.

- https://github.com/opendatacube/odc-stac/blob/367bb392c3a507aa255c3d1b534ea68705f52ca9/odc/stac/_mdtools.py#L667-L682

- https://github.com/opendatacube/odc-stac/blob/367bb392c3a507aa255c3d1b534ea68705f52ca9/odc/stac/_mdtools.py#L598-L614


We do have `GeoBox` union/intersection code that will only work when all geoboxes share common grid, so one could do something like:

- Compute intersection of all geoboxes given datasets+bands
- If that succeeds crop resulting GeoBox based on spatial query parameters if any (not sure if have code for that https://github.com/opendatacube/odc-geo/issues/31)
- If that fails pick most common projection and highest resolution and generate pixel edge aligned GeoBox

Also having a load mode that simply fails if reprojection is required at all would be very much appreciated, problem is that `.load` interface area is already so large and unwieldy that we need a better load configuration management system before adding more tweaks like that.

Any of that work we'll have to happen after migrating datacube to [odc-geo](https://github.com/opendatacube/odc-geo) though.
