### ISSUE TITLE
Lineage/source classifier from EO3 metadata not preserved when saving metadata in ODC

### ISSUE THREAD

**Issue by tijmenr** [opendatacube/datacube-core#1303]
### Expected behaviour

`opendatacube/eodatasets3` allows to specify multiple source datasets for a single classifier (see [DatasetPrepare#note_source_datasets()](https://github.com/opendatacube/eo-datasets/blob/develop/eodatasets3/assemble.py#L630) and related methods).

Expected is that `opendatacube/datacube-core` saves these source relations using the specified classifier (in other words: that `opendatacube/eodatasets3` and `opendatacube/datacube-core` are consistent with each other).

### Actual behaviour

When multiple source datasets are given for a classifier, each source dataset is saved with a classifier that is composed of the original classifier suffixed by an index.

E.g. `sources: {'classifier': [ID1, ID2]}`  =>  `sources: {'classifier1': { 'id': ID1 }, 'classifier2': { 'id': ID2 } }`

This happens in [datacube/index/eo3.py#prep_eo3#remap_lineage](https://github.com/opendatacube/datacube-core/blob/develop/datacube/index/eo3.py#L223)

### Steps to reproduce the behaviour

Create an EO3 dataset document using eodatasets3 `DatasetPrepare` / `DatasetAssemble`, and specify multiple source Datasets that share a single classifier name. Then, process the document using datacube-core `Doc2Dataset` (and save it in the ODC index).

### Environment information

* Which ``datacube --version`` are you using? 1.8.7 
* What datacube deployment/enviornment are you running against? PostgreSQL

**Comment by SpacemanPaul** [comment]
This is due to the database schema design (in the postgres index driver).  I'm not sure how this could be addressed without breaking backwards compatibility.  I'll keep it in mind as a I design the schema for the postgis driver though.
