### ISSUE TITLE
Programatically datacube initialization in virtual environment

### ISSUE THREAD

**Issue by lhcorralo** [opendatacube/datacube-core#1307]
### Expected behaviour

It should be possible to initialize the datacube programatically

### Actual behaviour

It is possible to run something like this from within python:

```
subprocess.check_call(["python", "-m", "datacube.scripts.cli_app", "-v", "system", "init"])
```

However, it fails when running a python interpreter outside the path (like running a conva environment in WSL2), as the called python interpreter is a different one (for example, /usr/bin/python, checked running ```subprocess.check_call(["which", "python"])```

### Steps to reproduce the behaviour

- Prepare a postgresql empty database using docker compose
- Install Pycharm Professional edition
- install WSL2
- Install conda in WSL2
- create a conda environment
- In pycharm, create an WSL2 project liking to the python interpreter in the conda environment (not to the default python interpreter)
- Execute a code like this

```
def init_database(hostname: str, port: Optional[int] = None, username: Optional[str] = None,
                  password: Optional[str] = None, database: str = "datacube"):

    # The initialization may be done using the following environment variables
    # DB_HOSTNAME, DB_USERNAME, DB_PASSWORD and DB_DATABASE
    if port is not None:
        os.environ["DB_HOSTNAME"] = f"{hostname}:{port}"
    else:
        os.environ["DB_HOSTNAME"] = hostname
    if username:
        os.environ["DB_USERNAME"] = username
    if password:
        os.environ["DB_PASSWORD"] = password
    os.environ["DB_DATABASE"] = database

    # Execute the command
    from datacube.scripts.system import database_init
    subprocess.check_call(["which", "python"])
    subprocess.check_call(["python", "-m", "datacube.scripts.cli_app", "-v", "system", "init"])

init_database(...)
```

### Environment information

datacube=1.8.7

### Additional comments

I have seen that there are functions for initializing the database in https://github.com/opendatacube/datacube-core/blob/629fc6475618024455ed0377c13ca78333179169/datacube/scripts/system.py#L48, but I do not know what argument pass to index

And thanks for your great project!

**Comment by SpacemanPaul** [comment]
The click test harness would at least let you avoid generating a subprocess:

```
from click.testing import CliRunner
import datacube.scripts.cli_app

runner = CliRunner()

result = runner.invoke(datacube.scripts.cli_app.cli, ["initdb"])

assert result.exit_code == 0
```

**Comment by lhcorralo** [comment]
Hi! I am testing the workaround and exit_code is 2, so it is not a direct workaround (it is a pity, it looked very promising...). I will investigate a little bit more the click test harness way :)

Thanks!

**Comment by SpacemanPaul** [comment]
Have you tried:

```
from datacube import Datacube

# Do not validate connection as db schema doesn't exist yet
dc = Datacube(validate_connection=False)

# Initialise db schema

dc.index.init_db()
```

**Comment by lhcorralo** [comment]
Hi!

Sorry for the (huge) delay.

I stopped trying to use this approach. Instead, as my project is relying in docker-compose, I created a specific image for the datacube initialization (something like postgresql image using the /docker-entrypoint-initdb.d directory for checking what scripts and sql queries to run during startup).

Thank you!
