### ISSUE TITLE
Updating of docker image for GH automated testing is problematic.

### ISSUE THREAD

**Issue by SpacemanPaul** [opendatacube/datacube-core#1311]
### Expected behaviour

Create a PR that modifies the python environment (e.g. `setup.py`, `docker/constraints.txt`) and makes code changes that depend on that environment.  Automated tests run on github using a docker image built from the changes in the PR.   Tests pass.

### Actual behaviour

Automated tests run on github using the docker image last pushed to dockerhub which does not include the environment changes made in the PR.  Tests fail.  

### Steps to reproduce the behaviour

Create a PR that adds a new library dependency, and imports from that library.

**Comment by Ariana-B** [comment]
This was (hopefully) fixed in #1406

**Comment by omad** [comment]
Lets close this, and we can always re-open or create a new issue if it pops up again.
