### ISSUE TITLE
opendatacube readthedoc not rendering code-block:: yaml

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-core#1326]
https://opendatacube.readthedocs.io/en/latest/installation/product-definitions.html

rst file contains `.. code-block:: yaml ` https://raw.githubusercontent.com/opendatacube/datacube-core/develop/docs/installation/product-definitions.rst it is not rendered

**Comment by omad** [comment]
The problem isn't a space or no space between `.. code-block::` and `yaml`, it's the lack of an empty line between `.. code-block:: yaml` and the YAML content.
