### ISSUE TITLE
Readthedocs points to old documentation

### ISSUE THREAD

**Issue by andrewdhicks** [opendatacube/datacube-core#133]
Our readthedocs page at http://agdc-v2.readthedocs.io/ currently defaults to the version called `latest`, which is out of date and looks to be based off the `master` branch on github.  The default version on github is the `develop` branch.
The readthedocs project page at https://readthedocs.org/projects/agdc-v2/ lists 4 versions of the documentation.

**Comment by jeremyh** [comment]
We probably want it to always point to the latest stable version (which is presumably the most recently built module).

A simple solution may be to start merging tagged releases into (the currently-defunct) master again. Or, if possible, configure readthedocs to use the most recent tag.

**Comment by andrewdhicks** [comment]
bump
