### ISSUE TITLE
Error on empty bands

### ISSUE THREAD

**Issue by PaulMousset** [opendatacube/datacube-core#134]
Hello,

I tried to ingest Sentinel-2 data, but when some bands are empty (file band doesn't exist), the ingest doesn't work.

```
File "\envs\datacube\lib\site-packages\datacube-0.0.0+80c8e57-py35.egg\
datacube\storage\storage.py", line 328, in __init__
    dataset_measurement_descriptor = dataset.metadata.measurements_dict[measurement_id]
KeyError: '10'
```

(Because '10' band doesn't exist)

How can I skip these empty bands ?

**Comment by v0lat1le** [comment]
Could you attach your storage type document (unless you're using one from docs/config_samples) and the dataset metadata document (agdc-metadata.yaml). I think there's a mismatch between the two and that's causing the issue.

**Comment by PaulMousset** [comment]
Thank you for your reply.
I used [Sentinel-2 Configuration](https://github.com/data-cube/agdc-v2/blob/develop/docs/config_samples/sentinel_2/s2_msi_l1c_mapping.yaml) provided on Github.
I used [s2prepare.py](https://github.com/data-cube/agdc-v2/blob/develop/utils/s2prepare.py) to prepare this file :  [agdc-metadata.yaml](https://github.com/data-cube/agdc-v2/files/269839/agdc-metadata.txt). In this dataset, for the document at line 353, only '3' and '9' bands are available. This document raises an error.

I tried with other files (Sentinel-2) or an other Dataset (Landsat_5). If a band is missing (but declared in the configuration), the same error is raised.

**Comment by v0lat1le** [comment]
Haven't seen that before... Do you know if that's expected for Sentinel 2 data not to have some band files? Is it possible that your archive is corrupted?

Missing bands are not really supported atm. One option is to remove the dataset with missing bands from `agdc-metadata.yaml` (delete lines  352-384 inclusive).

Depending on how frequent that is I'll see how to resolve the issue

**Comment by PaulMousset** [comment]
I downloaded the archive from the data provider  Peps. I already checked that the archive isn't corrupted. I will check to see if this scenario happens often.
Thanks.
