### ISSUE TITLE
No recursion on windows dataset path for multiple data ingest

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#135]
Explore options for adding a '-r' switch or similar for recursive function to enable multiple file ingest from dos commandline

**Comment by v0lat1le** [comment]
Unix shell glob-ing with *, doesn't work on windows. This makes it hard to reference multiple dataset metadata files for index/ingest.
Building in that functionality might be an option (parse the \* in the app). 
Also cygwin.
