### ISSUE TITLE
update unification ingester command line functions to maintain consistency

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#137]
New ingestion function looks like:
**agdc** -v index--match-rules <matchrules> <inputscene>

Maintain consistency with other datacube configuration and search commands:

i.e. **datacube index**, datacube ingest, datacube config, datacube search

**Comment by v0lat1le** [comment]
Few options for implementing this:
- [Click Plugins Package](https://github.com/click-contrib/click-plugins) (used by rasterio)
- [Click Command Collection](http://click.pocoo.org/5/commands/#merging-multi-commands)

I think click-plugins looks more promising...

**Comment by v0lat1le** [comment]
We could also do fancy things like hiding/showing commands based on user privileges/roles.

**Comment by simonaoliver** [comment]
list of command line functions being elaborated here: 
https://docs.google.com/document/d/1lTFUnd3vC4GqcIoJEGMeXytklY4KG5GYaLCD4RpmZgw/edit

**Comment by v0lat1le** [comment]
**Current Structure**
- datacube
  - index - index datasets
  - ingest - run ingest application: tile/reproject
- datacube-config
  - check - check db connection / schema
  - create - create user
  - database init - init database
  - grant - grant user role
  - type(product) add - add dataset type
  - users - list users
- datacube-search
  - datasets
  - units

**Option A**
- datacube
  - database
    - init
    - check
  - user
    - list
    - add
    - grant
  - dataset
    - add
  - product
    - add
    - count (datasets per product / product_type / range )
    - list (datasets per product / product_type / range )

**Option B**
- datacube
  - add
    - dataset
    - product
    - user
  - list
    - dataset
    - product
    - user
  - check
    - database
  - init
    - database

**Comment by omad** [comment]
A - better for extending

**Comment by jeremyh** [comment]
Agreed. Group by noun, especially since they won't always have the same set of operations.
