### ISSUE TITLE
Incompatibilities with xarray > 2022.03

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#1373]
### Expected behaviour
ODC should work with current version of `xarray`. In `setup.py` there's an exclusion of `2022.6.0`, but I don't think that's sufficient. It'd be worth digging up the commit/PR that made that change.

### Actual behaviour

Tests are failing.

```
FAILED tests/api/test_grid_workflow.py::test_gridworkflow_with_time_depth - AssertionError
FAILED tests/api/test_virtual.py::test_aggregate - ValueError: time already exists as coordinate or variable name.
```

### Steps to reproduce the behaviour

`pytest tests/`

### Environment information

* Which ``datacube --version`` are you using?

 `develop` branch at `af59377327c363b9c52b55000b4024a0b3fbaa8b`

* What datacube deployment/enviornment are you running against?

  - Mambaforge
  - conda-forge 
  - Python 3.10

**Comment by Ariana-B** [comment]
Seems like this is an issue with xarray, as raised by Emma: https://github.com/pydata/xarray/issues/6836
