### ISSUE TITLE
Shapely 2.0.0 compatibility

### ISSUE THREAD

**Issue by Ariana-B** [opendatacube/datacube-core#1378]
The Shapely 2.0.0 release on Dec 13 2022 included [several backwards incompatible API changes](https://shapely.readthedocs.io/en/latest/release/2.x.html#breaking-api-changes).

Currently, we've pinned the version < 2.0.0 in the docker constraints and datacube-explorer, but the code should be updated to make it compatible with the new release.

Related: #1376

**Comment by SpacemanPaul** [comment]
What are `odc-geo` doing?  We may be able to backport fixes from there.  I'm hoping to migrate datacube-core to use odc-geo some time relatively soon anyway.

**Comment by Kirill888** [comment]
@SpacemanPaul 

mostly it's using `.geom_type` instead of deprecated `.type`

https://github.com/opendatacube/odc-geo/pull/81/files

**Comment by Ariana-B** [comment]
@SpacemanPaul 
Beyond the deprecated `.type`, the biggest issue is with certain attributes being deprecated or having a different return type, causing some tests to fail as seen in #1386.

**Comment by Kirill888** [comment]
`odc-geo` have addressed various shapely deprecations a while back:

https://github.com/opendatacube/odc-geo/commit/7d0382eca0e32723616b5120cf7663b4ef531ab3
https://github.com/opendatacube/odc-geo/commit/e3d8a4944c01e8fdf59e3f18dc71be2b5e4f0986

**Comment by omad** [comment]
Fixed by #1389
