### ISSUE TITLE
Storage Access API - retrieve data from minimal build

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#14]
Use results returned by the Search API(#13) and provide:
- construct analysis array elements from storage units
- labeled data (with xray)
- lazy loading to facilitate out of core processing (with dask for example)
- group data by inter-operability
  - same projection
  - same coordinate extents
  - same 'resolution'

**Comment by petewa** [comment]
Is this the replacement for gdf.get_data?

If so, get_data needs to be have to take as input:
    - depending on how the data is stored in the storage units, a target projection may need to be specified in the get_data call to return the data in the appropriate projection.
    - grouping by time. e.g. seasons, month, day etc like in the gdf trial get_data code with grouping_function
    - dimension ranges or polygons or dimension masks
    - target resolution.
    - multi-scale version of get_data (not for v2 but should think about this, it's something I will be incorporating later on)

Arrays needs to be wrapped as a xray dataarray and metadata set as appropriate.

Reads by multi-process reads not multi-threaded reads, useful for scaling up on single node multi-core reads.

We need to have a chat about this, perhaps face to face with a whiteboard or over Skype?

**Comment by petewa** [comment]
I have created a page to discuss the Data Access Interface here: http://www.datacube.org.au/wiki/Data_Access_Interface

Here is the style guide for the wiki: http://www.datacube.org.au/wiki/Style_Guide

**Comment by v0lat1le** [comment]
@petewa Yes, it is the replacement for get_data. Look at the band_stats_integrated.py in the examples directory.
