### ISSUE TITLE
sql error getting max_client_conn

### ISSUE THREAD

**Issue by Bis-Bala** [opendatacube/datacube-core#141]
I do get time to time this error.  " conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: (psycopg2.OperationalError) ERROR:  no more connections allowed (max_client_conn)". This error is generated out of PBS jobs. The port was 6432.

[cont2_run.e6516578.txt](https://github.com/data-cube/agdc-v2/files/285522/cont2_run.e6516578.txt)

**Comment by Bis-Bala** [comment]
Getting query_wait_timeout

```
2016-06-05 15:11:54,181 INFO EpochStatisticsTask(x=-20, y=-27, acq_min=2013-01-01, acq_max=2013-12-31, season=Season.CALENDAR_YEAR, sat  File "/short/v10/bxb547/agdcv2_venv/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (psycopg2.DatabaseError) query_wait_timeout
server closed the connection  File "/home/547/bxb547/ga-repository/agdcV2/datacube/api/_api.py", line 582, in get_dataset_by_cell
    for su in self.index.storage.search(**query):
  File "/home/547/bxb547/ga-repository/agdcV2/datacube/index/_storage.py", line 178, in <genexpr>
    ) f7/agdcv2_venv/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (psycopg2.DatabaseError) query_wait_timeout
server closed the connection unexpectedly
```

**Comment by omad** [comment]
Can you please include a bit more information about what the query was, so that someone else can try to reproduce it.

**Comment by Bis-Bala** [comment]
I was trying to run concurrently through 200 nodes and using pbsdsh. The last API called by the application was  get_dataset_by_cell . The arguments are normal (ex. product nbar, 2013, LS8). The problem persists for  two minutes yesterday at 15:09-15:11)  and hence not processed few cells.

**Comment by jeremyh** [comment]
@Bis-Bala: I've increased the limits for pgbouncer: they're higher than your node count now.

We should also be able to drop your query load once you've moved to the new schema (unification): I see a lot of your queries taking 7+ seconds to run.

Please reopen if you still see issues.
