### ISSUE TITLE
rasterio 0.36:  'rasterio._io.RasterReader' object has no attribute 'crs_wkt'

### ISSUE THREAD

**Issue by cronosnull** [opendatacube/datacube-core#144]
I just perform a clean install of the datacube in ubuntu 16.04 with anaconda using python 2.7. 

There are compatibility issues with rasterio 0.36. A workaround is to install version 0.35.1 using pip: 

``` bash
pip install rasterio==0.35.1
```

A temporal fix could be change requirements in setup.py from `rasterio>0.30` to `rasterio==0.35.1`

**Comment by v0lat1le** [comment]
Was that in one of utils/*.py scripts?

Could you attach the whole error dump, please

**Comment by cronosnull** [comment]
Yes, it was in  utils/usgslsprepare.py
The error log dump is at  [error.txt](https://github.com/data-cube/agdc-v2/files/323671/error.txt)

I confirm that it works with the changes made in ceee66983f2b13b134878166d390effbf02b7d30
