### ISSUE TITLE
datacube load is failing as memory error

### ISSUE THREAD

**Issue by Bis-Bala** [opendatacube/datacube-core#145]
This query is failing after running more than five minutes on VDI even though datasets  are for only three years.
dc=datacube.Datacube(app='test')
bbb=dc.load(product='ls5_nbar_albers', x=(149, 149.9), y=(-35.9, -35), time=((2000,01,01,0), (2015,12,31,23,59,59)), group_by='solar_day')

**Comment by v0lat1le** [comment]
You are requesting ~32GB of memory...
Also make sure you are using agdc-py2-prod/1.1.3 at least - there are some performance improvemets
