### ISSUE TITLE
BUG: Scale in rectilinear reproject produces different results (without dask)

### ISSUE THREAD

**Issue by snowman2** [opendatacube/datacube-core#1456]
Related:
- #1448
- #1450

### Expected behaviour

reproject behaves similar to GDAL defaults

### Actual behaviour

The behavior has slight differences with GDAL defaults

### Steps to reproduce the behaviour
- Original CRS = EPSG:32615
- Original Transform = Affine(5.0, 0.0, 451560.0, 0.0, -5.0, 4640690.0)

```python
import datacube
import rioxarray
import xarray
from rasterio.enum import Resampling

dc = datacube.Datacube()
old = xarray.open_dataset("old_demsm.nc", decode_coords="all")  # loaded with datacube==1.8.12 
new = dc.load( # datacube==1.8.13 
    product=...,
    measurements=["demsm"],
    geom=geom,
    output_crs="EPSG:6933",
    resolution=[-10, 10],
    resampling="cubic_spline",
).squeeze()
```

![image](https://github.com/opendatacube/datacube-core/assets/8699967/28737a10-f813-4b6d-a374-22801875ef36)

```python
orignal_rasters = dc.find_datasets(
    product=...,
    measurements=["demsm"],
    geom=geom,
)
original_demsm = rioxarray.open_rasterio(
    orignal_rasters[0].raster_path,
    masked=True,
).rio.reproject_match(
    match_data_array=new["demsm"],
    resampling=Resampling.cubic_spline,
).rio.clip(
    [geom],
    crs="EPSG:4326",
).squeeze()
```
![image](https://github.com/opendatacube/datacube-core/assets/8699967/c9430328-60d4-414e-a17e-2a2c17035bc0)

### Environment information

* Which ``datacube --version`` are you using? 1.8.13

cc @alfredoahds

**Comment by snowman2** [comment]
[link](https://github.com/OSGeo/gdal/blob/5daa9c4eed6fa0c541f1f121a1b86ca5e11028b9/alg/gdalwarpkernel.cpp#L1037-L1062) to the code where GDAL calculates scales.

```
dfXScale = static_cast<double>(nDstXSize) / (nSrcXSize - dfSrcXExtraSize);
dfYScale = static_cast<double>(nDstYSize) / (nSrcYSize - dfSrcYExtraSize);
```
`scale2` is inverted from the original scale here: https://github.com/opendatacube/datacube-core/blob/c8795e3144fcf6cdabed23eecc9e8cb04626bcef/datacube/utils/geometry/tools.py#L650

If the `XSCALE` and `YSCALE` here:
https://github.com/opendatacube/datacube-core/blob/c8795e3144fcf6cdabed23eecc9e8cb04626bcef/datacube/storage/_read.py#L193

are adjusted to undo the invert and also remove the rounding to an integer:
```python
XSCALE=1 / rr.scale2[0],
YSCALE=1 / rr.scale2[1]
```
Then the difference is much smaller:
![image](https://github.com/opendatacube/datacube-core/assets/8699967/65e3be0c-17c3-428a-9d0e-31f51d490e5c)

**Comment by snowman2** [comment]
Question: Any issues disabling scaling for non-dask flows? https://github.com/corteva/datacube-core/commit/ddd56e39f934f8f4e83281432e1f6a1e9892f3bd

Edit: Seems GDAL is not always correct? https://github.com/OSGeo/gdal/issues/7750#issuecomment-1564114854

**Comment by snowman2** [comment]
If I add `dask_chunks={"time": 1, "x": 30, "y": 30},`

Without `XSCALE` | `YSCALE` set (`v1.18.12`):
![image](https://github.com/opendatacube/datacube-core/assets/8699967/48a2a9bb-5192-407b-aa34-2d4fa1df873f)

With` XSCALE=1 / rr.scale2[0]` & `YSCALE=1 / rr.scale2[1]`:

![image](https://github.com/opendatacube/datacube-core/assets/8699967/1f3f2736-e8be-48b3-af1f-90ba2244f386)

With `XSCALE=1` & `YSCALE=1`:
![image](https://github.com/opendatacube/datacube-core/assets/8699967/36ce31c7-a68c-457b-b9fd-d813e7abd851)

Current `master` | `v1.18.13`
![image](https://github.com/opendatacube/datacube-core/assets/8699967/910412dd-bde2-4c8b-8fe5-4cc291157812)

**Comment by Kirill888** [comment]
I think this is scale "direction error". `scale2=(2,2)` happens when down-sampling, whereas GDAL expects `XSCALE=0.5, YSCALE=0.5` for that use case.

Problem is in GDAL, problem is more obvious when `max(W,H)/min(W,H)` of the output image is high and when there is significant rotation component. I would not limit this to Dask only case. But obviously direction of scale needs to be 

1. Documented in datacube
2. Passed in correctly to GDAL

Honestly I disagree with the whole approach taken by GDAL here, it's attempting to be helpful by essentially injecting nearest neighbour shrink/expand step instead of sampling directly from source pixels. Which in itself is questionable approach, especially that this not really documented as far as I can tell. This is then made much worse by using approximation for computation of required shrink/expand factors that breaks down badly for tall and thin or short and wide destination images.

@SpacemanPaul I guess we'll need a new release after fixing this one.

**Comment by Kirill888** [comment]
My personal preference here would be to disable this shrink/expand step inside GDAL by always passing in `XSCALE=1, YSCALE=1` regardless of the scale change estimate.

**Comment by SpacemanPaul** [comment]
Interesting, but honestly not unsurprising - the existing scale stuff was a bit of hack based on the metadata we had to hand (which was gathered for a completely different purpose.)

I'll try to do a bit more testing before release this time so we've got a better handle on what works best.

**Comment by SpacemanPaul** [comment]
> My personal preference here would be to disable this shrink/expand step inside GDAL by always passing in `XSCALE=1, YSCALE=1` regardless of the scale change estimate.

The more I think about it, the more I tend to agree with you.  I think I need to look at the GDAL code and try to get a better understanding of what the undocumented XSCALE and YSCALE parameters actually do.

**Comment by Kirill888** [comment]
quote from issue linked above:

> They define respectively the ratio of the output width / input width and output height / input height, which is evaluated for each warping chunk, and such ratio is used to modulate the radius of the resampling kernel (when the ratio is for example 0.5, the effective radius of the bilinear resampling will go from its nominal 1 value to 2) .

I believe this is equivalent to inserting average based integer shrink of the source imagery followed by bilinear sampling from that. I tried looking at the code, but there are a lot of specialized implementations based on things like float vs int, sampling algorithm, whether it's a shrink or expand, nodata or not, opencl or cpu...

I'd start here: https://github.com/OSGeo/gdal/blob/master/alg/gdalwarpkernel.cpp#L1265

**Comment by SpacemanPaul** [comment]
Ahhh that makes sense.  Does indeed sound like `XSCALE=1, YSCALE=1` is the safest approach for us (for now).  (and definitely less wrong than what I did in #1450)

**Comment by SpacemanPaul** [comment]
@snowman2 - see PR #1457 (or develop branch if is merged by the time you're out of bed in your part of the world).

Please test this attempted fix with your example data and let me know how it goes.  If there don't seem to be any further issues I'll try and do another release later this week (or early next).

**Comment by snowman2** [comment]
I tested `XSCALE=1` and `YSCALE=1` and you can see the results in the previous post here https://github.com/opendatacube/datacube-core/issues/1456#issuecomment-1585037755. It differs from using the GDAL defaults similar to the issue seen with the current passed in scale. However, due to the discussion about doubts about the approach GDAL is taking, I am not sure if GDAL is the standard to compare against. But, we don't have anything better at the moment.

To ask for further insights from the GDAL core developers, thoughts about asking in the mailing list https://lists.osgeo.org/mailman/listinfo/gdal-dev? Or would it be better served as a GDAL issue?

**Comment by SpacemanPaul** [comment]
The GDAL defaults yield obvious visible distortion when the loaded image has a highly non-square aspect ratio (as per #1448)
