### ISSUE TITLE
issue in find_less_mature when indexing datasets without region_code

### ISSUE THREAD

**Issue by emmaai** [opendatacube/datacube-core#1490]
### Expected behaviour
Need a better solution of identifying the same dataset with less maturity, hard matching `region_code` is less ideal.

### Actual behaviour
couldn't index any dataset without `region_code`, e.g., summary products and tide data (https://data.dea.ga.gov.au/?prefix=hltc/v2.0.0/)

code here does some "hard-coded" match to the `region_code` without checking the item existence.
 https://github.com/opendatacube/datacube-core/blob/24b046e737ea94bc088ee0f0566e839370152be9/datacube/index/abstract.py#L928-L930

### Steps to reproduce the behaviour
run `s3-to-dc` (`odc-apps-dc-tools==0.2.13`) to index the products mentioned above  
```
  File "/tmp/odc-tools/apps/dc_tools/odc/apps/dc_tools/s3_to_dc.py", line 75, in dump_to_odc
    index_update_dataset(
  File "/tmp/odc-tools/apps/dc_tools/odc/apps/dc_tools/utils.py", line 262, in index_update_dataset
    dc.index.datasets.add(ds, archive_less_mature=archive_less_mature)
  File "/env/lib/python3.10/site-packages/datacube/index/postgres/_datasets.py", line 195, in add
    self.archive_less_mature(dataset, archive_less_mature)
  File "/env/lib/python3.10/site-packages/datacube/index/abstract.py", line 908, in archive_less_mature
    less_mature = self.find_less_mature(ds, delta)
  File "/env/lib/python3.10/site-packages/datacube/index/abstract.py", line 929, in find_less_mature
    region_code=ds.metadata.region_code,
  File "/env/lib/python3.10/site-packages/datacube/utils/documents.py", line 498, in __getattr__
    raise AttributeError(
AttributeError: Unknown field 'region_code'. Expected one of ['id', 'label', 'format', 'sources', 'creation_dt', 'grid_spatial', 'measurements', 'creation_time', 'format', 'label', 'lat', 'lon', 'time', 'platform', 'instrument', 'product_type']
```

### Environment information

* 1.8.15
* any

**Comment by SpacemanPaul** [comment]
Do we generate summary products with non-final maturity?  (i.e. is the solution to simply not use "archive-less-mature" behaviour for these products?)

If the user could specify a custom metadata fields to identify matching datasets, what field(s) would be used for these products?

**Comment by Ariana-B** [comment]
It doesn't seem to me like these products even have a `dataset_maturity` value? The error thrown could be improved, though.

**Comment by emmaai** [comment]
It sounds that archiving is optional and supposed to on certain datasets with both dataset_maturity and region_code in the metadata. Can we check if the datasets satisfy the conditions then? If not, no archiving.
