### ISSUE TITLE
Installation environment issues

### ISSUE THREAD

**Issue by WildEchoes** [opendatacube/datacube-core#1499]
# Problem
Thanks for your work! I first came into contact with the ODC library and encountered some doubts when configuring the Conda environment. 
> * Can I use the datacube normally with only *conda install - c conda forge datacube==1.8.12* ?
（I don't install postgresql, because I don't need it immediately）
> * If I don‘t use *pip install --upgrade -e .* ，it can work？I'm not sure if it's necessary and I have a problem when I use this command.

One more thing, If I want to learn how to use odc where I can learn form? Thanks!

**Comment by SpacemanPaul** [comment]
It sounds like you might be better off looking at odc-geo - if you are only working from a handful of local data files it is easier to install, doesn't require a database and and is probably a better way for a beginner to learn.

Datacube-core is more for managing or indexing large collections of data. You can't do much with the datacube-core without a database.

I find on most systems it is easiest to simply install from PyPI with pip (preferably in a virtual environment):

For help and guidance I recommend the [ODC Community Slack](http://slack.opendatacube.org/),

Another good way to get started and learn would be to obtain an account on a free platform with an ODC environment already provided for you, like Digital Earth Australia Sandbox or Digital Earth Africa Sandbox.  Both programs have extensive examples and documentation to get you up to speed.

**Comment by WildEchoes** [comment]
> It sounds like you might be better off looking at odc-geo - if you are only working from a handful of local data files it is easier to install, doesn't require a database and and is probably a better way for a beginner to learn.
> 
> Datacube-core is more for managing or indexing large collections of data. You can't do much with the datacube-core without a database.
> 
> I find on most systems it is easiest to simply install from PyPI with pip (preferably in a virtual environment):
> 
> For help and guidance I recommend the [ODC Community Slack](http://slack.opendatacube.org/),
> 
> Another good way to get started and learn would be to obtain an account on a free platform with an ODC environment already provided for you, like Digital Earth Australia Sandbox or Digital Earth Africa Sandbox. Both programs have extensive examples and documentation to get you up to speed.

Thanks！
