### ISSUE TITLE
command line tools in V2? 

### ISSUE THREAD

**Issue by juan-guerschman** [opendatacube/datacube-core#153]
The previous version of the Datacube API had a few convenient command tools, http://geoscienceaustralia.github.io/agdc/api/0.1.0/html/api_tools.html 

Is there anything similar to that in this new version? I can't find any of that in http://agdc-v2.readthedocs.io/en/develop/ops/tools.html 

Thanks

**Comment by omad** [comment]
Hi Juan,

At the moment we haven't built any equivalent command line tools yet. Is there anything in particular that would be useful for you, or things that are more important?

Cheers

**Comment by juan-guerschman** [comment]
I'm a NPP (Non-Python “People”)  :) 

A Retrieve Area of Interest tool (like in the planned http://geoscienceaustralia.github.io/agdc/api/0.1.0/html/api_tools.html#retrieve-area-of-interest ) would be very handy. 

Juan

**Comment by juan-guerschman** [comment]
In addition: ideally with an option of providing coordinates for UL, LR or a vector (kml for example). Outputs to TIF or netcdf, options to mask with PQA. Output NBAR bands or FC, NDVIs, etc. 

cheers

Juan

**Comment by omad** [comment]
Thanks for the feedback. No promises for when we'll have a tool like that ready, but it's really helpful for planning to know whats sorts of capabilities people will use!

**Comment by juan-guerschman** [comment]
Thanks. 
For exploratory data analysis I still use my own tools in other languages and/or downloading stuff locally. That's why a subsetting tool would be very useful. 

Juan

**Comment by omad** [comment]
While these sorts of tools are potentially still useful, there's no immediate plans to build an extract data tool, so I'm going to close this for now until the urgency rises.
