### ISSUE TITLE
Low contrast text on 1.9 migration page when using dark mode

### ISSUE THREAD

**Issue by pjonsson** [opendatacube/datacube-core#1576]
Here's a screenshot of the readthedocspage for the 1.9 migration when using dark mode in Chromium on Linux:
![image](https://github.com/opendatacube/datacube-core/assets/2082449/15e9a960-20ce-4f18-9b18-8ed40b84b3a3)
I don't think it is OS/browser issue, I get the same look in Firefox on Windows.

Here's a screenshot of the same section when using light mode as comparison:
![image](https://github.com/opendatacube/datacube-core/assets/2082449/1652efe3-1e4c-4299-a768-329405cec593)

**Comment by SpacemanPaul** [comment]
I had noticed this.  It's not just the migration notes, the same is true for all pages on readthedocs.
