### ISSUE TITLE
Ingesting terra satellite ASTER GDEM information. Requesting more clarity in the docs.

### ISSUE THREAD

**Issue by conicRelief** [opendatacube/datacube-core#159]
There is no neatly packaged XML file for ASTER GDEM V2 data as there is for USGS landsat scenes. 

There are only two .tiff files. 
This is giving me issues when trying to create a meta-data file for ingestion since the meta-data is not as easy to extrapolate from our data.  

I would like to know what fields are absolutely necessary for meta-data files so that I may code up a lightweight ASTER_GDEM_PREPARE .py  (Bonus points for telling me what fields auto-match work with)  
  
I hope to hear from you soon! 
  
Until then:  
ERROR Unable to create Dataset for file: //home/dc_user/Desktop/aster/meta_data.yaml: No matches found for unidentified

**Comment by v0lat1le** [comment]
http://agdc-v2.readthedocs.io/en/stable/ops/config.html details required and optional fields for `Product` (alse see examples in docs/config_samples/dataset_types) and `Dataset`.

`dataset add --auto-match` will associate a dataset with a particular product when fields inside `metadata` section of the product definition form a subset of top-level fields in the dataset definition

**Comment by conicRelief** [comment]
You're right. Thanks for linking me to that part of the documentation.  
Can you give me hints about about how to make 'aster gdem' data cooperate with 'landsat imagery'?  

How exactly are these two data-sets combined?  I see a `storage` field defined in ingestion-configs. My thoughts are as long as this aligns with my landsat7 ingestion config's `storage` field the two data-sets will be aligned and reference-able on the same coordinate system when being loaded into their high level `x-arrays` representation. Can you confirm this?

**Comment by v0lat1le** [comment]
Yep, if the two of them have the same ingester `storage` config then their xarray representation will be in the same coordinate system and pixel-aligned by default.

Alternatively [`Datacube.load`](http://agdc-v2.readthedocs.io/en/stable/dev/generate/datacube.Datacube.load.html#datacube-datacube-load) can be configured to reproject/resample on the fly by using `output_crs`, `resolution` and `align` parameters
