### ISSUE TITLE
V2 alternative to band_statistics_arg25.py workflow

### ISSUE THREAD

**Issue by lpinner** [opendatacube/datacube-core#160]
Earlier this year I generated some summary stats rasters using the old API workflow [band_statistics_arg25.py](https://github.com/GeoscienceAustralia/agdc/blob/develop/api/source/main/python/datacube/api/workflow/band_statistics_arg25.py).

Something like:
```
band_statistics_arg25.py --x-min $LON --x-max $LON --y-min $LAT --y-max $LAT            \
  --output-directory $OUTPUTDIR                                                         \
  --season CALENDAR_YEAR --satellite LS5 LS7                                            \
  --dataset-type NDVI --band NDVI                                                       \
  --statistic COUNT_OBSERVED MIN MAX MEAN STANDARD_DEVIATION PERCENTILE_5 PERCENTILE_95 \
  --chunk-size-x $XWIN--chunk-size-y $YWIN                                              \
  --acq-min 2005 --acq-max 2009                                                         \
  --mask-pqa-apply  --mask-pqa-mask PQ_MASK_CLEAR
```
Is there an equivalent command line tool or functionality in the new API?

**Comment by omad** [comment]
Hi Luke,

I'm working on an equivalent tool called [datacube-stats](https://github.com/GeoscienceAustralia/agdc_statistics) but it's not quite ready to run yet. I'm working on it this week and will post an update here when it's ready to go.

Cheers
Damien

**Comment by omad** [comment]
The `datacube-stats` tool has reached a somewhat useful stage, and is now being deployed into the NCI datacube environment. I'm still working on documentation, but I think this issue can be closed. For now at least.
