### ISSUE TITLE
www.opendatacube.org domain failing

### ISSUE THREAD

**Issue by JessicaS11** [opendatacube/datacube-core#1605]
### Expected behaviour

https://www.opendatacube.org/ loads the website. The Xarray-tutorial CI picked this up as a link failure and I went to find the correct link only to find the domain wasn't working.

### Actual behaviour

<img width="1224" alt="image" src="https://github.com/opendatacube/datacube-core/assets/11756442/e4a42a9a-7499-45a3-a4f8-0307a6527f63">

### Steps to reproduce the behaviour
Go to the URL: https://www.opendatacube.org/

**Comment by SpacemanPaul** [comment]
The website is working again.

The website is currently being actively rewritten/redesigned and while we try to keep outages to a minimum, we cannot rule out this happening again for short periods.

**Comment by JessicaS11** [comment]
> The website is currently being actively rewritten/redesigned 

Awesome! And no worries. Just wanted to make sure it was expected versus not known.
