### ISSUE TITLE
Ingesting Sentinel 1 data

### ISSUE THREAD

**Issue by fcastel** [opendatacube/datacube-core#164]
Hi,

I noticed that new config files were released, so I tried to use them to ingest Sentinel1 data.

I  have an error when running the preparation script :

> Traceback (most recent call last):
>   File "/opt/agdc-v2/utils/s1prepare.py", line 190, in <module>
>     main()
>   File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/opt/agdc-v2/utils/s1prepare.py", line 181, in main
>     documents = prepare_datasets(path)
>   File "/opt/agdc-v2/utils/s1prepare.py", line 161, in prepare_datasets
>     ), s1a_path.stem).groupdict()
> AttributeError: 'NoneType' object has no attribute 'groupdict'

Looking at the code, I don't really understand what the  script is supposed to do there :

```
# INPUT path is parsed for elements - below hardcoded for testing
def prepare_datasets(s1a_path):
    print(s1a_path)
    fields = re.match(
        (
            r"(?P<platform>SENTINEL_1A)"
        ), s1a_path.stem).groupdict()

    # timedelta(days=int(fields["julianday"]))
    # , 'creation_dt': ((crazy_parse(fields["productyear"]+'0101T00:00:00'))+timedelta(days=int(fields["julianday"])))})
    fields.update({'level': 'gamma0', 'type': 'intensity'})
    s1a = prep_dataset(fields, s1a_path)
    return (s1a, s1a_path)
```

The comment let me think that the code is not finalized... is the script able to work though?

Best regards,
Fabien

**Comment by simonaoliver** [comment]
Hi Fabien,
S1prepare.py is very preliminary and was quickly put together to demonstrate tiling of a S1 mosaic product from the Gamma software package in geotiff format. With a little work, the code could be be adapted to work with outputs from https://github.com/benjimin/s1prepro (S1 gamma0 creation code using SNAP). We can put this work in the TODO list of tasks if you'd like to see it happen or I'm happy to work with you to build the support. The intention of the utils example was to provide developers with some sample code for how to build preparation code for your own product - in the future we intend to further simplify the data preparation process.

example of S1prepare.py target dir contents:
/SENTINEL_1A
agdc-metadata.yaml (written by S1prepare.py)
mosaic_tasmania_S1_Gamma0_VH.tif 
mosaic_tasmania_S1_Gamma0_VV.tif

example execution:
$ python s1prepare.py /SENTINEL_1A
2016-12-08 06:23:19,388 INFO Processing /SENTINEL_1A
2016-12-08 06:23:19,407 INFO Writing /SENTINEL_1A/agdc-metadata.yaml

example gdalinfo dump of input geotiff:
gdalinfo /SENTINEL_1A/mosaic_tasmania_S1_Gamma0_VV.tif 
Driver: GTiff/GeoTIFF
Files: /SENTINEL_1A/mosaic_tasmania_S1_Gamma0_VV.tif
Size is 33585, 37584
Coordinate System is:
PROJCS["WGS 84 / UTM zone 55S",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",147],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",10000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","32755"]]
Origin = (220199.500000000000000,5630020.500000000000000)
Pixel Size = (12.500000000000000,-12.500000000000000)
Metadata:
  AREA_OR_POINT=Point
  TIFFTAG_DATETIME=2016:02:15 16:42:22
  TIFFTAG_SOFTWARE=Created with GAMMA Software www.gamma-rs.ch
Image Structure Metadata:
  COMPRESSION=PACKBITS
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  220199.500, 5630020.500) (143d44'56.86"E, 39d26' 2.23"S)
Lower Left  (  220199.500, 5160220.500) (143d31'48.15"E, 43d39'30.03"S)
Upper Right (  640012.000, 5630020.500) (148d37'39.56"E, 39d28' 4.87"S)
Lower Right (  640012.000, 5160220.500) (148d44'15.15"E, 43d41'52.19"S)
Center      (  430105.750, 5395120.500) (146d 9'40.96"E, 41d35'33.21"S)
Band 1 Block=33585x1 Type=Float32, ColorInterp=Gray
  NoData Value=0

**Comment by omad** [comment]
Not touched recently, closing until it comes up again.

**Comment by clausmichele** [comment]
I am also trying to ingest processed Sentinel 1 data, which are in the format `file.dat file.aux.xml file.hdr` . I found two old scripts for Sentinel 1: `prep_s1a.py s1prepare.py`
What are the file formats and folder structure they expect? Is there any example?
