### ISSUE TITLE
S2 new format name

### ISSUE THREAD

**Issue by AudreyCh** [opendatacube/datacube-core#165]
Hello, 
I'm trying to "s2prepare.py" new format L1C sentinel2 products but I get an error saying : 

[Errno 2] No such file or directory: '/hpss/S2A_MSIL1C_20161207T055222_N0204_R048_T44VPJ_20161207T055222.SAFE/S2A_MSIL1C_20161207T055222_N0204_R048_T44VPJ_20161207T055222.xml'

I tried to trick the script by renaming the xml file but then:

INFO No datasets discovered. Bye!

Is there a way to prepare the new L1C products? 
Thanks in advance.
Best regards

**Comment by simonaoliver** [comment]
@AudreyCh - I can provide a usage example below to demonstrate the code operating on a single new S2L1C granule (windows OS). Possibly you have a 'path to target dataset' issue? f you could post the full example execution I may be able to replicate your issue at this end:

python s2prepare.py C:\tmp\S2A_OPER_PRD_MSIL1C_PDMC_20161126T043212_R030_V20161126T000222_20161126T000222.SAFE\

2016-12-15 13:16:56,415 INFO Processing C:\tmp\S2A_OPER_PRD_MSIL1C_PDMC_20161126
T043212_R030_V20161126T000222_20161126T000222.SAFE\S2A_OPER_MTD_SAFL1C_PDMC_2016
1126T043212_R030_V20161126T000222_20161126T000222.xml

2016-12-15 13:16:57,492 INFO Writing 1 dataset(s) into C:\tmp\S2A_OPER_PRD_MSIL1
C_PDMC_20161126T043212_R030_V20161126T000222_20161126T000222.SAFE\agdc-metadata.
yaml

**Comment by AudreyCh** [comment]
Thanks for this quick answer.

The example you gave me use the old naming convention of the S2-L1C products, ESA is using a new naming format, like this one (I use PEPS platform to retrieve S2 products):

https://peps.cnes.fr/rocket/#/collections/S2/a0036908-3daa-5a45-be61-d91e0460c414

With this new name, the command line (linux OS):

python s2prepare.py /hpss/S2A_MSIL1C_20161207T055222_N0204_R048_T44VNH_20161207T055222.SAFE. 

does not work anymore even if I rename the MTD_MSIL1C.xml file into S2A_MSIL1C_20161207T055222_N0204_R048_T44VNH_20161207T055222.xml.

For now ESA still provides products with old and new names (so does PEPS) but shortly the old naming convention will disappear and I guess the name is not the only thing changing.

Thanks again.

Best regards

**Comment by simonaoliver** [comment]
@AudreyCh - please take a look at [https://github.com/data-cube/agdc-v2/blob/develop/utils/s2peps_prepare.py](url). Hopefully that works for now - we'll consolidate the S2 prepare scripts at some point (only tested on windows for now).
