### ISSUE TITLE
Geometry pickles

### ISSUE THREAD

**Issue by benjimin** [opendatacube/datacube-core#166]
````python
>>> x = datacube.utils.geometry.point(4,5, crs=datacube.utils.geometry.CRS('EPSG:4326'))
>>> s = pickle.loads(pickle.dumps(x))
ERROR 1: Empty geometries cannot be constructed
````
Shapely was [designed](https://sgillies.net/2007/06/11/shapely-geometries-for-python.html) to avoid this issue.

Use case: a distributed job where the spatial bounds for each task have already been pre-computed (as a side-effect of determining which tasks are needed), e.g. WOfS.

Observed in 1.1.17 py3 module.

**Comment by v0lat1le** [comment]
Fixed by @omad in 4fc2758d68d5d446ba524cd850a85c026432e56a
