### ISSUE TITLE
Error on upgrading to the latest version of the database

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-core#1666]
### Expected behaviour

`datacube -v system init` will migrate the DB to the 1.9.0 beta release.

### Actual behaviour

Exception is raised:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "d" of relation "dataset" does not exist
LINE 2:                 SET d.uri_scheme=(
                            ^
[SQL: UPDATE odc.dataset d
                SET d.uri_scheme=(
                    SELECT l.uri_scheme FROM odc.location l
                    WHERE l.dataset_ref=d.id AND archived IS NULL
                    ORDER BY added LIMIT 1),
                d.uri_body=(
                    SELECT l.uri_body FROM odc.location l
                    WHERE l.dataset_ref=d.id AND archived IS NULL
                    ORDER BY added LIMIT 1)]
(Background on this error at: https://sqlalche.me/e/20/f405)
time="2024-11-26T01:26:09 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```

### Steps to reproduce the behaviour

Have DB on previous version (hard to know which, as they're all hash releases) and upgrade to the new one.

`Running upgrade 610f32dca3cb -> d27eed82e1f6`

### Environment information

* Using `Open Data Cube core, version 1.9.0rc12.dev18+g009a9f2a`
* Running against a fairly fresh DB

**Comment by omad** [comment]
Is this migrating from one 1.9 pre-release to a 1.9 beta release? I would have expected that to work.

Is there a documented/supported process to migrate from 1.8 database to a 1.9 database?

**Comment by SpacemanPaul** [comment]
Migrating from a 1.8 postgis database to a 1.9 postgis database is probably a lost cause.  (Sorry, we called it "experimental" in 1.8 for a reason).

Postgis databases generated by 1.9 rc releases SHOULD be handled by `datacube system init` - but honestly we are still getting used to the art of writing Alembic migrations and some corner cases may not be handled smoothly.


Migrating from a postgres database to a postgis database is handled with:

```
datacube -E new system init
datacube -E new system clone old
```

Where the `old` environment points to the old postgres database and `new` to the new postgis database.

**Comment by SpacemanPaul** [comment]
(oh, and which postgres version are using?  shouldn't matter, but might)
