### ISSUE TITLE
Huge number of deprecation warnings when running tests in 1.9

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#1674]
### Expected behaviour
Not print out all of the deprecation warnings when running tests in 1.9.

They should either be explicitly checked for in the tests (painful!)

Or we should be able to, and default to, ignoring them for our own datacube code when running the tests.

**Comment by SpacemanPaul** [comment]
I think it's just where we are testing deprecating code, but yeah it is kinda annoying.

**Comment by Kirill888** [comment]
unit tests that test deprecated code on purpose should have warnings capture, other tests should not so that we can ensure that no "not-deprecated" code uses "deprecated code".
