### ISSUE TITLE
Time range strings behave differently between datacube and xarray

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-core#184]
When specifying a time range in a datacube:
`dc.load(..., time=('2003-01', '2003-03'))`
is interpreted to be 
_2003-01-01 00:00:00 to 2003-03-01 00:00:00_
i.e. values rounds down

vs

In xarray:
`data.sel(time=slice('2003-01', '2003-02'))`
is interpreted to be:
_2003-01-01 00:00:00 to 2003-03-31 23:59:59.999_
i.e. values round out

Ideally they would behave the same.

**Comment by andrewdhicks** [comment]
This should reuse logic added by https://github.com/opendatacube/datacube-core/pull/226/files
