### ISSUE TITLE
Masking-making functions should return a DataArray

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-core#185]
When making a mask from a `xarray.Dataset` object, the `make_mask()` function looks for data variables (such as `pixelquality` in ls5_pq_albers) that have `flags_definition` set.

It then returns a `Dataset` with a new `DataArray` variable of the same name, of `bool` type.

Unless we are expecting multiple variables in a PQ product to share mask names (eg `some_pq_product.oldpixelquality` and `some_pq_product.newpixelquality` to both have `cloud` defined) we should be able to combine them and return a single boolen DataArray not wrapped in a DataSet.

**Comment by omad** [comment]
Also see #345

**Comment by walsh-andrew** [comment]
This is not fixed, as the improvement is an old one and it may well break other things that have been added since then.
