### ISSUE TITLE
Allow result paging, sorting and limits in index API

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-core#191]
Will be useful for:
Dashboard (and CLI) dataset lists:
Queries such as "five most recent datasets of this type"
Paging through longer query results
Queries such as "first dataset after..."
Often want to sample a few datasets of a type easily (without selecting all.)

**Comment by jeremyh** [comment]
Paging probably isn't worth doing as it wont be efficient to do correctly at the moment. Sorting is optional. But limits alone would be extremely useful.

**Comment by omad** [comment]
The most requested part of this is **limit** support, which was added a while ago.
Closing this.

If sorting and filtering is still insufficient we should create a new issue.
