### ISSUE TITLE
Design API for derived datasets query

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-core#192]
You can currently return a list of source datasets, but not derived datasets.
As suggested by Simon Oliver, it would be useful for displaying provenance trees.

**Comment by omad** [comment]
I'm not sure about the internal API, but this is possible from the command line with `datacube dataset show --show-derived <dataset-id>` as well as in https://github.com/opendatacube/dea-dashboard to display provenance trees.
