### ISSUE TITLE
Helpful schema error messages

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-core#197]
If the datacube refuses to insert something into the database (because of schema checks), it would be nice if it helped the user fix this problem (especially since it is difficult anyway for a user to determine upfront exactly which metadata fields are necessary/permissible/appropriate). For example, in which node is a given property missing?
~~~~
   dc.index.products.add(product) 
  File "/g/data1/u46/users/brl654/datacube/agdc-v2/datacube/index/_datasets.py", line 216, in add
    DatasetType.validate(type_.definition)
  File "/g/data1/u46/users/brl654/datacube/agdc-v2/datacube/utils/__init__.py", line 622, in validate
    return validate_document(document, cls.schema, schema.parent)
  File "/g/data1/u46/users/brl654/datacube/agdc-v2/datacube/utils/__init__.py", line 300, in validate_document
    raise InvalidDocException(e.message)
datacube.utils.InvalidDocException: 'nodata' is a required property
~~~~

**Comment by omad** [comment]
This is still something that should be improved, but I'm going to close this for now until it becomes a higher priority, or we have some easily re-producable cases.
