### ISSUE TITLE
Support authenticated opendap datasources

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-core#198]
Some desired datasources from Opendap endpoints require OpenD
http://gpm1.gesdisc.eosdis.nasa.gov/opendap/GPM_L3/GPM_3IMERGHHE.03/2015/contents.html
NASA website has instruction to authenticate with wget cookiestore:
http://disc.sci.gsfc.nasa.gov/recipes/?q=recipes/How-to-Download-Data-Files-from-HTTP-Service-with-wget
NetCDF can support the authentication with libcurl style cookie files:
https://www.unidata.ucar.edu/software/netcdf/docs/auth.html
PyDap has an implementation for the cookie-based authentication:
http://www.pydap.org/client.html#cas

**Comment by omad** [comment]
This is *old* an there's no current work on this. Closing.
