### ISSUE TITLE
incompatibility with Postgres 9.6

### ISSUE THREAD

**Issue by DrewDevereux** [opendatacube/datacube-core#207]
If using Postgres 9.6 (the latest release) then
`datacube system init`
fails with error
`unrecognized role option "nocreateuser"`

The release notes for Postgres 9.6 include:
> Remove the long-deprecated CREATEUSER/NOCREATEUSER options from CREATE ROLE and allied commands (Tom Lane)
> CREATEUSER actually meant SUPERUSER, for ancient backwards-compatibility reasons. This has been a constant source of confusion for people who (reasonably) expect it to mean CREATEROLE. It has been deprecated for ten years now, so fix the problem by removing it.

**Comment by jeremyh** [comment]
Thanks Drew — this was fixed in 012f5a727bf9fcbfe535ae6da86ba85c8b74b715 but hasn't made it into a release yet.  We're hoping to have a release made sometime this week.
