### ISSUE TITLE
NCI VDI setup

### ISSUE THREAD

**Issue by JulianOG** [opendatacube/datacube-core#214]
Hi,
I'm interested in exploring your data cube on VDI.
I went through the NCI setup user guid   
http://datacube-core.readthedocs.io/en/latest/user/nci_usage.html

and got the following error message.

[jgo599@vdi-n27 ~]$ module use /g/data/v10/public/modules/modulefiles/
[jgo599@vdi-n27 ~]$ module load agdc-py3-prod
Unable to connect to the database (jgo599@130.56.244.227:6432).

Attempting to create a new user for jgo599...

Error creating user account for 'jgo599'. 
>>  ERROR: syntax error at or near "Grady" LINE 1: ...599', 'T9EHzE5j4PmPO3d4GHYz704w5AdEqWW5', 'Julian O'Grady'); ^
Error: database connection check failed!
  see log above for more details

Is it the apostrophe?

**Comment by benjimin** [comment]
Could be! Looks a bug in the module on the NCI rather than opendatacube-core itself. (Previously was using a shell script to build SQL statements..)

@JulianOG could you please try changing the command to `module load agdc-py3-prod/1.3.0` to see if that works?

**Comment by JulianOG** [comment]
[jgo599@vdi-n27 ~]$ module load agdc-py3-prod/1.3.0
Traceback (most recent call last):
  File "/g/data/v10/public/modules/agdc-py3-prod/1.3.0/datacube-ensure-user.py", line 165, in <module>
    main()
  File "/g/data/v10/public/modules/agdc-py3-env/20170327/envs/agdc/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/g/data/v10/public/modules/agdc-py3-env/20170327/envs/agdc/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/g/data/v10/public/modules/agdc-py3-env/20170327/envs/agdc/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/data/v10/public/modules/agdc-py3-env/20170327/envs/agdc/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/g/data/v10/public/modules/agdc-py3-prod/1.3.0/datacube-ensure-user.py", line 111, in main
    creds = find_credentials(pgpass, OLD_DB_HOST, username)
  File "/g/data/v10/public/modules/agdc-py3-prod/1.3.0/datacube-ensure-user.py", line 61, in find_credentials
    with pgpass.open() as src:
  File "/g/data/v10/public/modules/agdc-py3-env/20170327/envs/agdc/lib/python3.5/pathlib.py", line 1151, in open
    opener=self._opener)
  File "/g/data/v10/public/modules/agdc-py3-env/20170327/envs/agdc/lib/python3.5/pathlib.py", line 1005, in _opener
    return self._accessor.open(self, flags, mode)
  File "/g/data/v10/public/modules/agdc-py3-env/20170327/envs/agdc/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/599/jgo599/.pgpass'
Error: database connection check failed!
  see log above for more details
[jgo599@vdi-n27 ~]$

**Comment by jeremyh** [comment]
Hi Julian -- you've caught us in the middle of an environment migration :)

Can you retry the original? it should hopefully succeed this time: `module load agdc-py3-prod`

**Comment by benjimin** [comment]
Thanks @JulianOG for that test of the new environment module, you found a different bug and @jeremyh has made some fixes to both versions. Please try `module load agdc-py3-prod` again!

**Comment by JulianOG** [comment]
[jgo599@vdi-n27 ~]$ module load agdc-py3-prod
Unable to connect to the database (jgo599@130.56.244.227:6432).

Attempting to create a new user for jgo599...

Error creating user account for 'jgo599'. 
>>  ERROR: syntax error at or near ":" LINE 1: select create_readonly_agdc_user(:'db_user', :'generated_key... ^
Error: database connection check failed!
  see log above for more details
[jgo599@vdi-n27 ~]$

**Comment by jeremyh** [comment]
Hey @JulianOG, Is that error from eariler, or did you rerun it after Ben's recent comment? That was an issue earlier because the default NCI psql module is too old to support the syntax: I've added a newer one to the dependencies. 

These scripts are frustrating to test as we can't drop our own privileges on NCI.

**Comment by jeremyh** [comment]
My test user recreation is working with the old module:

```
15:45:46 [lpgs@raijin1:~]$ module load agdc-py3-prod
Unable to connect to the database (lpgs@130.56.244.227:6432).

Attempting to create a new user for lpgs...

Success! Credentials written to ~/.pgpass.
15:45:57 [lpgs@raijin1:~]$
```

**Comment by JulianOG** [comment]
It was run after Ben's recent comment. And I get the same error just now.

**Comment by JulianOG** [comment]
Here is a warning with **module load agdc-py3-prod/1.3.0**

[jgo599@vdi-n27 ~]$ module load agdc-py3-prod/1.3.0
Warning: PYTHONPATH is /g/data/v10/public/modules/agdc-py3/1.2.2/lib/python3.5/site-packages
Try unloading all python modules if you experience any issues.
Attempting to create a new user for jgo599...

An account for 'jgo599' already exists in the Data Cube Database, but 
we were unable to connect to it. This can happen if you have used the Data 
Cube from raijin, and are now trying to access from VDI, or vice-versa.

To fix this problem, please copy your ~/.pgpass file from the system you 
initially used to access the Data Cube, onto the current system.
Please contact a datacube administrator to help resolve user account creation.

**Comment by jeremyh** [comment]
Arg, sorry about the hassle. Can you copy the output from `module list`?

And is this a fresh bash environment, or the same as the previous load?

**Comment by jeremyh** [comment]
Ah, I think there's some conflicts happening between multiple partially-loaded modules

**Comment by JulianOG** [comment]
[jgo599@vdi-n27 ~]$ module list
Currently Loaded Modulefiles:
  1) pbs                      5) /agdc-py3-prod/1.2.2
  2) /agdc-py3-env/20170221   6) /agdc-py3-env/20170327
  3) /agdc-py3/1.2.2          7) /agdc-py3/1.3.0
  4) /psql/9.6.2              8) /agdc-py3-prod/1.3.0

new bash terminal.

**Comment by jeremyh** [comment]
It has a mixture of old and new modules loaded. Can you try restarting your bash session completely and then trying the original module again?

Then paste the outputs of `module list` and `psql --version`

**Comment by JulianOG** [comment]
When I first open a terminal... 
[jgo599@vdi-n27 ~]$ module list and psql --version
VERSION=3.2.10
DATE=2012-12-21

AUTOLOADPATH=undef
BASEPREFIX="/opt"
BEGINENV=99
CACHE_AVAIL=undef
DEF_COLLATE_BY_NUMBER=undef
DOT_EXT=""
EVAL_ALIAS=1
HAS_BOURNE_FUNCS=1
HAS_BOURNE_ALIAS=1
HAS_TCLXLIBS=1
HAS_X11LIBS=1
LMSPLIT_SIZE=undef
MODULEPATH="/opt/Modules/modulefiles"
MODULES_INIT_DIR="/opt/Modules/3.2.10/init"
PREFIX="/opt/Modules/3.2.10"
TCL_VERSION="8.5"
TCL_PATCH_LEVEL="8.5.7"
TMP_DIR="/tmp"
USE_FREE=undef
VERSION_MAGIC=1
VERSIONPATH="/opt/Modules/versions"
WANTS_VERSIONING=1
WITH_DEBUG_INFO=undef

then when I load the **module load agdc-py3-prod** I get the same psql --version.

[jgo599@vdi-n27 ~]$ module load agdc-py3-prod/1.3.0
Warning: PYTHONPATH is /g/data/v10/public/modules/agdc-py3/1.2.2/lib/python3.5/site-packages
Try unloading all python modules if you experience any issues.
Migrating you to the new database server.
Unable to connect to the Data Cube database, please contact an administrator for help.
[jgo599@vdi-n27 ~]$ module list and psql --version
VERSION=3.2.10
DATE=2012-12-21

AUTOLOADPATH=undef
BASEPREFIX="/opt"
BEGINENV=99
CACHE_AVAIL=undef
DEF_COLLATE_BY_NUMBER=undef
DOT_EXT=""
EVAL_ALIAS=1
HAS_BOURNE_FUNCS=1
HAS_BOURNE_ALIAS=1
HAS_TCLXLIBS=1
HAS_X11LIBS=1
LMSPLIT_SIZE=undef
MODULEPATH="/opt/Modules/modulefiles"
MODULES_INIT_DIR="/opt/Modules/3.2.10/init"
PREFIX="/opt/Modules/3.2.10"
TCL_VERSION="8.5"
TCL_PATCH_LEVEL="8.5.7"
TMP_DIR="/tmp"
USE_FREE=undef
VERSION_MAGIC=1
VERSIONPATH="/opt/Modules/versions"
WANTS_VERSIONING=1
WITH_DEBUG_INFO=undef

[jgo599@vdi-n27 ~]$ module list
Currently Loaded Modulefiles:
  1) pbs                      5) /agdc-py3-prod/1.2.2
  2) /agdc-py3-env/20170221   6) /agdc-py3-env/20170327
  3) /agdc-py3/1.2.2          7) /agdc-py3/1.3.0
  4) /psql/9.6.2              8) /agdc-py3-prod/1.3.0

**Comment by JulianOG** [comment]
sorry, I missread you message. 

[jgo599@vdi-n27 ~]$ module list
Currently Loaded Modulefiles:
  1) pbs
[jgo599@vdi-n27 ~]$  psql --version
psql (PostgreSQL) 8.4.20
contains support for command-line editing
[jgo599@vdi-n27 ~]$

**Comment by JulianOG** [comment]
[jgo599@vdi-n27 ~]$ module list
Currently Loaded Modulefiles:

pbs
[jgo599@vdi-n27 ~]$ psql --version
psql (PostgreSQL) 8.4.20
contains support for command-line editing
[jgo599@vdi-n27 ~]$

**Comment by JulianOG** [comment]
[jgo599@vdi-n27 ~]$ module list
Currently Loaded Modulefiles:

pbs
[jgo599@vdi-n27 ~]$ psql --version
psql (PostgreSQL) 8.4.20
contains support for command-line editing
[jgo599@vdi-n27 ~]$

**Comment by benjimin** [comment]
@JulianOG, is that in a fresh terminal, before you load the agdc module? What output do you get from `module load agdc-py3-prod`, then `module list`, then `psql --version`?

**Comment by JulianOG** [comment]
Yes, a fresh terminal.

[jgo599@vdi-n27 ~]$ module list
Currently Loaded Modulefiles:
  /1) pbs
[jgo599@vdi-n27 ~]$  psql --version
psql (PostgreSQL) 8.4.20
contains support for command-line editing
[jgo599@vdi-n27 ~]$ module load agdc-py3-prod
ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'agdc-py3-prod'
[jgo599@vdi-n27 ~]$ module use /g/data/v10/public/modules/modulefiles/
[jgo599@vdi-n27 ~]$ module load agdc-py3-prod
Migrating you to the new database server.
Unable to connect to the Data Cube database, please contact an administrator for help.
[jgo599@vdi-n27 ~]$ module list
Currently Loaded Modulefiles:
 /1) pbs                                     /3) /agdc-py3/1.3.0
 /2) /agdc-py3-env/20170327  /4) /agdc-py3-prod/1.3.0
[jgo599@vdi-n27 ~]$ psql --version
psql (PostgreSQL) 8.4.20
contains support for command-line editing
[jgo599@vdi-n27 ~]$

**Comment by benjimin** [comment]
Hi @JulianOG. We think the module scripts are working now, but we'll need to refresh your `~/.pgpass` file. Can you either remove (or rename) that file entirely, if you're not using it for anything else, or just drop/comment all lines that begin with 130.56.244.*227* and 130.56.244.*105*. Afterward, again try loading the module from a fresh terminal.

e.g. `mv ~/.pgpass ~/.pgpass.backup`

**Comment by JulianOG** [comment]
it worked :) 

[jgo599@vdi-n27 ~]$ module use /g/data/v10/public/modules/modulefiles/
[jgo599@vdi-n27 ~]$ module load agdc-py3-prod
Attempting to create a new user for jgo599...
Created new database account.
User credentials written to ~/.pgpass. Connection test: passed.
[jgo599@vdi-n27 ~]$
