### ISSUE TITLE
Develop application code for comparing/matching data cube metadata with CMI metadata

### ISSUE THREAD

**Issue by jkool** [opendatacube/datacube-core#215]
Intended to match data cube metadata against what was recorded as expected in the CMI.  The CMI outputs a set of JSON nodes containing CMI entries made by scientisits/authors.  For more detail on CMI, contact Johnathan Kool.

**Comment by benjimin** [comment]
Is the code available?

**Comment by jkool** [comment]
We're looking to get code developed to provide this function.  Happy to move this issue out of core if a better alternative presents itself.

**Comment by mpaget** [comment]
This issue relates only to the AGDC. It is a good example of the need for us to be clear when there is a separation of interests between opendatacube and AGDC. @jkool - you're not wrong to add it here as there is nowhere else to add it. All - what would your preferred method be for AGDC-only issues? Labels? Projects? Feel free to suggest, or we can bump it up if there are pros and cons between options.

**Comment by GypsyBojangles** [comment]
This is issue is now tracked within our internal JIRA as it is unrelated to ODC.
