### ISSUE TITLE
Fix for Ingestion of Existing Dataset Type Error

### ISSUE THREAD

**Issue by alfredo-ama** [opendatacube/datacube-core#218]
In the ingestion script, the index is checked for an existing type and updates it if there are no 'bad' changes. The output type is set using [index.products.update](https://github.com/opendatacube/datacube-core/blob/develop/datacube/index/_datasets.py#L365) which has no return value, causing a NoneType error. Should the update function return a ProductResource or should the output type be updated in place without reassigning a value to output_type?

[Line, for quick reference](https://github.com/opendatacube/datacube-core/commit/f4b8b5dd2856530115afd8a3351b30c74344eb8d#diff-2a62009b43559ee82754f45d180200c6R153)

**Comment by alfredo-ama** [comment]
A return may also be required [here](https://github.com/opendatacube/datacube-core/blob/develop/datacube/index/_datasets.py#L388).

**Comment by andrewdhicks** [comment]
Yes it it! (I'm blaming my jet lag...)
Leaving this bug open until I write tests for the `update` and `can_update` functions

**Comment by omad** [comment]
Closing old issue. Seems to be fixed, but tests may or may not ever be written.
