### ISSUE TITLE
Issue with the ingestion of UInt16 and UInt32 dtypes

### ISSUE THREAD

**Issue by alfredo-ama** [opendatacube/datacube-core#222]
When trying to load an ingested dataset with a dtype of either UInt16 or UInt32, the following error comes up:
![dc_load](https://cloud.githubusercontent.com/assets/22379995/25388543/22046c32-299c-11e7-94a7-47c3260c88d5.PNG)

It seems that the NetCDF files generated during ingestion are trying to be read in as datatype 8/9, which correspond to the unsupported CInt types - [seen here](https://github.com/mapbox/rasterio/blob/master/rasterio/dtypes.py#L26). The dtype is set to UInt16 in both the product definition and the ingestion configuration file, and running gdalinfo on the .nc file reports it as a UInt16:
![gdalinfo](https://cloud.githubusercontent.com/assets/22379995/25388658/6d3f5856-299c-11e7-94b9-b075fff2ffdc.PNG)

It seems to be a rasterio issue, as trying to open the dataset results in the following warning:
![rasterio_open](https://cloud.githubusercontent.com/assets/22379995/25388717/8e30205e-299c-11e7-8a35-55ae372531df.PNG)

The error in the DC occurs because it won't cast the default Float32 type back to whatever is set in the ingestion configuration file. Is this a rasterio issue or does this have something to do with how the DC writes the netCDF files? I can load in the source dataset (GeoTiff) as UInt16/32 without any issues.

**Comment by sixy6e** [comment]
All to do with the NetCDF-CF specification. The spec doesn't allow for unsigned types, except for uint8. GeoTiff doesn't have that same limitation.

**Comment by alfredo-ama** [comment]
I see - thanks for the information.

**Comment by jeremyh** [comment]
We may want to improve the error message, though, to make it more obvious why it is failing.
