### ISSUE TITLE
Allow usage of `scale_factor` and `add_offset` variable attributes

### ISSUE THREAD

**Issue by Bis-Bala** [opendatacube/datacube-core#227]
To have geo median products, it is required to scale to float32/64 in the surface reflectance values before passing onto geomedian algorithm. Needs to update variable attributes in the netcdf file so that users can rescale geo median values.

The flexibility will enable users to convert back by rescaling those values and will be reflected as per CF conventions. It can be used writing on any netcdf file.

**Comment by sixy6e** [comment]
I think this is what you're trying to say:

"You require the *scale_factor* and *add_offset* variable attributes to the netCDF write utility."

**Comment by omad** [comment]
See http://unidata.github.io/netcdf4-python/#netCDF4.Variable.set_auto_maskandscale for more information about `scale_factor` and `add_offset` when using the Python NetCDF library.

This shouldn't be too hard to implement.
