### ISSUE TITLE
OGR_ENABLE_PARTIAL_REPROJECTION Error

### ISSUE THREAD

**Issue by felipk101** [opendatacube/datacube-core#233]
I'm getting the following error when ingesting to a conda install (Anaconda), the same ingest and product configuration files (see attached) work seamlessly on the CEOS datacube install.

I also overcame this error by setting `export OGR_ENABLE_PARTIAL_REPROJECTION=TRUE`, yet the lat/longs of the ingested files seem wrong.

The case study area is Mocoa Columbia, and latitudes are at the equator, not sure whether that has something to do with it.

Cheers

Felix

PS: This may help,  https://trac.osgeo.org/gdal/ticket/3758
```console
11:45(cubeenv) felix@twin1:~$ datacube -v ingest -c /home/felix/Datacube/ingest/ingestion_configs/ls7_sr_scenes_wgs84_colombia1.yaml --executor multiproc 8
/home/felix/.conda/envs/cubeenv/lib/python3.6/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
 from pandas.tslib import OutOfBoundsDatetime
2017-05-12 11:40:06,272 6165 datacube INFO Running datacube command: /home/felix/.conda/envs/cubeenv/bin/datacube -v ingest -c /home/felix/Datacube/ingest/ingestion_configs/ls7_sr_scenes_wgs84_colombia1.yaml --executor multiproc 8
2017-05-12 11:40:06,319 6165 agdc-ingest INFO Created DatasetType ls7_LS_USGS_ARD_Colombia_Mocoa3
2017-05-12 11:40:06,349 6165 datacube.index._datasets INFO No changes detected for product ls7_LS_USGS_ARD_Colombia_Mocoa3
ERROR 1: Full reprojection failed, but partial is possible if you define OGR_ENABLE_PARTIAL_REPROJECTION configuration option to TRUE
```

[YAMLS.zip](https://github.com/opendatacube/datacube-core/files/1000112/YAMLS.zip)

YAMLS also at https://gist.github.com/omad/c0b7defbe70dc07fd2dfcbd4e2e48727

**Comment by Lunasunsea** [comment]
When I use the script provided in utils/usgslsprepare.py to prepare the Landsat scenes for use with the Data Cube, I met the problem:"UnboundLocalError: local variable 'metafile' referenced before assignment",please can you tell me how to solve this?Thanks a lot~

**Comment by omad** [comment]
Closing, old, can be reopened if this reoccurs.
