### ISSUE TITLE
 if I can install the datacube on the centos6.5 ?

### ISSUE THREAD

**Issue by asqhaqs** [opendatacube/datacube-core#237]
hello ，I want to know if I can install the datacube on the centos6.5 ? Because my files are all on the centos6.5.

**Comment by jeremyh** [comment]
Hi Trident,
Yes, CentOS 6 is supported – some of our own systems are still CentOS 6. But we recommend using conda to install as CentOS's built-in libraries are quite old. 

See the documentation page for conda installs: https://datacube-core.readthedocs.io/en/latest/ops/conda.html

**Comment by asqhaqs** [comment]
thanks so much for your quick and helpful response
