### ISSUE TITLE
How to get the example data in the guide docs

### ISSUE THREAD

**Issue by asqhaqs** [opendatacube/datacube-core#238]
### Expected behaviour
Hi ，I am a new user for the datacube. When I follow the guide docs  like 
http://datacube-core.readthedocs.io/en/stable/ops/indexing.html
and the examples like   
https://github.com/data-cube/agdc-v2-examples ,
I can't find where to get the needed data such as   'ls5_nbar_albers'   
![image](https://cloud.githubusercontent.com/assets/14349360/26191613/2805f1a8-3be1-11e7-960b-7fca1661b217.png)

And then I visit the USGS website(https://landsat.usgs.gov/CDR_LSR.php) to download some landset data to analysis . But its format is different from the  usgslsprepare.py or other python scripts in the
https://github.com/opendatacube/datacube-core/tree/develop/utils

so if I can find somewhere to get the example data('ls5_nbar_albers' ) or is there some more clearly guide or example for the indexing and ingesting data operations illustration?

**Comment by ghost** [comment]
I agree, the website doesn't give complete example satellite data and corresponding metadata and config files. I spend nearly one month to get the data and related config files. finally, succeed.

**Comment by amruthkiran94** [comment]
@gis-lijunjie  Please do share the links for the example data and configuration files. It would help beginners immensely.

**Comment by alexgleith** [comment]
I'm going to close this issue. There's some examples with accessing public data available now, such as [Cube in a Box](https://github.com/opendatacube/cube-in-a-box).
