### ISSUE TITLE
Group-based permissions & finer-grained authentication

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-core#24]
- Use of individual user accounts rather than a single shared user/password.
- But users should still be able to "module load" the api without any further configuration (editing conf files).
  - AGDCv1 did this via a shared user and password hard-coded into the module, but this isn't ideal. It would be preferable to use existing environmental user accounts instead.
    - Look at PAM, LDAP, ident usage within NCI? All are built into Postgres and easy to configure.
- Postgres grants should all be to group roles, not user roles.

This will allow for many useful features: 
- Logging of per-user actions: such as who ingested a dataset
- More fine-grained access control (who can ingest, who can administer, who can query).
- Minimise password management by using existing systems.

**Comment by woodcockr** [comment]
Need to be a bit careful with the AAA design for AGDC. We have HPC, Cloud and PC targets and multiple deployment environments (e.g. NCI, Pawsey, AWS (CEOS Data Cube)). The technology stack shouldn't be hard wired in a way that prevents the variety of target environments from working.
Postgres authentication will probably be fine in all cases, but I'm no expert and just wanted to highlight the requirement here isn't just for the specific NCI deployment environment.

**Comment by jeremyh** [comment]
Good point Rob.

From the perspective of AGDC's code, this will only hard-code the Postgres roles expected not the authentication scheme.

The authentication scheme used is dependent on the deployment of the Postgres server. An environment can always use manually-configured users, as with AGDCv1.

**Comment by jeremyh** [comment]
- AGDC roles are now created on database initialisation
- We've added cli grant commands to add/modify users
- Our NCI modules now use NCI usernames instead of cube_user. 

Closing.
