### ISSUE TITLE
Large number of open/close operations on datasets impacting performance

### ISSUE THREAD

**Issue by Bis-Bala** [opendatacube/datacube-core#241]
### Background
I'm using agdc_statistics with pbs jobs to calculate ndwi on entire archive of datasets for all coastline.
NCI responded with an email  that our job is impacting in their /g/data2 filesystem.
### Expected behaviour
It should open and close on datasets after performing operation. It is opening and closing four times on every call of the dataset before actual read and lseek starts.

### Actual behaviour
The application is doing more than a million calls of open and close operations per second while running multiple polygons.
I am running stack trace on the stats job and I can see in each time, the process is trying to open four times to a single dataset. Three extra calls are also opening to the dataset and seems to be reading the header file and closing immediately. This causes more than a million call  for about 2000 datasets, considering running the jobs in chunks for a polygon region. 

The whole log of the trace can be found in /g/data/r78/ITEM/LOGS/trace_all_100.log.

This is a snapshot of the stack trace
```
open("NetCDF:/g/data/rs0/datacube/002/LS5_TM_NBAR/-2_-14/LS5_TM_NBAR_3577_-2_-14_19870912004347000000.nc:blue", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("NetCDF:/g/data/rs0/datacube/002/LS5_TM_NBAR/-2_-14/LS5_TM_NBAR_3577_-2_-14_19870912004347000000.nc:blue", 0x7ffe76da8870) = -1 ENOENT (No such file or directory)
readlink("NetCDF:/g/data/rs0/datacube/002/LS5_TM_NBAR/-2_-14/LS5_TM_NBAR_3577_-2_-14_19870912004347000000.nc:blue", 0x34e7820, 2048) = -1 ENOENT (No such file or directory)
open("/g/data/rs0/datacube/002/LS5_TM_NBAR/-2_-14/LS5_TM_NBAR_3577_-2_-14_19870912004347000000.nc", O_RDONLY) = 12
fstat(12, {st_mode=S_IFREG|0674, st_size=3671134, ...}) = 0
mmap(NULL, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f48f9768000
read(12, "\211HDF\r\n\32\n\2\10\10\0\0\0\0\0\0\0\0\0\377\377\377\377\377\377\377\377^\0048\0"..., 1048576) = 1048576
lseek(12, 0, SEEK_SET)                  = 0
close(12)                               = 0
munmap(0x7f48f9768000, 1048576)         = 0
open("/g/data/rs0/datacube/002/LS5_TM_NBAR/-2_-14/LS5_TM_NBAR_3577_-2_-14_19870912004347000000.nc", O_RDONLY) = 12
fstat(12, {st_mode=S_IFREG|0674, st_size=3671134, ...}) = 0
fstat(12, {st_mode=S_IFREG|0674, st_size=3671134, ...}) = 0
mmap(NULL, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f48f9768000
read(12, "\211HDF\r\n\32\n\2\10\10\0\0\0\0\0\0\0\0\0\377\377\377\377\377\377\377\377^\0048\0"..., 1048576) = 1048576
close(12)                               = 0
munmap(0x7f48f9768000, 1048576)         = 0
open("/g/data/rs0/datacube/002/LS5_TM_NBAR/-2_-14/LS5_TM_NBAR_3577_-2_-14_19870912004347000000.nc", O_RDONLY) = 12
fstat(12, {st_mode=S_IFREG|0674, st_size=3671134, ...}) = 0
lseek(12, 0, SEEK_SET)                  = 0
read(12, "\211HDF\r\n\32\n", 8)         = 8
close(12)                               = 0
open("/g/data/rs0/datacube/002/LS5_TM_NBAR/-2_-14/LS5_TM_NBAR_3577_-2_-14_19870912004347000000.nc", O_RDONLY) = 12
fstat(12, {st_mode=S_IFREG|0674, st_size=3671134, ...}) = 0
lseek(12, 0, SEEK_SET)                  = 0
read(12, "\211HDF\r\n\32\n", 8)         = 8
lseek(12, 0, SEEK_SET)                  = 0
read(12, "\211HDF\r\n\32\n\2", 9)       = 9
read(12, "\10\10\0\0\0\0\0\0\0\0\0\377\377\377\377\377\377\377\377^\0048\0\0\0\0\0000\0\0\0\0"..., 39) = 39
lstat("/g/data/rs0/datacube/002/LS5_TM_NBAR/-2_-14/LS5_TM_NBAR_3577_-2_-14_19870912004347000000.nc", {st_mode=S_IFREG|0674, st_size=3671134, ...}) = 0
read(12, "OHDR\2\r-\1\2\"\0\0\0\0\0\3\f\0\0\0\0\0\0\0\3416\f\0\0\0\0\0"..., 512) = 512
lseek(12, 800627, SEEK_SET)             = 800627
read(12, "BTHD\0\5\0\2\0\0\v\0\0\0d(\341F\36\0\0\0\0\0\f\0\f\0\0\0\0\0"..., 38) = 38
lseek(12, 800481, SEEK_SET)             = 800481
read(12, "FRHP\0\7\0\0\0\2\0\20\0\0\0\0\0\0\0\0\0\0\377\377\377\377\377\377\377\377\321\0"..., 146) = 146
lseek(12, 1984225, SEEK_SET)            = 1984225
read(12, "BTLF\0\5~}e\7\0C\0\0\0\24\0/\315**\0\201\0\0\0\30\0002U\311A"..., 512) = 512
lseek(12, 2598710, SEEK_SET)            = 2598710
```

### Comment by NCI

> Daniel Rodwell commented:
> 
>  
> We've noticed that you are currently running a number of jobs under u46 against the v10 AGDC dataset on /g/data2.
>  
> The jobs are generating very large number of cumulative Open/Close operations on the gdata2 filesystem, peaking at 1.77 Million open 
> 
> operations per second, with an accompanying close operation. The jobs are also generating ~500,000 stat operations, for a total of 
> 
> 3.36M filesystem operations per second.
>  
> This is considered an abnormal behaviour, and has not been seen previously by any other jobs using datasets on gdata2. 
>  
> Many of the IO request sizes are very small, ranging from 4-32KB seek, mixed with some larger operations up to 1MB. In effect, there 
> 
> are a lot of files being opened, but very little data being read from within them.
>  
> The combination of the very high open/close rate and the small IO access is placing a higher than usual load on the filesystem, which 
> 
> is likely impacting the performance of other users jobs.
>  
> We'd kindly ask that you investigate if there is a more efficient method of running your job, particularly one that minimises 
> 
> unnecessary ope/close and stat operations. 
>  
> Example job IDs are 5132942.r-man2, 5123801.r-man2 and 5132849.r-man2
>  
> Regards,
> Daniel.
>  
> –
> Daniel Rodwell
> Manager, Data Storage Services
> National Computational Infrastructure
> NCI Building (143), Cnr Garran and Ward Roads
> The Australian National University
> Canberra ACT 0200 Australia

### Steps to reproduce the behaviour

It can be reproduced by using following command 
strace -e trace=all datacube-stats -v < *.yaml>

### Environment information

* Which ``datacube --version`` are you using?
  1.3.2
* What datacube deployment/enviornment are you running against?
  Running on the NCI, loaded from agdc-py3-prod

**Comment by Kirill888** [comment]
blocked by #625
IO driver re-work should allow file handle caching that would improve disk access patterns.
