### ISSUE TITLE
ability to get publishing time list for the searching dataset

### ISSUE THREAD

**Issue by yan073** [opendatacube/datacube-core#247]
In the old API, the function get_descriptor(...) returns a list of publishing time, the latest and the earliest publishing time for the given dataset searching criteria, without loading the actual dataset.

Now, the function get_descriptor(...) is deprecated. Can we have this function back in the new API?
This function will make it possible to create better UI to the user to browser and process datasets.

Thank you!

**Comment by benjimin** [comment]
Is that what `find_datasets` does?

**Comment by yan073** [comment]
In my testing, `find_datasets(product='ls5_nbar_albers', x=(149.25, 149.35), y=(-35.25, -35.35))` only returns a list of Dataset id, type, and location. No time field is returned.
Is there any flag or parameter to ask for publishing time?

Thank you!

**Comment by benjimin** [comment]
What about something like `[ds.center_time for ds in dc.find_datasets(..)]` ?

**Comment by yan073** [comment]
It works!
Thank you, Ben!

**Comment by yan073** [comment]
This can be achieved by using [ds.center_time for ds in dc.find_datasets(..)] .
Thanks Ben for his suggestion!
