### ISSUE TITLE
Determine reasonable storage compression for storage units

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#26]
Investigate available compression algorithms and specify a compression rate to optimise data access performance. 

Produce compression ratio versus access speed for different algorithm parameters (Nan percentages) -ignore storage file size as a constraint for now. Using image data - not random generated.

**Comment by sixy6e** [comment]
Potential spatial area to be used for compression testing.  This selection should create file containing sparse data, as well as complete data.

![storage-units-compression-testing-area](https://cloud.githubusercontent.com/assets/4917324/10986538/035f5238-847f-11e5-869a-144792f1f91b.png)

**Comment by sixy6e** [comment]
I forgot to post the report.  It can be found here:

http://www.datacube.org.au/wiki/File:Compression-chunk-testing.pdf

From the testing a spatial block size of 200 by 200 worked quite well, as did a compression level of 4.
The z-axis chunk size of 10 faired better with this data in terms of compression and access speed, but wasn't too different from a size of 5 or 20.
