### ISSUE TITLE
Transferring Datasets and Products between Databases

### ISSUE THREAD

**Issue by benjimin** [opendatacube/datacube-core#275]
Copying dataset records between different databases is tricky yet very useful (e.g. production vs private). I propose the documentation should explain the process in detail, or there should be a dedicated tool.

(The process is tricky because some of the relationships use keys that are specific only to the db instance, which means the data seem scrambled, e.g. datasets end up grouped under the wrong product, if naively inserted from one db into the other.)

One solution would be along these lines:
```sql
-- psql to your private database --
create extension postgres_fdw;
create server proddb foreign data wrapper postgres_fdw options (host 'agdc-db', dbname 'datacube'); -- connect
create user mapping for $user server proddb options (user '$user', password '$pass'); -- copy password from ~/.pgpass
create schema prod;
import foreign schema agdc from server proddb into prod;

begin;
create temporary table staging as select * from prod.dataset where dataset_type_ref=(select id from prod.dataset_type where name like '$product');
update staging set dataset_type_ref=(select id from agdc.dataset_type where name like '$product');
update staging set metadata_type_ref=(select metadata_type_ref from agdc.dataset_type where name like '$product');
insert into agdc.dataset select * from staging;
insert into agdc.dataset_source select * from prod.dataset_source where dataset_ref in (select id from staging); --may fail here unless ancestors tranferred before derived products!
insert into agdc.dataset_location select * from prod.dataset_location where dataset_ref in (select id from staging);
drop table staging;
commit;
```

**Comment by omad** [comment]
Closing for now. Not because it doesn't still need addressing, but that hopefully it'll come out of other work like being able to export and import products and datasets.

Thanks for the SQL foo for copying between databases.
