### ISSUE TITLE
dc.load returning almost no scenes for a large polygon but many for a small polygon in the same area

### ISSUE THREAD

**Issue by BexDunn** [opendatacube/datacube-core#276]
### Expected behaviour

Expect to get a similar number of scenes retrieved across a polygon area, when using a big polygon in the dc.load call vs using a small polygon in the dc.load retrieval.

### Actual behaviour
If I plot the scenes retrieved I get a triangle shape with about 2 observations in it in the big polygon, whereas in that area for the small polygon I get 300-600 scenes retrieved. (Over 30 yr epoch, ls5,7 and 8)
![image](https://user-images.githubusercontent.com/20038594/28957403-1452e238-7935-11e7-99dc-cacfe1faeeb2.png)

### Steps to reproduce the behaviour
https://github.com/rjdunn/GWnotebooks/blob/master/Dask_wetness_anomaly_debugger_040817-forDC.ipynb

The code above should run for either of the queries below. Obv you may wish to change the paths for the output files. 

queries used:

Big polygon
```{'dask_chunks': {'time': 5},
 'geopolygon': Geometry(POLYGON ((-83105.2314368732 -1451602.90924564,-33391.0599240792 -1455644.18659597,-37415.0420370399 -1505610.83402089,-87117.7910054179 -1501569.35056345,-83105.2314368732 -1451602.90924564)), PROJCS["GDA94_Australian_Albers",GEOGCS["GCS_GDA_1994",DATUM["Geocentric_Datum_of_Australia_1994",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Albers_Conic_Equal_Area"],PARAMETER["standard_parallel_1",-18],PARAMETER["standard_parallel_2",-36],PARAMETER["latitude_of_center",0],PARAMETER["longitude_of_center",132],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]),
 'time': ('1987-01-01', '2016-12-31')}
```

Little polygon
```{'dask_chunks': {'time': 5},
 'geopolygon': Geometry(POLYGON ((131.554434234076 -13.8009653022795,131.547892015813 -13.8790036027955,131.496441846499 -13.8746177747694,131.503013176119 -13.7965809082819,131.554434234076 -13.8009653022795)), GEOGCS["GCS_WGS_1984",DATUM["WGS_1984",SPHEROID["WGS_84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]),
 'time': ('1987-01-01', '2016-12-31')}
```

## Environment information

* Which ``datacube --version`` are you using?
1.3.2
* What datacube deployment/enviornment are you running against?
behavior same on raijin and on VDI

**Comment by Kirill888** [comment]
After some analysis error was identified in `Datacube.load` when using `dask_chunks` parameter, basically custom fuser function and `skip_broken_datasets` do not flow through to .

Missing `fuse_func` leads to using default fuser, which in the case of PQ masks is completely broken. This in turn leads to no data in the south part of the tile after masking is applied.

![broken_fuser_sample](https://user-images.githubusercontent.com/1428024/29057518-4c374736-7c4e-11e7-94eb-1764cd2e44cd.png)

Bottom image should look like top-right, instead it's an exact copy of top-left.

**Comment by Kirill888** [comment]
Error was in `datacube.api.core.py::fuse_lazy` and was partially fixed by this commit  

https://github.com/opendatacube/datacube-core/commit/639774bacd3dca803fa3226f17af839ea4c85af4#diff-73367154868e05ad209c8e4c81a320b8

By explicitly naming `fuse_func` parameter.

However call chain `load->make_dask_array->fuse_lazy->_fuse_measurement` still drops `skip_broken_datasets=<False|True>` parameter.

**Comment by Kirill888** [comment]
reproduced on 1.5.1 on NCI

https://gist.github.com/Kirill888/7f79dc864e398f5d9eb08fed3c463d01
