### ISSUE TITLE
Support for MODIS Surface Reflectance products

### ISSUE THREAD

**Issue by amruthkiran94** [opendatacube/datacube-core#286]
The MODIS data product for the series MCD43A1-A4 is available for indexing and ingestion but they are BRDF and Albedo data products. The Land product for Australia and global, priority list is attached and linked below- 
http://wiki.auscover.net.au/wiki/Land_products_for_Australia_and_global

![issuegit](https://user-images.githubusercontent.com/17108758/29870427-07c31c70-8da5-11e7-938f-1f1c0594779f.png)

**Will there be a support for the surface reflectance data products MOD09Ax series?**
This link edited 2 years ago gives some light.
http://www.datacube.org.au/wiki/MODIS_ARD _(2nd point under 'MODIS Ingest')_
or to quote -

> Create a custom MOD09 or MOD43 product from Edward’s L1A swatch archive, with sun/satellite angles and cloud and observation attributes to align with the Landsat pipeline as sensibly possible.

Thank you.

**Comment by mpaget** [comment]
Hello Amruth,

You have the right links for MODIS in the data cube (Australian implementation, at least).

MCD43A1-4 are the priority products for Australia's use cases. You will note on the wiki.auscover link that the full mirrored archive is now complete in Australia, and the next step is to check/update/operationalise the indexing configuration files and scripts for these products.

In Australia we don't have a strong use case for the LPDAAC MOD09 surface reflectance products as we have an operational MODIS swath (L1A/B) from which we are more likely to derive MOD09 products and feed these into the Australian implementation of the data cube instead. This activity will (hopefully) be restarted later this year.

Nevertheless, I do expect that when we check and update the indexing configuration files and scripts for MCD43A1-4 it will be relatively easy task to create/check/update the configuration files and scripts for most of the other LPDAAC products. Certainly we recognise the value having configuration files and scripts for most of the LPDAAC products - it just hasn't been a strong use case for us beyond MCD43A1-4 to date.

Stay tuned. I expect this task will get some attention in the next couple of weeks.

All the best,
Matt

**Comment by amruthkiran94** [comment]
Thank you @mpaget  for your quick response! I sure hope the MOD09 products get some attention in the near future. The basic surface reflectance products often provide a good start for those beginners who step into the world of the Data Cubes and Analytics, before the more specific and complex MOD43Ax series (BRDF/Albedo).

Any updates on the product/configuration/ingestion files for the MOD09 series or other LPDAAC products would be highly appreciated.

Thank you once again,
Amruth Kiran.

**Comment by woodcockr** [comment]
Stale issue closed
