### ISSUE TITLE
TypeError: illegal data type for attribute when use China's domestic satellite data

### ISSUE THREAD

**Issue by ghost** [opendatacube/datacube-core#288]
I tried to use China's domestic satellite data (called GF-1) in datacube , and I finished defining and indexing data ,but when i ingested data

> ` datacube ingest -c C:\Users\ZHD\Desktop\test\config.yaml `  (it is my configuration file path)

it was wrong

> E:\envs\agdcv2\lib\site-packages\rasterio\warp.py:286: ComplexWarning: Casting complex values to real discards the imaginary part 
> init_dest_nodata, **kwargs)
> 2017-09-04 09:59:35,703 6776 agdc-ingest ERROR Task failed
> Traceback (most recent call last):
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\scripts\ingest.py", line 302, in process_tasks
>     executor.result(future)
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\executor.py", line 64, in result
>     return func(*args, **kwargs)
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\executor.py", line 37, in get_ready
>     result = SerialExecutor.result(futures[0])
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\executor.py", line 64, in result
>     return func(*args, **kwargs)
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\scripts\ingest.py", line 260, in ingest_work
>     variable_params)
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\drivers\manager.py", line 228, in write_dataset_to_storage
>     return self.driver.write_dataset_to_storage(dataset, *args, **kargs)
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\drivers\netcdf\driver.py", line 27, in write_dataset_to_storage
>     return write_dataset_to_netcdf(dataset, *args, **kargs)
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\storage\storage.py", line 662, in write_dataset_to_netcdf
>     netcdfparams)
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\storage\storage.py", line 625, in create_netcdf_storage_unit
>     setattr(nco, key, value)
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\storage\netcdf_safestrings.py", line 65, in __setattr__
>     super(_NC4DatasetProxy, self).__setattr__(name, value)
>   File "netCDF4\_netCDF4.pyx", line 2438, in netCDF4._netCDF4.Dataset.__setattr__ (netCDF4\_netCDF4.c:20352)
>   File "E:\envs\agdcv2\lib\site-packages\datacube-0+unknown-py2.7.egg\datacube\storage\netcdf_safestrings.py", line 70, in setncattr
>     super(_NC4DatasetProxy, self).setncattr(name, value)
>   File "netCDF4\_netCDF4.pyx", line 2367, in netCDF4._netCDF4.Dataset.setncattr(netCDF4\_netCDF4.c:19311)
>   File "netCDF4\_netCDF4.pyx", line 1308, in netCDF4._netCDF4._set_att (netCDF4\_netCDF4.c:8002)
> TypeError: illegal data type for attribute, must be one of ['i8', 'f4', 'u8', 'i1', 'u4', 'S1', 'i2', 'u1', 'i4', 'u2', 'f8'], got O
> 0 successful, 1 failed

**Comment by ghost** [comment]
i tried many ways to solve ( like changing  data format, such as tif,img,netcdf,ENVI and so on. like using gdal to extract raster digital number data and then create a new raster ), but didn't work , is there any suggestion?

**Comment by andrewdhicks** [comment]
Hi @gis-lijunjie 
Could you please post what is in your ingest config next to **dtype**.
The example below sets the _blue_ band to be stored as a signed 16 integer (_int16_)
```
measurements:
    - name: blue
      dtype: int16
      nodata: -999
      resampling_method: nearest
      src_varname: '1'
      zlib: True
      fletcher32: True
```

**Comment by ghost** [comment]
firstly, thanks a lot @andrewdhicks 
I have found the problem and fixed it after I raised my question, I thought that my satellite datatype caused the error. In fact, it is wrong. It is Netcdf  global attributes that lead to the error. In ingest config,  must be careful when write global attributes, any illegal character is not allowed. And had better not set the value of the property null. 
Actually, I don't know specific format requirements for Netcdf  global attributes, I just copy it from an example landsat 5 config file. Anyway, it works. So I hope that datacube team can make detailed description for every metadata file and config file. It's best to give complete example satellite data and corresponding metadata and config files. Thanks
