### ISSUE TITLE
what is datacube's supported maximum size of single image

### ISSUE THREAD

**Issue by ghost** [opendatacube/datacube-core#289]
when my data is 10000X10000 (single image demensions), datacube works ,and no error
but when my data is 20000X10000, datacube doesn't work, says failed reading documents. So what is datacube's supported maximum size of single image?

**Comment by omad** [comment]
The largest single images that I know we have tested with are Landsat scenes which are approximately 5000x5000.

I'm not sure what the maximum supported size of a single image is, but I would have expected more than 20,000x10x000.

If you could provide a more detailed error message we might be able to track down what is causing the restriction.
