### ISSUE TITLE
Add ability to configure 'locations'

### ISSUE THREAD

**Issue by v0lat1le** [opendatacube/datacube-core#29]
Locations are named URI 'base paths'. For example gdata location can 'point to' file:///g/data. For now only file system locations are required. In the future web and S3 locations could be supported

see 59c1fbe4a6d033bc1187f1bd2fece8eaa3c5db7b for a potential config file solution

**Comment by v0lat1le** [comment]
do we want to store those in the db?

**Comment by jeremyh** [comment]
They are partially a description of how to reach the data from the current machine, so they don't seem to make sense in a central database.

But it does seem useful to be able to specify a default location (or something) for newly-connecting machines to use, at least when talking about remote data (or within an environment such as NCI).

Maybe if location_name is null, the path itself could be an absolute path (with full protocol etc "ftp://somemachine.com/data") to support arbitrary files too. Overkill?

**Comment by v0lat1le** [comment]
Config file for now...
