### ISSUE TITLE
Utilize .NC files in Datacube

### ISSUE THREAD

**Issue by amruthkiran94** [opendatacube/datacube-core#322]
How do I consider using ready made .nc files generated by NCI into my Datacube?
I've retrieved the files from http://dapds00.nci.org.au/thredds/catalogs/rs0/catalog.html for the Australian Landsat data series.

Do I need the satellite images to view the plots when generated on Jupyter such as http://nbviewer.jupyter.org/github/opendatacube/datacube-core/blob/develop/examples/notebooks/Datacube_Summary.ipynb this?

**Comment by omad** [comment]
Hi Amruth,

Hopefully you're not still stuck on this, sorry for the lack of earlier reply, but I know you've been a part of other discussions.

WRT to these specific datasets. If you have downloaded them locally, there are two steps required to use them in a separate Data Cube. First, the _Product_ they belong to must be added to the local Data Cube _Index_. The specification for DEA products is a little hard to find, but there's [a copy of them available here](https://gist.github.com/omad/f6ab64d851a937d01bebeade4a94e929). Once downloaded they can be added by running:
```bash
    datacube product add <products_document.yaml>
```

Then, they can be _Indexed_, by running:
```bash
    datacube dataset add <*.nc>
```

**Comment by amruthkiran94** [comment]
Thank You @omad for your answer. Although it might not be of much importance, I believe this would benefit first time users of the Data Cube who struggle to write the scripts themselves.

**Comment by omad** [comment]
At the ODC conference last week there was a lot of interest in removing the barrier of index/ingesting data for new users. We're working on documentation/script/data updates to hopefully be released in the next few weeks.
