### ISSUE TITLE
Import errors when default config is corrupted

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#335]
### Expected behaviour

`datacube --help` should print help regardless of broken config file

### Actual behaviour

`datacube --help` prints out stack trace when `~/.datacube.conf` is malformed.

### Steps to reproduce the behaviour
1. Create `~/.datacube.conf` with broken config for example one character file containing `[`
2. Run `datacube --help`
3. Observe stack trace

### Environment information

This is on `develop` branch

### Reason for the error

`LocalConfig.find` is called during import time from

`datacube-core/datacube/index/postgres/_connections.py`

**Comment by omad** [comment]
Closing issues from commits needs slightly difference syntax. The word _issue_ stopped it working.

`Fixes #335` or `Closes #335` would work.

https://help.github.com/articles/closing-issues-using-keywords/
