### ISSUE TITLE
Drop Support for Python 2

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#338]
I'd like to propose that future development on Data Cube Core stop supporting Python 2 after the beginning of February 2018.

We can continue to support Python 2 for bug fix releases of version 1.5.x, but beyond that it is an ongoing drain on the limited developer resources.

**Comment by mpaget** [comment]
Quite likely an appropriate proposal. I support it in principal. We could suggest that someone else may like to take up the mantle for python 2 maintenance; and the Core devs will focus on python 3 from Feb onwards.
