### ISSUE TITLE
subset from input dataset at ingest

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#34]
For cases where the storage unit only needs to be populated for a subset extent of the input data.

Example: Himawari 8 datasets have data for the entire globe, but we might only want to ingest and store data covering Australia.

**Comment by v0lat1le** [comment]
Should it go into the storage mapping config (or it's future incarnation)?
How complex should it be?
- Bounding box
- polygon
- multi-polygon

What projection should it be specified it?
- Source dataset? (UTM might be tricky)
- Target storage type?
- Lat/Lon EPSG:4326
- Specify its own projection

**Comment by v0lat1le** [comment]
Added 'roi' field to storage_mapping (soon to be renamed to storage_type).
Can specify bounding box in the storage unit crs.
More issues can be created for additional use cases when they become relevant
