### ISSUE TITLE
Better manage upstream dependencies

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#374]
## Background

Every now and then, our automated builds and freshly created environments fail due to changes in upstream dependencies. We've floated the idea of _pinning_ version numbers, in `setup.py` and/or `.travis/environment.yaml` and/or a not yet existing `requirements.txt`.

While a great idea, it would add extra work to keep these up to date.

Fortunately, with the recent change to using PyPI packages instead of conda-forge ones for TravisCI testing, we should be able to use one of:
 * https://pyup.io
 * ~https://libraries.io~
    October 2018: Can send emails, but not create PRs.
 * https://requires.io
 * ~https://dependabot.com~
    October 2018: Can only create PRs for one dep at a time, which will be unmanageable.

These tools can automatically check, notify and pull request (which includes testing) against a repository to keep it's list of dependencies nicely up to date. Hopefully with a minimum of work.

**Comment by omad** [comment]
Commit 9cebadb6fa7b5cb7b59cffba35a7818340d26874 has taken a step towards fixing this by pinning versions of dependencies in [`requirements-test.txt`](https://github.com/opendatacube/datacube-core/blob/9cebadb6fa7b5cb7b59cffba35a7818340d26874/requirements-test.txt) for running in Travis-CI.

https://github.com/opendatacube/datacube-core/blob/9cebadb6fa7b5cb7b59cffba35a7818340d26874/.travis.yml#L50

https://github.com/opendatacube/datacube-core/blob/9cebadb6fa7b5cb7b59cffba35a7818340d26874/requirements-test.txt#L1-L4

They will need periodic updates manually until we can integrate one of the above tools.

**Comment by omad** [comment]
https://requires.io FTW

**Comment by alexgleith** [comment]
Thanks @omad! On it ;-)

**Comment by alexgleith** [comment]
Requires.io has been implemented and appears to be working ok.
