### ISSUE TITLE
why ODC will sclice image scenes into grid ?

### ISSUE THREAD

**Issue by asqhaqs** [opendatacube/datacube-core#377]
Hello?  I don't understand why datacube would slice the image scene into grids and ingest them, compared with indexing the image scenes, what advantage or meaning does it have? could somebody help me? thanks

**Comment by woodcockr** [comment]
The ODC can just Index or it can Ingest (which is index+slice). The principle reason for ingestion is the data can be transformed from what is usually an archival data storage format into a computationally efficient form. With repeated use and tuned data storage forms the ODC can achieve higher overall performance compared with Index only.

How much of an improvement varies depending on the primary analytics use-cases, archive storage form and deployed environment. For example, the CSIRO deployment of the ODC on AWS ingests the archival form of the data (in most cases scenes or swaths in geotiff or netcdf) into AWS S3 object storage using the ODC S3 Array IO storage plugin. S3 is cheaper than file storage and with the S3AIO plugin scales better with increased computational nodes. The CSIRO deployment tends to treat the ingest form of that data as a caching mechanism where our most frequently used data is available. In future we would like to make the cache management automatic and on demand.

Alternately, the Digital Earth Australia deployment on the NCI High Performance Computing system has a shared archive of EO data. The data needs to be compatible with a range of non-ODC applications. The ODC uses this data in place as netcdf files via indexing only. It is efficient as the NCI HPC system has tuned these files to be performant in that environment whilst being compatible with a range of applications, of which ODC is one. There is no need to ingest in this deployment.

So sometimes, just indexing is easy, if you have a need for an archival form. The ODC will work with both index only and ingested forms. Which is more efficient depends on your environment and use-cases.

**Comment by ghost** [comment]
Rob Woodcock's explanation is really helpful, would it be possible to
include it in the documentation in some form? It helped me understand the
difference between indexing and ingesting better. Please delete if not
appropriate or if this explanation already has similar examples in the odc
docs.

**Comment by omad** [comment]
Thanks Rob, Bex,
I'm working on a big update to the documentation at the moment, which will be merged in this week. I'll find a place for something like that explanation. 👍
