### ISSUE TITLE
"Fuse_Data" Warning

### ISSUE THREAD

**Issue by amruthkiran94** [opendatacube/datacube-core#379]
Greetings! 
I've used the ODC before and was successfully able to index, ingest and view on Jupyter Notebook and carry out analysis as required, but occasionally i've come across this warning:

> "agdc-ingest WARNING Skipping (46, 342) - no "fuse_data" specified in config"
 
What does this mean exactly? Searching through the ingestion scripts, points to a "FUSER_KEY" variable.
Any suggestions to rectify this warning would be highly appreciated.
Thank you!

**Edit:** I've noticed if the time stamps on the metadata files are similar this issue seems to creep up. Randomly varying the time stamps by a second or two allows this warning to be suppressed.

Is there a clearer explanation as to how this "Fuse_Data" works?

**Comment by ashoka1234** [comment]
The `FUSER_KEY` points to a function to be used by the ingestion scripts when the tiles overlap or when the region of interest overlaps more than one tile. It basically tells how to fuse or combine the overlapping data. You can specify this function in the configuration scripts, e.g. `fuse_data: copy`.  Please check the configuration examples in [datacube-core/docs/config_samples/ingester](https://github.com/opendatacube/datacube-core/blob/develop/docs/config_samples/ingester/) eg. [s2amsil1c_albers_60.yaml](https://github.com/opendatacube/datacube-core/blob/develop/docs/config_samples/ingester/s2amsil1c_albers_60.yaml#L47). When you specify `fuse_data` in the config you will not see this warning.

**Comment by amruthkiran94** [comment]
Thank you for your quick reply and suggestion @ashoka1234 .
