### ISSUE TITLE
Storage unit temporal aggregator tool

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#38]
Aggregate all timeslices/storage units to single storage unit
1. Query database
2. Return single aggregated unit
3. Update DB

Operationally will be triggered by operator - user command line:
Assumes component timeslices exist
Fixed time range: 1 year for Landsat
Input time slices to aggregate will appropriately tagged to exclude from analysis / processing.

**Comment by v0lat1le** [comment]
datacube-ingest stack does this
