### ISSUE TITLE
No index driver found for 'default'

### ISSUE THREAD

**Issue by amruthkiran94** [opendatacube/datacube-core#384]
Greetings!

Using the latest Datacube version and libraries, indexing and ingestion runs well except when I try to access the database on Jupyter I get the "No index driver found for 'default': 0 available: " error.

> RuntimeError                              Traceback (most recent call last)
> ipython-input-2-f074b535470c> in <module>()
>       1 
>       2 import datacube
> ----> 3 dc = datacube.Datacube(config='E:\Datacubes\datacube-core-develop\datacube.conf')
>       4 dc
> 
> E:\Datacubes\datacube-core-develop\datacube\api\core.py in __init__(self, index, config, app, env, validate_connection)
>     116             index = index_connect(normalise_config(config),
>     117                                   application_name=app,
> --> 118                                   validate_connection=validate_connection)
>     119 
>     120         self.index = index
> 
> E:\Datacubes\datacube-core-develop\datacube\index\_api.py in index_connect(local_config, application_name, validate_connection)
>      37         raise RuntimeError(
>      38             "No index driver found for %r. %s available: %s" % (
> ---> 39                 driver_name, len(index_drivers()), ', '.join(index_drivers())
>      40             )
>      41         )
> 
> RuntimeError: No index driver found for 'default'. 0 available: 

I've reinstalled PostgreSQL and all libraries, to no avail.
All suggestions are welcome.

**edit:** While ingestion I get this warning

>  datacube.drivers.driver_cache WARNING Failed to resolve driver datacube.plugins.io.write::s3aio
>  datacube.drivers.driver_cache WARNING Failed to resolve driver datacube.plugins.io.write::s3aio_test

where do I update the driver from? Is it because of this plugin?

**Comment by omad** [comment]
Hi Amruth,

It's now necessary to install the datacube code, instead of just using it from the source directory. Installing registers the drivers used for accessing the database and reading data. Do this by running from within the `datacube-core` directory:
```bash
    pip install -e .
```
The `-e` gives you an editable install, which means you can continue to update the code from git to receive the latest updates.

I'll leave this ticket open until someone updates the error message to be a bit more helpful.

**Comment by Kirill888** [comment]
I think that default index driver should be available even if entry points are messed up or missing. This is the behaviour in the reader plugin.

**Comment by amruthkiran94** [comment]
I have followed the instructions as per the official and latest documentation http://datacube-core.readthedocs.io/en/latest/ops/windows.html during all my previous runs and have never come across this issue. 
@omad  I've obtained the .zip archive of the latest release and installed via the python setup file ` python setup.py install` as per the documentation. Although that also means any update on the Git wont be reflected on my local system.

I updated Conda and all its libraries and I believe something there has corrupted my install/drivers.

Testing on another machine to verify this.

**Comment by amruthkiran94** [comment]
@omad  I tried the command `pip install -e {path}` as you suggested, but to no avail. Attaching screenshots,
![git](https://user-images.githubusercontent.com/17108758/37244331-69c302c4-24ad-11e8-8780-6ad3dbfdce24.png)

Reinstalled DC, all the libraries, PostgresSQL also just to verify. Also `datacube system check` returns that the  index drivers available are "default".
![git2](https://user-images.githubusercontent.com/17108758/37244401-8d57831c-24ae-11e8-87d8-97e0454b6b06.PNG)

Accessing on Jupyter throws me this error.
![git](https://user-images.githubusercontent.com/17108758/37244407-a383c010-24ae-11e8-9bcf-6513810e7383.PNG)

Why do I feel like I'm missing something simple here, Please update with any suggestions and/or correct any mistakes I've made.

**Edit: Closed by accident.**

**Comment by Kirill888** [comment]
Hi Amruth, the error you see is a warning and will not prevent you from using the system. This particular driver is not available on Windows, we will update installation script to exclude it when installing on windows, in the mean time if the warning bothers you, you can edit setup.py and remove 

https://github.com/opendatacube/datacube-core/blob/develop/setup.py#L113-L114

You will then have to run pip install again for changes to take effect

**Comment by amruthkiran94** [comment]
**Update**
Installation as described in the documentation would yield the warning on Jupyter Notebook while using the `load` function and I wasn't able to go ahead in my code from here. (Maybe as @Kirill888 said, it should not prevent me from using the system, so maybe some changes in my script would do the trick).

**FIX**
As suggested by @omad  using the command `pip install -e {path_of _archive}` after installation from source directory and consequently indexing and ingesting data, I was able to view on Jupyter Notebook, albeit with a harmless warning message ( as pointed out by @Kirill888 ).

Sometimes a full reinstall of all libraries and virtual environment came in handy to debug most errors. I'm sure beginners to this field such as myself would be benefited, if this be added to the documentation.

Thanks to @omad  and @Kirill888  for your valuable suggestions.
