### ISSUE TITLE
Mislabeled architecture doc section

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#388]
Section

Architecture Guide> "Virtual Products"

Is not about "virtual products", it describes storage, and should be integrated into storage section of the "Architecture Guide"

This file should be renamed:

https://github.com/opendatacube/datacube-core/blob/develop/docs/architecture/virtual.md

or merged into 

https://github.com/opendatacube/datacube-core/blob/develop/docs/architecture/storage.rst

**Comment by omad** [comment]
I'll merge it in, working on it now.
