### ISSUE TITLE
Very slow to load data when resampling requested in query

### ISSUE THREAD

**Issue by CEKrause** [opendatacube/datacube-core#395]
### Expected behaviour
Resampling of Landsat to 10m x 10m pixels for comparison with Sentinel 2 would not have a great impact on the speed of `dc.load`.

### Actual behaviour
`dc.load` slowed to the point where it was essentially unusable. e.g. Began extraction prior to a 1 hour meeting, and it hadn't finished loading in the tiny area (all time, all bands) by the time I came back.

### Steps to reproduce the behaviour
`ds = dc.load(product = ls5_nbar_albers, group_by = 'solar_day', **query)`

```
query = {'output_crs': 'EPSG:3577',
         'resolution': (-10, 10),
         'geopolygon': geom
        }
```
Note that the geopolygon is not the problem - same issue encountered when a small bounding box was used instead. Area for extraction is very small (~50 by ~70 pixels in Sentinel2)

### Environment information

* Which ``datacube --version`` are you using?
* What datacube deployment/enviornment are you running against?
DEA on the VDI, loaded with 
```
module use /g/data/v10/public/modules/modulefiles/
module load agdc-py3-prod
```

**Comment by Kirill888** [comment]
This TODO: clearly needs fixing:

https://github.com/opendatacube/datacube-core/blob/36b580f1babfee203aec129e8a4651225ae82d75/datacube/storage/storage.py#L350-#L361

**Comment by Kirill888** [comment]
Some versions of rasterio had bugs when reprojecting from multi-band file (stacked netcdf in this case). It was fixed in the version currently installed in the `agdc-py3-prod` but we still use slower work around

https://github.com/opendatacube/datacube-core/blob/36b580f1babfee203aec129e8a4651225ae82d75/datacube/storage/storage.py#L402

**Comment by Kirill888** [comment]
Looks like 1.0a9 if the version where they fixed it:

https://github.com/mapbox/rasterio/commit/dbd389c483b65459bd6114e5db4ab172836336cd

**Comment by omad** [comment]
Oh yeah, that looks like a tragic confluence of bugs, and would explain the behaviour I saw on Claire's computer. There was significantly more network traffic than necessary to load the tiny amount of data requested.

Who wants to work on fixing this?

The immediate fix would be to not fall back to `OverrideBandDataSource` if using a new enough `rasterio`.
