### ISSUE TITLE
Access Data Cube via custom Web Application

### ISSUE THREAD

**Issue by amruthkiran94** [opendatacube/datacube-core#397]
Greetings!
How would I go about in accessing the ingested data from the datacube using a custom web-page, instead of Jupyter Notebook? I was hoping to display the ingested data and run analytics on a remote environment preferably connected through services such as WampServer or XAMPP.

 |**Server**   | -------------------- >      |   **Web App**   |  -------------- >    |  **Run Analytics andVisualize**|
|Data Cube  | --------------  >     |   User-Interface  |  ------------------ >    |              End-User                      |

Basic ideology was to hide the intricacies of the analysis, i.e. the Python code which is run on JupyterNotebook with just a simple UI, buttons which can display the products and measurements and run a sample code on the ingested data, as well as displaying a map of the same.

A UI by CEOS on https://github.com/ceos-seo/data_cube_ui is available, does anyone have any working experience on this particular project? especially on a windows environment.

Thank you!

**Comment by roarmstrong** [comment]
Hi @amruthkiran94, in your case I think the CEOS datacube UI would be a good starting point. It will let you view the ingested data as well as write custom algorithms which can be accessed from from the web UI.

**Comment by amruthkiran94** [comment]
Thank you @roarmstrong  for your quick reply.
The CEOS datacube UI is built on Ubuntu, I was hoping for a windows implementation. Any suggestions on how to implement a simpler UI on windows?

**Comment by roarmstrong** [comment]
Hi @amruthkiran94, sorry for the lateness of this reply! Unfortunately I don't have any specific suggestions on implementing a simple webservice on windows, however using parts CEOS UI as a base is probably a good starting point. Most of the dependencies can be built or used on Windows and it should give you an idea on how to structure the application.

**Comment by amruthkiran94** [comment]
@roarmstrong  Thankyou!
I have gone ahead by building the UI from scratch using Bootstrap and Python to run the scripts. Database connections are authenticated server side by PHP and a minimal Javascript on the user side. The CEOS UI is a bit complicated to re-do at the moment. I'm satisfied with my results so far.

Mods please close this thread.
Thank you @roarmstrong  for your help. This community has been very patient with newbies like me :)

**Comment by omad** [comment]
Thanks @amruthkiran94, we'd love to see what you come up with, if and when you're ready to share. :)
