### ISSUE TITLE
Allow indexing without provenance tracking

### ISSUE THREAD

**Issue by uchchwhash** [opendatacube/datacube-core#398]
### Rationale
For testing and debugging, it would be helpful if `datacube` allowed indexing datasets
with lineage information stripped off. This would help avoid filling test datacubes to hold,
for example, simple statistics on a product with irrelevant lineage data tracing back to
acquisition.

### Expected behaviour
Something along the lines of
`$ datacube dataset add --no-lineage DATASET`
should index dataset with `lineage.source_datasets` set to `{}`.

### Environment information
* Which ``datacube --version`` are you using?
Open Data Cube core, version 1.5.1+516.g7046071

**Comment by omad** [comment]
We already have a command line option of `--sources-policy`. How about adding another policy named `drop`. eg:
```bash
$ datacube dataset add --sources-policy drop <datasets>
```

**Comment by Kirill888** [comment]
But what does `--sources-policy=X` actually do? I remember expecting something else from it than what it actually does.

**Comment by Kirill888** [comment]
It already has "skip" which is very close to "drop", but what it skips is the dataset being added, not the sources dataset.

**Comment by Kirill888** [comment]
Also there is both "verify" and "ensure", but which one ensures more?

**Comment by jeremyh** [comment]
There's a docstring the explains it, but perhaps it belongs in one of the guides too?

`ensure`: ensure that it exists in the index (adding it if needed)

`verify` (default): ensure that it exists in the index (adding it if needed), and throw an error if any metadata differs from what we already have.

`skip`: Confusingly named: it skips adding the sources, but will still link them to this dataset.
- From a user perspective, `skip` really means "throw an error if we don't already have all the sources".
- Which is slightly more useful than it sounds: most of our processing is on datasets that are already in the cube, so if it's quietly adding new sources we'd want to know about it.
    - Example previous bug: an old scene processor that inappropriately scanned the filesystem for datasets to process was picking up datasets that were partially-written/corrupt.
- I think it was actually added before `ensure` existed, as brute-force way to "skip" the metadata verification. `ensure` is a more forgiving alternative.
