### ISSUE TITLE
_gdfnetcf.py - Invalid GDF.DECIMAL_PLACES

### ISSUE THREAD

**Issue by didierearith** [opendatacube/datacube-core#4]
Dear Team,

In _gdfnetcf.py, instruction at  line 155, failed.

I think GDF.DECIMAL_PLACES must be changed by self.decimal_places

Replace:
                dimension_index_vector = np.around(np.arange(dimension_min, dimension_max, element_size), GDF.DECIMAL_PLACES)

by:
                dimension_index_vector = np.around(np.arange(dimension_min, dimension_max, element_size), self.decimal_places)

Kind regards,

**Comment by omad** [comment]
Closing. GDF has been deprecated.
