### ISSUE TITLE
Calling DatasetType.dimensions when these are not set causes AttributeError

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-core#406]
### Expected behaviour
If I have a dataset, and I want to get the dimensions, I should be able to get them. And if they're missing, it should tell me they're missing.

### Actual behaviour

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-45-66e0a2a24ac8> in <module>()
      1 # print(ds)
      2 landsat8 = dc.index.products.get_by_name('ls8_level1_usgs')
----> 3 print(landsat8.dimensions)

/usr/local/lib/python3.5/dist-packages/datacube/model/__init__.py in dimensions(self)
    421         """
    422         assert self.metadata_type.name == 'eo'
--> 423         return ('time',) + self.grid_spec.dimensions
    424 
    425     @cached_property

AttributeError: 'NoneType' object has no attribute 'dimensions'
```

### Steps to reproduce the behaviour

 * Added product information for landsat `datacube product add .../docs/config_samples/dataset_types/ls_usgs.yaml`
 * Indexed Landsat8 from S3
 * Get the product with `landsat8 = dc.index.products.get_by_name('ls8_level1_usgs')`
 * try to access the dimensions like `lansat8.dimensions`

### Environment information

* Datacube in Docker, latest build from the `develop` branch as of 4/4/18
* Datacube and Jupyter as defined in this system: https://github.com/crc-si/opendatacube-cloudformation-testing

**Comment by Kirill888** [comment]
Obviously code should not crash the way it does, so it's an error. 

On the other hand it's perfectly reasonable for product not to have `grid_spec`, it's not clear what the behaviour should be in this case. When `grid_spec` is set dimensions are taken from `crs` property of the `grid_spec`, and are either `y,x` (most common) or `latitude,longitude`.

Options:

1. Default to projected coordinate `y,x`
2. Default to non-projected `latitude,longitude`
3. Raise exception
4. Return None
