### ISSUE TITLE
Steps to index datasets with example yaml files.

### ISSUE THREAD

**Issue by ashu6397** [opendatacube/datacube-core#417]
I have issues in adding data to datasets using the command datacube dataset add --automatch <path-to-dataset> Below is my dataset metadata file
[AW-NH43K-095-047C-29Dec15_metadata.zip](https://github.com/opendatacube/datacube-core/files/1902764/AW-NH43K-095-047C-29Dec15_metadata.zip)
# It's producing the following errors:- 
(cubeenv) C:\Users\Ashutosh Vaish>datacube dataset add --auto-match "C:\Users\Ashutosh Vaish\Desktop\AW-NH43K-095-047C-29Dec15_metadata.yaml"
Indexing datasets  [####################################]  100%2018-04-12 16:10:18,124 13540 datacube-dataset ERROR Unable to create Dataset for file:///C:/Users/Ashutosh%20Vaish/Desktop/AW-NH43K-095-047C-29Dec15_metadata.yaml: No matching Product found for {
    "id": "62079b50-8b63-4e39-949c-21f175b06fee",
    "creation_dt": "2015-12-29T00:00:00",
    "product_type": "GEOREF",
    "platform": {
        "code": "Resourcesat-2"
    },
    "instrument": {
        "name": "AWiFS(56.0m) Optical Data"
    },
    "format": {
        "name": "GeoTiff"
    },
    "extent": {
        "coord": {
            "ll": {
                "lat": 75.9909999,
                "lon": 29.99099999
            },
            "lr": {
                "lat": 77.009,
                "lon": 29.99099999
            },
            "ul": {
                "lat": 75.9909999,
                "lon": 31.009
            },
            "ur": {
                "lat": 77.009,
                "lon": 31.009
            }
        },
        "from_dt": "2015-12-29T00:00:00",
        "center_dt": "2015-12-29T00:00:00",
        "to_dt": "2015-12-29T00:00:00"
    },
    "grid_spatial": {
        "projection": {
            "geo_ref_points": {
                "ll": {
                    "x": 112.99986111,
                    "y": -44.000138890272005
                },
                "lr": {
                    "x": 153.999861110328,
                    "y": -44.000138890272005
                },
                "ul": {
                    "x": 112.99986111,
                    "y": -10.00013889
                },
                "ur": {
                    "x": 153.999861110328,
                    "y": -10.00013889
                }
            },
            "spatial_reference": "PROJCS[\"WGS 84 / UTM zone 44N\",GEOGCS[\"WGS 84\", DATUM[\"WGS_1984\", SPHEROID[\"WGS 84\",6378137,298.257223563, AUTHORITY[\"EPSG\",\"7030\"]], AUTHORITY[\"EPSG\",\"6326\"]], PRIMEM[\"Greenwich\",0, AUTHORITY[\"EPSG\",\"8901\"]], UNIT[\"degree\",0.01745329251994328, AUTHORITY[\"EPSG\",\"9122\"]], AUTHORITY[\"EPSG\",\"4326\"]],UNIT[\"metre\",1, AUTHORITY[\"EPSG\",\"9001\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",81],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],AUTHORITY[\"EPSG\",\"32644\"],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH]]"
        }
    },
    "image": {
        "bands": {
            "2": {
                "layer": "layer 1",
                "path": "C:\\Users\\Ashutosh Vaish\\Downloads\\awh43k29dec15\\AW-NH43K-095-047C-29Dec15-BAND2.tif"
            },
            "3": {
                "layer": "layer 2",
                "path": "C:\\Users\\Ashutosh Vaish\\Downloads\\awh43k29dec15\\AW-NH43K-095-047C-29Dec15-BAND3.tif"
            },
            "4": {
                "layer": "layer 3",
                "path": "C:\\Users\\Ashutosh Vaish\\Downloads\\awh43k29dec15\\AW-NH43K-095-047C-29Dec15-BAND4.tif"
            },
            "5": {
                "layer": "layer 4",
                "path": "C:\\Users\\Ashutosh Vaish\\Downloads\\awh43k29dec15\\AW-NH43K-095-047C-29Dec15-BAND5.tif"
            }
        }
    },
    "lineage": {
        "source_datasets": {}
    }
}
# I have already uploaded metadata_types and products and displaying them below:-
# Metadata
MetadataType(name='eo', id_=1)
MetadataType(name='eo_full', id_=3)
MetadataType(name='telemetry', id_=2)
# Products
id             Name                        Description                                                        Product_type  instrument            
6              Product_AWiFS         High Resolution Advanced Wide Field Sensor   GEOREF         AWiFS             GeoTiff      IRS_P6
1            Product_LISSIII  High Resolution Linear Imaging Self-Scanning S...   GEOREF            L3             GeoTiff      IRS_P6
4            ls5_level1_usgs       Landsat 5 USGS Level 1 Collection-1 OLI-TIRS     L1TP            TM             GeoTiff   LANDSAT_5
3            ls7_level1_usgs       Landsat 7 USGS Level 1 Collection-1 OLI-TIRS     L1TP           ETM             GeoTiff   LANDSAT_7
5             ls8_l1_pc_usgs     Landsat 8 USGS Level 1 Pre-Collection OLI-TIRS      L1T      OLI_TIRS             GeoTiff   LANDSAT_8
2            ls8_level1_usgs       Landsat 8 USGS Level 1 Collection-1 OLI-TIRS     L1TP      OLI_TIRS             GeoTiff   LANDSAT_8
7         modis_mcd43a1_tile             MODIS 500 metre MCD43A1 Collection 006  MCD43A1         MODIS   HDF4_EOS:EOS_GRID  AQUA_TERRA
8         modis_mcd43a2_tile             MODIS 500 metre MCD43A2 Collection 006  MCD43A2         MODIS   HDF4_EOS:EOS_GRID  AQUA_TERRA
12  modis_mcd43a3_sinusoidal  MODIS Albedo 16-Day L3 Global 500m, 1200 pixel...  MCD43A3         MODIS              NetCDF  AQUA_TERRA
9         modis_mcd43a3_tile             MODIS 500 metre MCD43A3 Collection 006  MCD43A3         MODIS   HDF4_EOS:EOS_GRID  AQUA_TERRA
11  modis_mcd43a4_sinusoidal  MODIS Nadir BRDF-Adjusted Reflectance 16-Day L...  MCD43A4         MODIS              NetCDF  AQUA_TERRA
10        modis_mcd43a4_tile             MODIS 500 metre MCD43A4 Collection 006  MCD43A4         MODIS   HDF4_EOS:EOS_GRID  AQUA_TERRA

**Comment by uchchwhash** [comment]
Hi @ashu6397, which product were you expecting to index into? Of the two GEOREF products that I can see, none of the has the exact instrument code "AWiFS(56.0m) Optical Data".

**Comment by ashu6397** [comment]
Hi @uchchwhash thanks for the early reply. I am indexing an AWiFS product of Cartosat-2 satellite I downloaded from an Indian website NRSC Bhuvan. I'm attaching the metadata file(xml) of the product.
[AW-NH43K-095-047C-29Dec15.zip](https://github.com/opendatacube/datacube-core/files/1906185/AW-NH43K-095-047C-29Dec15.zip)
This is the sole metadata file I got from their website. I had many issues with creating the product and dataset configuration files. I am attaching the product file that I created, here:- 
[Product_AWiFS.zip](https://github.com/opendatacube/datacube-core/files/1906193/Product_AWiFS.zip) 
# kindly rectify the errors if there are any, and please guide me with whole process as I am clearly misunderstanding the instructions present in opendatacube.org site.

**Comment by uchchwhash** [comment]
Hi @ashu6397 ,
If I understand you correctly, in your product file, you have this section:
```yaml
    platform:
        code: IRS_P6
    instrument:
        name: AWiFS
    product_type: GEOREF
    format:
        name: GeoTiff
```
whereas in your dataset, you have:
```yaml
product_type: GEOREF
platform:
    code: Resourcesat-2
instrument:
    name: AWiFS(56.0m) Optical Data
format:
    name: GeoTiff
```
For the dataset to match the product, these must match up exactly. Unfortunately the instrument and the platform sections do not match, which might be why you are getting this message.

Hope this helps!

**Comment by ashu6397** [comment]
Thanks for the help. Can you tell me how can I remove existing products and datasets using PostgreSQLPortable. I haven't come across any issue/document explaining it.

**Comment by Kirill888** [comment]
There is really no easy way to cleanup database. You can always drop the entire datacube database and reindex/reingest.

In your case however it might be possible to just **force** update product definition with the new instrument name.

```
datacube product update --allow-unsafe <product.yaml>
```

You can then try to index data again.

**Comment by Kirill888** [comment]
Seems like you `platform.code` also doesn't match up, so make sure to fix that too.

**Comment by ashu6397** [comment]
Yes thank you for noting that, and I guess `pgadmin` would be useful to execute edit and update queries. Thank for replying and helping me!
