### ISSUE TITLE
Enable query across multiple AGDC database instances of equal version

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#42]
For common versions of datacube databases on common infrastructure - enable query and data access using more than one database/datastore.

User story: user has a local datacube implementation (datacube 1) but wants to use data from a public instance (datacube 2) in the query.

**Comment by omad** [comment]
This is already possible, with a couple of restrictions that are being worked on.

```python
from datacube import Datacube

localdc = Datacube()
remotedc = Datacube(config='remoteserver.configfile')

local_datasets = localdc.find_datasets('ls5_nbar_albers')
remote_datasets = remotedc.find_datasets('ls5_nbar_albers')
```

Only data on a local filesystem can be accessed, but this will soon be resolved under another issue.
