### ISSUE TITLE
Jupyter Notebook crashes when displaying new data

### ISSUE THREAD

**Issue by ashu6397** [opendatacube/datacube-core#425]
Whenever I'm adding new data-sets to the data-cube the dimensions of the data-set increases i.e (time,lat,lon) increases from original value. On running the plot command on the notebook completely crashes the system. Is there a way in notebook by which I can limit the amount of data I want to display on the notebook?

**Comment by caffeine-potent** [comment]
Assuming you're using `datacube.load`. You can select a smaller area in space an time by providing values to crop it.  
  
here are some examples:  

```
my_dataset_1 = datacube.load(latitude = (20,21), longitude = (1,2))  
my_dataset_2 = datacube.load(latitude = (20,21), longitude = (1,2), time = ('2016-01-01', '2017-01-01')) 
my_dataset_3 = datacube.load(time = ('2016-01-01', '2017-01-01'))
```  
  
To see what other options you have for loading data, I suggest checking the documentation on [`datacube.Datacube.load`](http://datacube-core.readthedocs.io/en/latest/dev/api/generate/datacube.Datacube.load.html#datacube.Datacube.load)  
  

Another way would be loading in a lot of data, then selecting a sub-set of it using xarray indexing/selection. I would refer to [these docs](http://xarray.pydata.org/en/stable/indexing.html)

**Comment by ashu6397** [comment]
@caffeine-potent thank you, I will study these documentations.
