### ISSUE TITLE
Datacube Ingest config - better description of output name may be required

### ISSUE THREAD

**Issue by helyx-amcmillan** [opendatacube/datacube-core#437]
The AGDC-v2 UI requires the data product prefix (e.g. ls7_ledaps_) when adding a satellite, and creating a new area needs a matched ID to the ingested dataset (e.g. Ghana). When you first create your product output name in the ingest script it would be useful to have a bit more advice on the format of this name - I was unaware that it should be in the format sensor_format_{area} until I got to the UI.

**Comment by Kirill888** [comment]
@helyx-amcmillan thank you for your report and sorry for such a late response.

In `datacube-core` product name is allowed to be almost anything, a single character product_name will work just as well. This is why, I guess, it's not documented in the ingestor itself right now.

It is however a constraint imposed by [datacube-ui](https://github.com/opendatacube/datacube-ui), not sure if this constraint still holds (@caffeine-potent ?)

If product name constraint still holds in the ui code then we certainly need to update documentation both on the ui and ingest sides to warn users about expected product name formatting (@alexgleith)
