### ISSUE TITLE
Ask why a dataset fails to match a specific product

### ISSUE THREAD

**Issue by uchchwhash** [opendatacube/datacube-core#438]
### Expected behaviour
Some time when indexing a dataset, some omission or discrepancy in the metadata results in no matching product being found. Often there is a specific product in mind. If I could ask 
```bash
$ datacube dataset add FILE --intended-product=SOME_PRODUCT
```

or something like that, datacube could actually report what was missing.

### Actual behaviour
Datacube splits out the dataset information back at me.

```
Indexing datasets  [####################################]  100%
2018-05-03 10:38:23,108 28698 datacube-dataset ERROR Unable to create Dataset for file:///g/data1a/u46/users/ia1511/Work/data/test-suite/output/LS8_PQ_COUNT_TIFF/LS8_PQ_COUNT_RAW_3577_20160101_20160401.yaml: No matching Product found for {
    "creation_dt": "2018-05-03T00:37:33.396168",
[... snipped some 2500 lines ...]
    "product_type": "pq_count_modified",
    "statistics": {
        "period": "3m",
        "step": "3m"
    }
}
```

### Environment information
* Which ``datacube --version`` are you using?
Open Data Cube core, version 1.6rc1
* What datacube deployment/environment are you running against?
DEA

**Comment by Kirill888** [comment]
Honestly `datacube dataset add` has a whole bunch of confusing options and bad names, `--source-policy` is particularly bad in my opinion, `--auto-match` and `--match-rules` aren't well understood. There is already `--dtype` (another bad name) which I think is exactly what your `--intended-product` is supposed to be.

**Comment by Kirill888** [comment]
After reading the code it seems that `--dtype` is really just "Auto-match using a subset of products" (you can supply several `--dtype`), while help message:

```
  -t, --dtype TEXT                Product to be associated with the datasets
```

communicates something very different, at least to me.

**Comment by hrithikc-ship-it** [comment]
Indexing datasets  [------------------------------------]    0%2025-02-25 10:26:09,689 7800 datacube-dataset ERROR No matching Product found for dataset a63f8fda-0952-4989-82ba-8842e7fccd3f
Indexing datasets  [####################################]  100%

what could be the issue for this error.i tried all the possible ways to get rid of the error.

**Comment by omad** [comment]
> Indexing datasets [------------------------------------] 0%2025-02-25 10:26:09,689 7800 datacube-dataset ERROR No matching Product found for dataset a63f8fda-0952-4989-82ba-8842e7fccd3f Indexing datasets [####################################] 100%
> 
> what could be the issue for this error.i tried all the possible ways to get rid of the error.

Hi @hrithikc-ship-it, can you post this as a new issue please, instead of a comment on an old closed issue.

It'd be helpful to include some extra context, what command you're running, an example of the data you're trying to index, and what you've tried to fix the issue.

Thanks!

**Comment by hrithikc-ship-it** [comment]
"0%2025-03-04 16:01:28,680 25596 datacube-dataset ERROR No matching Product found for dataset f6bdb74a-21d8-43e1-a207-8fb733b891b1" this is the error occured while i tried to add dataset.json file into open data cube using the command "datacube dataset add dataset.json"

dataset.json is given below 
"{
  "$schema": "https://schemas.opendatacube.org/dataset",
  "id": "11111111-1111-1111-1111-111111111111",
  "product": {
    "name": "test_product"
  },
  "crs": "EPSG:4326",
  "grids": {
    "default": {
      "shape": [100, 100],
      "transform": [0.1, 0.0, 0, 0.0, -0.1, 0, 0.0, 0.0, 1.0]
    }
  },
  "measurements": {
    "band1": {
      "path": "D:/icdas/lhasa/BH_RAF10JAN2024036801011200050SSANSTUC00GTDC/lhasa.tif",
      "dtype": "int16",
      "nodata": -9999
    }
  },
  "properties": {
    "datetime": "2024-01-01T00:00:00Z",
    "odc:file_format": "GeoTIFF"
  },
  "lineage": {}
}"
product.json is give below
"{

  "name": "test_product",

  "description": "A minimal test product",

  "license": "CC-BY-4.0",

  "metadata_type": "eo3",

  "metadata": {

    "product": {

      "name": "test_product"

    },

    "platform": {

      "code": "TESTPLATFORM"

    },

    "instrument": {

      "name": "TESTINSTRUMENT"

    },

    "format": "GeoTIFF",

    "lineage": {}

  },

  "storage": {

    "crs": "EPSG:4326",

    "resolution": {

      "x": 0.1,

      "y": -0.1

    },

    "tile_size": {

      "x": 100,

      "y": 100

    }

  },

  "measurements": [

    {

      "name": "band1",

      "dtype": "int16",

      "nodata": -9999,

      "units": "DN"

    }

  ]

}

 "

**Comment by SpacemanPaul** [comment]
Your product contains metadata for platform and instrument but the dataset does not - the dataset metadata must be a superset of the matching product.  All metadata specified in the product document must exactly match metadata in all datasets belonging to that product.

For more information about the EO3 metadata standard, refer to the formal definitions in https://github.com/opendatacube/eo3 ,  specifically:

https://github.com/opendatacube/eo3/blob/develop/SPECIFICATION-odc-product.md
and
https://github.com/opendatacube/eo3/blob/develop/SPECIFICATION.md

**Comment by hrithikc-ship-it** [comment]
Can u give me any YouTube video link to refer this
