### ISSUE TITLE
Analytics Expression Language.

### ISSUE THREAD

**Issue by petewa** [opendatacube/datacube-core#45]
Analytics Expression Language - a intuitive language for performing analytics.

**Comment by daleroberts** [comment]
If you are interested, this is how I do things:

https://gist.github.com/daleroberts/75cb0f0d5a77bedc28cf

**Comment by petewa** [comment]
Thanks Dale I'll take a look at it.

Closing this.

First version of the AEL is located here https://github.com/data-cube/agdc-v2/tree/develop/datacube/ndexpr

It provides the ground work for for feedback and further improvements.
