### ISSUE TITLE
Dataset add `sources_policy` is confusing and should be split into two options

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#451]
I'm talking about this one:

https://github.com/opendatacube/datacube-core/blob/b253bbc074a9f50e8153bae921d4dca7b23797a1/datacube/index/_datasets.py#L102-L116

First off, `verify` and `ensure` are way too similar in normal language use. Also `verify` implies a kind of "read-only" action: *check everything is fine, but don't change a thing*. Even documentation linked above implies that much. But that's not what's happening.

Both `ensure` and `verify` insert new datasets into the database from the lineage sources. The real difference between them is the level of verification two of them perform. One of them just checks presence of uuids in the database (if missing it will add it to the DB), the other one checks uuids as well as metadata documents. Which does what? I can never remember, but here is code for you to read:

https://github.com/opendatacube/datacube-core/blob/b253bbc074a9f50e8153bae921d4dca7b23797a1/datacube/index/_datasets.py#L186-L192

And then `skip`, is the only one that doesn't insert new datasets from the lineage, but otherwise performs a most complete check of consistency of lineage datasets.

### Proposed interface

There are really two axis here

1. What to do when lineage datasets are missing from DB
    - Add them to the database (current default action, `verify` and `ensure`)
    - Abort processing of the input dataset (`skip`)
2. What level of verification to apply to lineage datasets that are already in the DB
    - None (I think that's what `ensure` does)
    - Full check that lineage dataset is exactly the same as in DB (`skip` and `verify` do that)

So this all quite confusing, but worst of all we bubble up that confusion all the way to the end-user, have a look at `datacube dataset add --help` output, I won't be pasting it here.

**Comment by uchchwhash** [comment]
While you are at it, seems like @harshurampur needs https://github.com/opendatacube/datacube-core/issues/398 too.

**Comment by Kirill888** [comment]
@uchchwhash not sure I would do it at this level, wholesale lineage rejection is a useful "app-level" feature we should have as part of `datacube dataset add`, and it's trivial to add at the app level, just remove `lineage` subtree from the datasets as they are being parsed. In fact I would say that it should probably be a feature at the dataset generation level as well: *"don't record lineage for these datasets, I'm still experimenting and this not a final run of the algorithm, I don't won't to deal and pay in time and effort for all this lineage management, just yet"*

This is index API level and at this point having an option like *"just ignore missing lineage datasets and proceed like nothing happened"* is not ideal.

But in general I agree that we need to have a serious discussion about lineage management options for summary datasets, as it gets quite unwieldy in that case. Also cross datacube data movement is made practically impossible because of the way we deal with lineage.

**Comment by uchchwhash** [comment]
I understand your concerns, but from the users' perspective the option to opt out of the lineage record keeping (and thus indexing the parents if they are not there) could be (and probably is) valuable on its own.

**Comment by Kirill888** [comment]
Users should not be calling `datacube.index._dataset.add` directly, and we do not expose indexing apis to "users" other than via command line/ui tools, as far as I know off, there is only talk about "datacube save" which would be a high-level user-facing api for indexing.

`datacube dataset add` will get `--ignore-lineage` option that will prompt the user if they are sure or will abort with error message if not running interactively, and `--confirm-ignore-lineage` for scripts.

**Comment by uchchwhash** [comment]
:+1: thanks.
