### ISSUE TITLE
Stacker: `check_data_identical=True` fails to load generated file 

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#455]
Not sure if this a new issue after introducing fixes for #454, or due  to changes in dask, or existed before.

Basically we are not able to load data from the newly created file while stacker is still running, actual file is alright after stacker process finishes, my guess is that something is holding up netcdf file from being fully closed

Error occurs here:

https://github.com/opendatacube/datacube-core/blob/a256de335d19d32abfd740f4ee3a9fddbda77066/datacube_apps/stacker/stacker.py#L171

Even though we have already closed the file (and even renamed it to final destination name)

https://github.com/opendatacube/datacube-core/blob/a256de335d19d32abfd740f4ee3a9fddbda77066/datacube_apps/stacker/stacker.py#L164-L167

File is not accessible to external tools at this point either, calling something like `ncdump -h` on the file while paused in debugger generates output like this:

```
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 140735772541824:
  #000: H5F.c line 586 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1305 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1839 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 940 in H5FD_sec2_lock(): unable to lock file, errno = 35, error message = 'Resource temporarily unavailable'                         
    major: File accessibilty
    minor: Bad file ID accessed
```

This strongly suggests that `nco.close()` doesn't fully close the file at this point, probably because of some references still being kept around, probably within `dask`.

**Comment by alexgleith** [comment]
This looks like a pretty complex issue to reproduce... I guess we need to keep it open though, as it's valid still.

**Comment by Kirill888** [comment]
@alexgleith problem happens every time, just run stacker with the check eneabled, so no issue with reproducibility. Difficult to diagnose though, is the problem inside netcdf lib or the way we use it, or interactions with gdal/h5py?
