### ISSUE TITLE
Generate affine for xarray dataset/dataarray on-the-fly

### ISSUE THREAD

**Issue by BexDunn** [opendatacube/datacube-core#458]
### Expected behaviour
can generate an affine for an  xarray dataset/array on-the-fly (for a datacube dataset, that has had a bunch of things done to it but probably retains original properties)
### Actual behaviour
affine drops off the dataset/array if keep_attrs=True is not maintained the whole way down

...would be nice to regenerate in order to write tif or nc files

**Comment by Kirill888** [comment]
@BexDunn `.affine` is already a dynamic property (always was), but it only applies if `.crs` attribute is present, just copying `.crs` attribute from source should be sufficient to get `.affine` and `.geobox` to work on the derived dataset.  So just doing `derived.attrs['crs'] = src.crs` should be enough to enable `derived.affine` property. You might have to do that for every data variable that you want to use `.affine` on.
