### ISSUE TITLE
Question : How scalability is ensured by ODC ?

### ISSUE THREAD

**Issue by carguel** [opendatacube/datacube-core#459]
Quickly looking at the documentation, it is not clear for me how ODC supports some kind of scalability ?

Could the ODC take advantage of a multi-node infrastructure in order to distribute computations and data accesses on available nodes ?

Thanks for your reply.

**Comment by alexgleith** [comment]
Hey @carguel, I'm going to close this issue as it hasn't had any input for quite a long time.

For future reference, the ODC can be used in a number of ways that means that it can scale horizontally. For example, the ODC integrates well with Dask, for example, see [here](https://github.com/opendatacube/datacube-conference-2019/tree/master/dask_implementation).

And it can be deployed as an OGC Web Services stack, using Docker and Kubernetes to have hundreds of workers, see [here](https://github.com/opendatacube/datacube-ows/).
