### ISSUE TITLE
Distributed ingestion error

### ISSUE THREAD

**Issue by loicdtx** [opendatacube/datacube-core#462]
I'm trying to ingest large amounts of Landsat 8 data into a datacube using the distributed executor of the `datacube ingest` command. The cluster we've set-up has 6 workers and each worker has 4 threads (I suspect the multithreading is what causes the issue).
Starting the ingestion, a few files get ingested, but all subsequent tasks fail with the following error message:

```
2018-05-25 22:28:47,423 29910 datacube-ingest ERROR Task failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/datacube/scripts/ingest.py", line 292, in process_tasks
    executor.result(future)
  File "/usr/local/lib/python3.5/dist-packages/datacube/executor.py", line 135, in result
    return future.result()
  File "/usr/local/lib/python3.5/dist-packages/distributed/client.py", line 171, in result
    six.reraise(*result)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/datacube/scripts/ingest.py", line 210, in ingest_work
    raise ValueError('Something went wrong: no longer can find driver pointed by storage.driver option')
ValueError: Something went wrong: no longer can find driver pointed by storage.driver option
```

Here's the exact command used:
```
datacube ingest -c ~/.config/madmex/ingestion/ls8_espa_mexico.yaml --executor distributed 10.0.2.49:8786
```

The [ingestion file](https://github.com/CONABIO/antares3/blob/develop/madmex/conf/ingestion/ls8_espa_mexico.yaml)

Using datacube 1.6rc1

**Comment by Kirill888** [comment]
@loicdtx we use GDAL (via rasterio) to read netcdf files and Netcdf4 to write them. Both of these libraries use HDF5 library under the hood. HDF5 library is not thread safe, not at all. GDAL and netcdf4 might or might not introduce guards when accessing HDF5, to be safe assume that they don't.

Can you please configure dask to not use threads, only processes, if the error persists, will look into it further then.

**Comment by Kirill888** [comment]
Also you need to make sure that "dask side" has the same python environment, with the same datacube.

**Comment by loicdtx** [comment]
Sounds good, I'll stick to one thread per process :-)
My reason for trying to give more threads to the processes was that I saw processes using more than 100% cpu when ingesting with the cloudpickle executor. One of the steps of the ingestion has internal multithreading; not sure which one. I was betting on `rasterio.reproject` but did not find any evidence of that...
Anyway, thanks for your response, single threaded processes works great!

**Comment by Kirill888** [comment]
If you are not running on a cluster, there is also `--executor multiproc 16` which will use multiprocessing to run 16 processes concurrently, you  might want to try that.

GDAL might very well have some internal threads for re-projecting, I don't think multi-threaded reproject is enabled by default though.

**Comment by Kirill888** [comment]
Looks like threading of third-party libs, closing this, but we do need better management of threading+HDF5.
