### ISSUE TITLE
Propose new location management feature for `datacube update`

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#465]
Currently if you make a copy of ingested file and then call `datacube update <copied-file>` new location for all datasets present in this file (and also in the database) will be added to the index. Previous location will still be present, i.e. `dataset.uris` will become `[new_uri, old_uri]`.

I propose we add an option to archive or forget completely old location, something like

```
--previous-location [keep|archive|forget]
                       What to do with previously recorded dataset location
                       'keep'    -- no change, keep as alternative location [default]
                       'archive' -- mark as archived
                       'forget'  -- remove from the index
``` 

This can then be used to update locations of stacked datasets on NCI with `forget` option.

`archive` and `forget` should probably error out if there is more than 1 active location.

**Comment by mpaget** [comment]
I appreciate verboseness but I suggest '--location' may be sufficient, which may allow this parameter to be used more generically in update. In a sense, 'update' already implies a 'previous'. Consistency across the other datacube * functions needs to be considered, as appears to be happening with related issues/fixes.

Aside from 'semantics', I think this (and related recent fixes) will be a really valuable contribution to easier (transparent) data management tools. Happy to help and test.

**Comment by Kirill888** [comment]
@mpaget the issue I have with just `--location` is that I would expect it to be followed by a file system path or a URL, not a multiple-choice option. How about `--location-policy`? So that can not be confused with `location as path`.

I realise `previous` is hard to spell correctly.

**Comment by Kirill888** [comment]
Now that I think about it `--previous-location` kinda also implies `location as path`, I think `--location-policy` is less ambiguous.

**Comment by mpaget** [comment]
Fair point on path. Yes, something like that .. particularly if --*policy* is used elsewhere in the datacube * functions where multiple-choice options appear.
I like the consistency drive that you appear to already be on, so just seeing an opportunity to support that.
--location-choice ?? probably not. 'policy' is good.
thesaurus options: action, method, rule

**Comment by Kirill888** [comment]
We do you use `policy` in `datacube dataset add`, although I do want that option gone.

**Comment by mpaget** [comment]
semantics and word perspectives.. :)
`policy` implies something formal, which may have a perception of 'management' (set in stone) rather than 'maintenance' (can be changed).
`action` implies something dynamic; your choice will make something happen.
`method` implies something more generic across contexts.
`rule` implies something less generic that could be confusing across contexts.
I kinda like `action`.
