### ISSUE TITLE
`datacube product list` and `datacube product show` do very similar thing

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#494]
Default behaviour of `datacube product list` is to **show** all products in yaml format. I would expect to see just a list of product names.

`product list` with `-f tab|csv` works a little bit better for seeing list of all products, but still not ideal as lines are very long, not sure who is the intended audience for that.

One really has to do `datacube product list | grep name:` to get an idea about a **list** of products.

`datacube product show` without product name doesn't work at all, it would make more sense to have this command dump all product YAMLs instead of `datacube product list`

**Comment by Kirill888** [comment]
What's even worse output of `product list` is not even compatible with `product add` since it includes `id` field which is specific to a particular DB and is not a property user enters via product yaml.

`product show` doesn't have that problem.

**Comment by loicdtx** [comment]
I agree, I use the `datacube product list` command a lot and I very much preferred the formatting in version `1.5.5`

**Comment by Kirill888** [comment]
Seems to have been addressed by this commit:

https://github.com/opendatacube/datacube-core/commit/fd5d0124fad8d95369723148a65805a0975c4439
