### ISSUE TITLE
_gdfnetcdf.py - NetCDF - SetAttributes failed

### ISSUE THREAD

**Issue by didierearith** [opendatacube/datacube-core#5]
Dear Team,

In _gdfnetcdf.py, function georeference_from_file failed because of invalid (?) attribute name 'name' in crs_metadata

...
        crs_metadata = {'crs:name': spatial_reference.GetAttrValue('geogcs'),
                    'crs:longitude_of_prime_meridian': 0.0, #TODO: This needs to be fixed!!! An OSR object should have this, but maybe only for specific OSR references??
                    'crs:inverse_flattening': spatial_reference.GetInvFlattening(),
                    'crs:semi_major_axis': spatial_reference.GetSemiMajor(),
                    'crs:semi_minor_axis': spatial_reference.GetSemiMinor(),
                    }
        self.set_variable('crs', dims=(), dtype='i4')
        self.set_attributes(crs_metadata)
...

Exception raised while processing storage unit (2015, -28, 111): 'name' is one of the reserved attributes ('_grpid', '_grp', '_varid', 'groups', 'dimensions', 'variables', 'dtype', 'data_model', 'disk_format', '_nunlimdim', 'path', 'parent', 'ndim', 'mask', 'scale', 'cmptypes', 'vltypes', '_isprimitive', 'file_format', '_isvlen', '_iscompound', '_cmptype', '_vltype', 'name', '__orthogoral_indexing__', 'keepweakref'), cannot rebind. Use setncattr instead.

I replaced 
 crs_metadata = {'crs:name': spatial_reference.GetAttrValue('geogcs'),
by
 crs_metadata = {'crs:standard_name': spatial_reference.GetAttrValue('geogcs'), 
or 
 crs_metadata = {'crs:long_name_name': spatial_reference.GetAttrValue('geogcs'), 

as a workaround

Kind regards,

**Comment by omad** [comment]
Closing. GDF has been deprecated.
