### ISSUE TITLE
Proposal: Extend Measurements class to add base_attrs method

### ISSUE THREAD

**Issue by snowman2** [opendatacube/datacube-core#500]
What are your thoughts on extending the [Measurements class](https://github.com/opendatacube/datacube-core/blob/develop/datacube/model/__init__.py#L314-L328) to have a `base_attrs()` method that could replace functionality [here](https://github.com/opendatacube/datacube-core/blob/develop/datacube/api/core.py#L443-L454)?

Then, it could be dropped in the [measurements property](https://github.com/opendatacube/datacube-core/blob/develop/datacube/model/__init__.py#L414-L420) of the DatasetType.

**Comment by alfredoahds** [comment]
Just for some context, we've created an index class that maps existing internal data structures to Data Cube models. This change would allow users that use a custom index to subclass `Measurement` and include custom fields that would be added to output Datasets without additional changes.

**Comment by snowman2** [comment]
Could address the measurements part of issue #188

**Comment by snowman2** [comment]
Another iteration could use the `@schema_validated` decorator with validation in measurement-schema.yaml and inherit from the dict class.

**Comment by uchchwhash** [comment]
Thanks for the report. This has been on our list of things to do for a while, great to know somebody else has a use-case for it. The `datacube.model.Measurement` class was added later and although it seems reasonable to update our code making use of that class, we still have do not have a clear idea of how much of user code that would break. But it is definitely worth doing IMHO.
