### ISSUE TITLE
write_geotiff helper function fails if CRS is string, not object

### ISSUE THREAD

**Issue by CEKrause** [opendatacube/datacube-core#501]
### Expected behaviour
The write_geotiff helper function assumes that you will pass the function a datacube crs object. If you are writing out a geotiff from data that was not loaded using `dc.load`, this crs object is not present. 
E.g. I read a Geotiff file produced by datacube-stats into a Notebook, ran some analysis on it, and wanted to write it back out to Geotiff. I have a crs string from the attributes of my original Geotiff, but no datacube crs object, so the write_geotiff function fails.

### Error
```
AttributeError                            Traceback (most recent call last)
<ipython-input-41-736bab55bae5> in <module>()
      3 Differenceds.attrs['crs'] = (GeotiffData.crs)
      4 
----> 5 write_geotiff(PercentileConfidence, Differenceds)

/g/data/v10/public/modules/dea/20180515/lib/python3.6/site-packages/datacube/helpers.py in write_geotiff(filename, dataset, profile_override, time_index)
     44     profile = DEFAULT_PROFILE.copy()
     45     profile.update({
---> 46         'width': dataset.dims[dataset.crs.dimensions[1]],
     47         'height': dataset.dims[dataset.crs.dimensions[0]],
     48         'transform': dataset.affine,

AttributeError: 'str' object has no attribute 'dimensions'
```

**Comment by uchchwhash** [comment]
Would
```python
from datacube.utils.geometry import CRS

Differenceds.attrs['crs'] = CRS(GeotiffData.crs)
write_geotiff(PercentileConfidence, Differenceds)
```
solve your problem?

**Comment by CEKrause** [comment]
Yes, that's how I have gotten around it. 

It would be really useful if the write_geotiff function was able to handle either the datacube crs object, or a crs string and generate its own on the fly, rather than fail.
