### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by snowman2** [opendatacube/datacube-core#506]
https://github.com/opendatacube/datacube-core/blob/67024189d138172a234aabedf49c836cde774d5e/setup.py#L99-L109

With the release of rasterio 1.0, can the pin be updated to `rasterio~=1.0`?
Also, since Python 2 support is dropped, should `futures` and `pathlib` be removed?

**Comment by omad** [comment]
Those all sound like good ideas to me.

**Comment by omad** [comment]
Thanks!
