### ISSUE TITLE
Release 1.5.5

### ISSUE THREAD

**Issue by snowman2** [opendatacube/datacube-core#507]
Is it possible to release 1.5.5 with the dependency fixes in the requirements to pypi/conda-forge? We are having issues with pathlib in 1.5.4 in random instances and hope that this will fix it.

**Comment by snowman2** [comment]
Here is a PR for conda-forge https://github.com/conda-forge/datacube-feedstock/pull/8.

**Comment by omad** [comment]
Absolutely. The release process is always a work in progress.

PR merged, so 1.5.5 with fixed deps should be available from `conda-forge` soon.

Thanks very much for the PR, makes it super easy for me. 👍

**Comment by snowman2** [comment]
Thanks!
