### ISSUE TITLE
Stack trace printout when system is not configured

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#517]
### Expected behaviour

Expect to see some helpful message

### Actual behaviour

See `ValueError` stack trace
```
Traceback (most recent call last):
  File "/usr/local/bin/datacube", line 11, in <module>
    load_entry_point('datacube==1.6rc2+83.gc2d0ac22', 'console_scripts', 'datacube')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/datacube/ui/click.py", line 190, in new_func
    parsed_config = config.LocalConfig.find(paths=paths, env=specific_environment)
  File "/usr/local/lib/python3.6/dist-packages/datacube/config.py", line 116, in find
    env=env,
  File "/usr/local/lib/python3.6/dist-packages/datacube/config.py", line 94, in __init__
    raise ValueError('No ODC environment, checked configurations for %s' % fallbacks)
ValueError: No ODC environment, checked configurations for ['default', 'datacube']
```

### Steps to reproduce the behaviour

Run `datacube system check` in the environment where there is no `~/.datacube.conf` and no `/etc/datacube.conf` and `DATACUBE_CONFIG_PATH` is not set.

Exception is raised from `LocalConfig` constructor and is not caught by adapter helper in `datacube.ui.click`

- Thrown here: https://github.com/opendatacube/datacube-core/blob/1d998b85d9fadcba098748340d5566fd5c461463/datacube/config.py#L94
- Not caught here: `pass_context` decorator https://github.com/opendatacube/datacube-core/blob/1d998b85d9fadcba098748340d5566fd5c461463/datacube/ui/click.py#L190

Similar issues with `pass_index` decorator, if there are exceptions they should be caught and converted to proper termination via `click` library *"abort with error message mechanisms"*.

### Environment information

This is `develop` on Ubuntu 18.04, but really anywhere will trigger the same error, and problem applies to older versions probably also.

**Comment by jcrattz** [comment]
So we'll need to check if the configuration file exists, and if it doesn't, inform the user (also linking to the [documentation on the config file](https://datacube-core.readthedocs.io/en/datacube-1.4.1/ops/db_setup.html#create-configuration-file)?) but is there anything else about this that we should know (common error cases other than the config not existing where expected)?

**Comment by omad** [comment]
I think the main error is when no configuration file exists. I believe there are already reasonable error messages printed for things like the database not being initialised, or not being able to connect to the database.

The change @Kirill888 mentioned in the Zoom about configuration via environment variables alone will impact this, but, can be dealt with later.

**Comment by jcrattz** [comment]
So is it OK for me to work on this, or should I work on something else?

**Comment by omad** [comment]
Go for it!

**Comment by Kirill888** [comment]
I can add config from ENV in a way that should not interfere with your work @jcrattz, I'll start with just copying functions for parsing that, we can plug it in later.
