### ISSUE TITLE
Ingesting with executor multiproc seems to just idle around

### ISSUE THREAD

**Issue by ikselven** [opendatacube/datacube-core#528]
### Expected behaviour
The ingester should ingest data when it is run with the option `--executor multiproc 2`.

### Actual behaviour
The ingester does not ingest data and is idling (i.e. no noticeable CPU load). The status message does not indicate any progress, it always says "completed 0, failed 0".

When the first 3 tasks are submitted, the following error is shown:
```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/cubeenv/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/user/anaconda3/envs/cubeenv/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
BufferError: could not get scalar buffer information
```
For all the other tasks, that are submitted, the error is not shown.

### Steps to reproduce the behaviour

```
$ datacube -v ingest -c "ingestion_config" --executor multiproc 2
```

The ingestion configuration I am using is derived from this [Landsat 8 example](https://github.com/ceos-seo/agdc-v2/blob/master/ingest/ingestion_configs/landsat_collection/ls8_collections_sr_lake_chad_example.yaml).

### Environment information

* Which ``datacube --version`` are you using?
```shell
$ datacube --version
Open Data Cube core, version 1.5.5
```
* What datacube deployment/environment are you running against?
Debian 9.5 with Anaconda3 5.2.0, conda 4.5.9, Python 3.6

### Additional Notes
When leaving out the executor argument, ingesting data works, however, it is slow.

Just a thought: Might it be possible, that some component is waiting here for some tasks to finish but these tasks will never finish because of an error?

Maybe I am just missing something, but reading the documentation, I cannot see, what is missing.

Edit: added Python version

**Comment by Kirill888** [comment]
@ikselven looks like something isn't picking well, either during task submission or when getting results back. We had a bunch of these pickling related issues in the past as well, sometimes some third party dependency changes and is no longer picklable, other times it's our code, but in un-expected place.

I found this issues that might be affecting  your setup:
https://github.com/numpy/numpy/issues/11656

But really it could be anything, but it's definitely pickling related.

**Comment by ikselven** [comment]
Unfortunately, at the moment, I am unable to test if numpy 1.14.* would make any difference. 

However, since conda has installed numpy 1.15.0 in my datacube's conda environment, it is likely that the issue you mentioned might just be what's causing the trouble.

**Comment by Kirill888** [comment]
If you can just try the snippet in the issue linked above

```

**Comment by Kirill888** [comment]
Can you check if the snippet in the issue linked above causes problems in your setup:

```python
import pickle
import numpy as np
pickle.dumps(np.datetime64('2016-01-01T00:00:00.000000000'))
```

**Comment by ikselven** [comment]
Yes, I can reproduce the error with that snippet.

**Comment by adaag** [comment]
```python
def parallel_apply(data, fun, args):
    pool = mp.Pool(mp.cpu_count() - 1)
    result = [pool.apply(fun, (data.loc[x, :], *args)) for x in data.index]
    result = [p.get() for p in result]
    end_result = pd.concat(result)
    return end_result
```
From this part of code i also get "BufferError: could not get scalar buffer information", I've tried to solve it, but it seems like there is a bug. i really appreciate your help. Thanks

**Comment by Kirill888** [comment]
@adaag you will have to down-grade `numpy` to previous release, or wait until pickling regression is fixed in `numpy` and a new version is available.

**Comment by ikselven** [comment]
Closing this issue, as ingesting with `--executor multiproc 2` works fine again.
