### ISSUE TITLE
No way to create `MetadataType` without database connection

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#529]
In order to construct `MetadataType` object from yaml definition one has to have access to connected db index. No information is queried from the DB during construction. It's just that `doc->MetadataType` conversion is part of the index api attached to an `index` object

```python
m = dc.index.metadata_types.from_doc(doc)
```

`MetadataType` class is just a container of "dataset search fields", the type of the search fields will be different for different index implementations, but there is nothing that depends on the state stored inside the db. 

I propose that 

- Database index driver should expose constructor method for `MetadataType`
- We should have "dataset search fields" implementation that is not tied to any DB driver

If I have "metadata definition yaml" and "dataset yaml" I should be able to parse "dataset yaml" according to "metadata definition yaml" without connecting to the database, and even without deciding what db index should be used.

I believe this limitation is impacting testing in a negative way, a lot of the tests that could have been "unit tests" are now forced into "integration test" category, and integration tests are harder to write and are slower to run.

**Comment by omad** [comment]
Wow, I didn't realise this was the case. Having an offline way of combining those documents would be a big help for testing!

**Comment by Kirill888** [comment]
It's not "impossible" as such, you can create index with dummy config and `validate_connection=False`, and then call `index.metadata_types.from_doc({..})` and you will get `MetadataType` without `db engine` ever trying to connect to non-existent db, but you know, that's not ideal.

The whole approach to "index api" with those `{Dataset|Product|User|MetadataType}Resource` classes kind assumes that you create an `index` object, which then create `{XX}Resource` objects makes it rather hard to have "static" methods exposed.
