### ISSUE TITLE
Proposal: Support loading in multiple datasets with np.nan as the nodata value.

### ISSUE THREAD

**Issue by snowman2** [opendatacube/datacube-core#530]
Currently, we have run into instances where netCDF files have a nodata/_FillValue value of NaN (strange, but it happened). The current code in odc does not correctly search for the location of nodata  in the case of a NaN value (https://github.com/opendatacube/datacube-core/blob/develop/datacube/storage/storage.py#L195, and https://github.com/opendatacube/datacube-core/blob/develop/datacube/storage/storage.py#L162). It is a simple fix to use `numpy.isnan` to support this. 

We have developed a fix for this, would you be interested in a PR?

**Comment by Kirill888** [comment]
Thanks @snowman2 we should certainly handle `nodata` being `NaN` case correctly. Do make a PR with your fix, thanks.

We might have to add more tests for this case.
