### ISSUE TITLE
Issues with file line endings & git

### ISSUE THREAD

**Issue by snowman2** [opendatacube/datacube-core#532]
### Behaviour

After cloning the repository and some minor activity with git, I have issues with:
`docs/config_samples/dataset_types/ls_usgs_sr_scene.yaml`

```
$ git status
On branch nodata_nan_fix
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   docs/config_samples/dataset_types/ls_usgs_sr_scene.yaml

no changes added to commit (use "git add" and/or "git commit -a")
```

When I run:
```
git stash
```
or 
```
git checkout docs/config_samples/dataset_types/ls_usgs_sr_scene.yaml
```
Nothing happens. This makes rebasing difficult as I have to commit the changed file and then rebase to remove the commit while doing other changes.

### Proposed solution
Change from CRLF -> LF.

**Comment by Kirill888** [comment]
@snowman2 just for your information, we are in the process of moving sample configs and prepare scripts to this repo https://github.com/opendatacube/datacube-dataset-config/ 

We started with that specific product, and there are some updates in the new repo.

**Comment by snowman2** [comment]
Okay, sounds good. I will close this issue then.
