### ISSUE TITLE
Propose to add new field to eo metadata

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#536]
Many (most?) data sources have  some structure to the way they capture data. Typically there is some sort of spatial partitioning, there is a finite set of regions and they get observed with some regularity. A footprint of any dataset is not completely arbitrary or unique. There often exists a "native" spatial binning, several datasets, captured at different times but covering the same "region" might not have exactly the same footprint, but they will have a "significant" overlap, and are likely to share the same projection.  

In case of Landsat that region is a "scene path,row", in case of ingested products on NCI it's Albers tile, for Sentinel it's MGRS code.

I think it is worthwhile to keep that "native spatial grouping" information, and I think it's generic enough to justify adding it to the default metadata type `eo`.

Possible names:

- `region_code`  
- `regioncode` (like postcode)
- `region_id`
- `spatial_group_id`

We won't promise much: 

- Uniquely identifies some spatial region
- Datasets with the same `region_code` cover roughly the same area
- There is a finite set of spatial regions (much less than number of datasets in the collection)
- No interpretation of `region_code`, no spatial info of any kind, just an opaque label
- No spatial "ordering"

This would allow grouping of datasets based on "collection specific" spatial relations, this could be useful for certain types of processing.

**Comment by omad** [comment]
I like the sound of this.

I'm not sure about a name... I'll think about it.

It should help with querying for bulk processing.
