### ISSUE TITLE
Need better error reporting when constructing `GridSpec`

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#556]
### Expected behaviour

Meaningful error message when user supplies `GridSpec` document with missing/misspelled information.

### Actual behaviour

Code raises `KeyError: latitude`

### Steps to reproduce the behaviour

Mismatched `x,y` vs `longitude,latitude` in either `tile_size`, `resolution`, `origin` (reported on Slack, supplying `x,y` for `EPSG:4326` CRS).

### Where

Code here should first check if correctly named keys are present and throw some `Datacube` error if not:

https://github.com/opendatacube/datacube-core/blob/a82de5c031d711043b5dedbb09b609de0d544a4f/datacube/model/__init__.py#L491-L493

**Comment by omad** [comment]
The plan is to deprecate `GridSpec` in v1.9 and remove it in v2, so this will no longer be relevant. Any errors will be via [opendatacube/odc-geo: GeoBox and geometry utilities extracted from datacube-core](https://github.com/opendatacube/odc-geo/).
