### ISSUE TITLE
Datacube uses reproject instead of "scaling reads" when reading at reduced resolution

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#563]
Underlying IO driver interface allows "scaling reads"

```python
 def read(self, window=None, out_shape=None):
```

one can supply both the ROI (region of interest, `window`) in the native projection/scale to read and also the shape of the output `out_shape`. The idea is to allow use of pre-computed overview images when reading data at 1/2,1/4... scales.

> NOTE: resampling strategy is decided at the time of building of overviews, and if they are missing GDAL defaults to nearest neighbour resampling. Older versions of GDAL didn't allow resampling with any other methods, but since 2.0 one can supply resampling policy other than NN.

Current implementation of `read_from_source` however only calls `io_drivers.read` when the read scale is `1:1` (this was not always the case)

https://github.com/opendatacube/datacube-core/blob/26e2fe5bae36966eb17c3770c521e52df0b538e6/datacube/storage/storage.py#L149-L151

I believe the change happened in response to errors in `_read_native` (previously `_decimated_read`) when dealing with scaled outputs.

`_read_native` logic is fairly involved, lot's of dense code without sufficient documentation (which way is scale/offset, `in->out` or `out->in`?) There are also no unit-tests that test this functionality directly.

https://github.com/opendatacube/datacube-core/blob/26e2fe5bae36966eb17c3770c521e52df0b538e6/datacube/storage/storage.py#L82-L128

Ultimately it's all about figuring out what region of input image to read at what scale and where to put in the output pixel plane. Section of code linked above needs to be re-written with unit tests calling `_read_native` directly and verifying produced image data is correct.

We should also consider augmenting IO driver interface for read with "resampling strategy" parameter so that when `out_shape != shape(window)` appropriate resampling can be used.

**Comment by Kirill888** [comment]
Looks like code always had `_no_scale` check in there, which is weird given that the rest of the code doesn't make assumptions about input/output shapes being the same.

**Comment by omad** [comment]
Perhaps it was originally for `unscaled` reads, and was in the process of being extended to work for scaling as well...

**Comment by Kirill888** [comment]
I'm also not too sure about axis flipping logic being correct, particularly when both sx,sy are negative.

**Comment by Kirill888** [comment]
Was addressed in #611
