### ISSUE TITLE
Incomplete Ingestion Runs

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#574]
### Expected behaviour
When running `ingest` on a large job, it should output *all* of the expected tiles.

### Actual behaviour
Ingest completes up to the `--queue-size` number of tiles.

### Environment information

* Which ``datacube --version`` are you using?
1.6.1
* What datacube deployment/enviornment are you running against?
DEA NCI. Anywhere.

**Comment by Kirill888** [comment]
Broke here: 0afd9e8769995e5a491b2282f9e27b0487807120

**Comment by Kirill888** [comment]
https://github.com/opendatacube/datacube-core/pull/515

**Comment by omad** [comment]
Can you please have a look at this @santoshamohan, Kirill has pointed out exactly where the breakage happened.

Thanks

**Comment by santoshamohan** [comment]
Sure Damien, I will have a look at it.
