### ISSUE TITLE
Write dataset metadata to storage unit

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#58]
Include the dataset config within the storage unit

**Comment by v0lat1le** [comment]
You mean the dataset metadata document (as per Jeremy's terminology doc) I assume...

**Comment by v0lat1le** [comment]
In case multiple datasets contribute to the same time slice (e.g. Sentinel 2 data) all documents should be stored. Multi-document yaml format could be used for that

**Comment by omad** [comment]
- A YAML serialisation of the dataset metadata is saved into an `extra_metadata` variable in the NetCDF Storage Units. This variable is along the time coordinate, with a dataset metadata per time.
- If multiple datasets are being merged, metadata from each dataset is concatenated into a multi-document YAML.
- _Unfortunately the CF-Conventions don't allow string variables, so I'm using a fixed length character array._
