### ISSUE TITLE
Issue with time based datacube query using months as a query range

### ISSUE THREAD

**Issue by santoshamohan** [opendatacube/datacube-core#585]
### Expected behaviour
Product search using `datacube dataset search` command based on `time` range between months should yield a range between the beginning of the month to the end of the month.

Ex. query using time range `2018-02 < time < 2018-03` is expected to result in a range,
```Range(begin=datetime.datetime(2018, 2, 1, 0, 0, tzinfo=<UTC>), end=datetime.datetime(2018, 3, 31, 23, 59, 59, 999999, tzinfo=tzutc()))```

### Actual behaviour
The query range selected is as follows:
```Range(begin=datetime.datetime(2018, 2, 1, 0, 0, tzinfo=<UTC>), end=datetime.datetime(2018, 3, 1, 23, 59, 59, 999999, tzinfo=tzutc()))```

### Steps to reproduce the behaviour
1) Load latest dea module (dea/20181015)
2) Run the following command:
`datacube dataset search product=ls5_nbar_albers '2010-01 < time < 2010-02' | grep "time: {" | sort`

### Environment information
* ``datacube --version``: 1.6.1+72.gdfc6b47a
* ``dea module``: dea/20181015

**Comment by uchchwhash** [comment]
The resolution we settled for is don't use `2018-02 < time < 2018-03`, use `time in [2018-02, 2018-03]` instead, and expect `dc.load` semantics.

Closing.
