### ISSUE TITLE
GetDescriptor to return timestamps

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#60]

**Comment by andrewdhicks** [comment]
Update API.get_descriptor to include the 'irregular_indices' property, ideally without opening files to read the data.  The only irregular dimension we currently have in datasets is time.  (This will be hard-coded in the API until an 'irregular' flag for the dimension can be passed along from other layers.

The acquisition timestamps are stored in relation to the dataset, which can be linked back to from the storage unit. This is not an ideal mapping.
Alternatively, we can open a file for each section of the dimension and return the list of indices.

**Comment by andrewdhicks** [comment]
The API.get_descriptor 'irregular_indices' property now uses the time coordinates stored in the NetCDF files for irregular time dimension, for files with more than 2 slices (it uses the database for the min and max times where possible).
This is a stopgap solution until we determine what the use cases are irregular variables other than time.
