### ISSUE TITLE
Allow fuse function customisation per band

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#604]
Currently `fuse` can only be customized per `.load_data` call, but since `.load_data` is loading multiple-bands all bands will be fused with the same function. It is completely reasonable for different bands of the same product to be sufficiently different as to require a different fusing strategy. And since a ``fuse`` function doesn’t know which band it is processing it can not dispatch to different implementations internally.

We can use similar approach currently used to configure resampling per band (#551), which is to  accept a dictionary `dict: str -> fuser` instead of a single `None|fuser` parameter. Change can be made in a backwards compatible way.

This impacts collection upgrade since new product structure doesn't split PQ into a separate product, but instead includes `fmask` and `nbar` measurements in the same product, where `fmask` will need a custom fuser.

**Comment by omad** [comment]
This is important. I like the plan to follow an existing pattern in the `load` API.
