### ISSUE TITLE
NETCDF url construction is broken for files with ':' character in their name

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#608]
### Expected behaviour

Should be able to open Datasets that reference files like `"file_with_colon:in_the_name.nc"`

### Actual behaviour

Get error message from gdal (via rasterio)

### Steps to reproduce the behaviour

Index file with `:` in the name try to open it.

### Environment information

`dea/20181015` on NCI

### Solution

When constructing `NETCDF:${filepath}:band` file path part needs to be wrapped in quotes.

https://github.com/opendatacube/datacube-core/blob/c4ed2929f2bc70426687b87db95513a1eae302ff/datacube/storage/storage.py#L516-L521

middle `%s` should be in quotes

**Comment by mpaget** [comment]
What is the case for having a colon in a filename? It seems to me quite a non-standard file/data management scenario.

The wrapping in quotes, and the actual change in this PR, is fine.

**Comment by Kirill888** [comment]
@mpaget sometimes people dump timestamp into file name, often it contains `:`, but I agree best to avoid those characters.
