### ISSUE TITLE
https://github.com/data-cube/agdc-v2/blob/ga/milestone1/README.md out of date

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#61]
requirements.txt does not exist 
suggest supersede with readthedocs?

**Comment by omad** [comment]
This should be fixed up as part of the documentation overhaul.

The `invalid` label is normally used to mark the issue itself as invalid, not that there is something in the project that is invalid.

**Comment by jeremyh** [comment]
Updated to be more development focused, with a link to readthedocs for users.
