### ISSUE TITLE
make_dataset shouldn't generate random id

### ISSUE THREAD

**Issue by emmaai** [opendatacube/datacube-core#613]
### Expected behaviour
make_dataset should generate uuid according to some rules, which would enable tracing back to the data file(s)

### Actual behaviour
uuid is generated randomly, doesn't show any information about the data file(s).

**Comment by Kirill888** [comment]
`make_dataset` should allow customization of uuid generation through some mechanism:

https://github.com/opendatacube/datacube-core/blob/83bae20d2a2469a6417097168fd4ede37fd2abe5/datacube/model/utils.py#L184-L198

Currently random uuid is generated:

https://github.com/opendatacube/datacube-core/blob/83bae20d2a2469a6417097168fd4ede37fd2abe5/datacube/model/utils.py#L80-L84

We should not encourage random uuids (v4), instead we should use uuid v5 (namespace), using something like common prefix path as "name" part of uuid5.
