### ISSUE TITLE
Metadata name not included in Dataset object

### ISSUE THREAD

**Issue by jankovicgd** [opendatacube/datacube-core#627]
Other fields are included in `search_by_metadata()` return except name.

### Expected behaviour
Print the name of the dataset from the metadata searched by `search_by_metadata()`

### Actual behaviour
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-41-cd57dcc6e90c> in <module>()
      6 ds = lor[0]
      7 ds = ds.metadata
----> 8 ds.name

~/miniconda/envs/cubeenv2/lib/python3.6/site-packages/datacube/utils/__init__.py in __getattr__(self, name)
    748             raise AttributeError(
    749                 'Unknown field %r. Expected one of %r' % (
--> 750                     name, list(chain(self._system_offsets.keys(), self._search_fields.keys()))
    751                 )
    752             )

AttributeError: Unknown field 'name'. Expected one of ['id', 'label', 'format', 'sources', 'creation_dt', 'grid_spatial', 'measurements', 'creation_time', 'format', 'label', 'lat', 'lon', 'time', 'platform', 'instrument', 'product_type']
```

### Steps to reproduce the behaviour
```
generator = dc.index.datasets.search_by_metadata({'id':'17b31217-2187-4030-9f8e-37beea2baa06'})
results = []
for result in generator:
    results.append(result)
ds = results[0].metadata
ds.name
```
The query with name works and returns correct results
```
generator = dc.index.datasets.search_by_metadata({'name':'Sentinel2 Test'})
```

### Environment information

* Which ``datacube --version`` are you using? 1.6rc2+57.g0e4fe679
* What datacube deployment/enviornment are you running against? miniconda environment

**Comment by Kirill888** [comment]
@jankovicgd unfortunately behaviour you describe is "as intended", or at least "expected". Confusion comes from our abuse of a term "metadata". This term can refer to a lot of related but different things inside datacube code base. As a result writing meaningful unambiguous documentation is really hard, when everything is called metadata the term becomes meaningless. Imagine writing a short story with ten characters, but all have to be called Max, and you can't give them nicknames... This is the situation we find ourselves in with "metadata" and to some extent "dataset".

Anyway back to your problem:

In `search_by_metadata` method `metadata` refers to the entire `yaml` document of a dataset (`metadata_doc`). Obviously all searches are "by metadata", it's not like we support finding datasets based on pixel values. This one is more like: "search by raw metadata"

What it does is equivalent to the following `pseudo-python`: 

```python
# Find all datasets in the database that have this exact subtree as part of their definition.

query = {'name': 'blah', 'other': {'subtree': {'x': 10}}}
datasets = [ds for ds in all_datasets if ds.medata_doc.contains_exact_subtree(query)]
```

The `.metadata` property refers to a different "metadata" concept. This property only exposes "well known fields", essentially it flattens a subset of the metadata document into a named tuple of key value pairs where keys are strings and values are of a set of known types like date, number, range. What these named fields are is defined by `MetadataType`. In your case you use one of the pre-defined metadata types named "eo" (short for Earth Observation). All datasets under one product share the same `MetadataType`. It is possible to define your own `MetadataType` that would include field `name`, then you would be able to access it via `ds.metadata.name`, and to filter datasets based on that field: `dc.load(product='something', ..., name="that one")`, no need to use `search_by_metadata` in this case.

I think the original expectation was that people would define their own `MetadataType` a lot to allow more efficient queries for custom products, but that never happened, instead everyone just uses default "eo" `MetadataType`.

Anyway quick fix for your case:

```diff
generator = dc.index.datasets.search_by_metadata({'id':'17b31217-2187-4030-9f8e-37beea2baa06'})
results = []
for result in generator:
    results.append(result)
- ds = results[0].metadata
- ds.name
+ ds = results[0].metadata_doc
+ ds.get('name')
```

**Comment by jankovicgd** [comment]
Thanks for the broad answer and help. I will try it out. As far as I'm concerned you can close the issue :)
