### ISSUE TITLE
Remove Geometry Shim Classes from `datacube.model`

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#635]
There is some code from 2017 in `datacube/model/` that just prints warnings when somebody imports and instantiates various geometry objects, like `CRS`, from `datacube.model` instead of from `datacube.utils.geometry`

https://github.com/opendatacube/datacube-core/blob/f255a0529725ee6acb35e7619965746ab66ae83d/datacube/model/__init__.py#L37-L66

I think these classes ARE part of the Datacube model, except for maybe `Coordinate`, so we should just import them from wherever they are defined and not discourage people from importing them from the `model`. It shouldn't matter where they are defined, it makes perfect sense for external code to import them from the same place as `Dataset`.

**Comment by Kirill888** [comment]
Also this thing:

https://github.com/opendatacube/datacube-core/blob/f255a0529725ee6acb35e7619965746ab66ae83d/datacube/model/__init__.py#L569-L597

still being used by ingestor.

**Comment by omad** [comment]
Might still be used in `stats`, or one of the other applications too.

**Comment by Kirill888** [comment]
If this is the case then we probably need a new API call that can compute tighter extents from "sources" and switch over to that. This code is from 3 years back.

**Comment by Kirill888** [comment]
@omad Just like `ingest` stats is using `GeoPolygon.from_sources_extents` only, which does not generate deprecation warning since only constructing `GeoPolygon` does, but using static methods doesn't. Still I think keeping this "just in case" is too costly, imports are all over the place as it is, having more inter-dependencies in "model" is too costly. 

by the way stats is already broken as it pulls in `Variable` from model as well.

**Comment by Kirill888** [comment]
stats should be good after this is merged:

https://github.com/opendatacube/datacube-stats/pull/170
