### ISSUE TITLE
Difficulty opening NetCDF Storage Units with Xray

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#64]
The NetCDF Storage Units created by the ga/milestone1 code give a CF compliance error when attempting to open them with xray.

The error is either related to units, or to a data type issue. Further investigation is required.

**Comment by mpaget** [comment]
Could you please send a file path or an ‘ncdump -h’ of the CF metadata and I can have a look if there’s anything obvious?
Alternatively Josh should be across CF and data types so might be worth getting his input.

**Comment by omad** [comment]
The problem was a configuration issue. The _units_ attribute was being set to the integer 1 instead of the string "1".

This was fixed in code, but being overridden by a storage mapping configuration file.

I've fixed the configuration file and expanded the automatically run integration tests to use some real configuration files, as well as checking that xray can open our _storage units_.
