### ISSUE TITLE
Add mappings remove/purge option to config tool

### ISSUE THREAD

**Issue by v0lat1le** [opendatacube/datacube-core#65]
Removing a mapping cleanly means the storage units created using that mapping will also be deleted.

Discuss.

**Comment by jeremyh** [comment]
What use case(s) do you have in mind?

Once there's data, deletion becomes _hard_. 
- What if there are existing jobs running that use them? Such as an API user who has run get-descriptor, serialised their results, and plans to run get-data in the future.
- Local jobs that are queued to use this data but haven't started running yet.
- The file permissions also need to match. I was hoping for almost all units to be read-only to almost all users (such as to prevent accidental modification, not just for security).

I could see two useful and fairly easily implemented "delete" scenarios:
1. Hard deletion. **If no units have been created yet, delete the mapping record entirely.** This would be useful during initial setup/configuration of a cube.
2. Soft deletion. **If units have been created, mark the mapping as 'archived'.** The mapping still exists in the DB, and existing storage units remain (and could be cleaned up later separately), but no new storage units will be written for that mapping.

I imagine we may eventually want controlled modification of mappings too, such as if we have a minor change to storage units but cannot modify all existing historical ones (it's expensive). The mappings could be versioned, similar to datasets themselves, and the soft-deletion would be a new version.

**Comment by simonaoliver** [comment]
Soft deletion looks like the a reasonable solution. The issue with letting files persist is that the datacube interface is not the only access method for the data. As a data management task we could manage hard deletes through notification?
