### ISSUE TITLE
Datacube Ingest problem with latest revision of dask and distributed conda packages

### ISSUE THREAD

**Issue by santoshamohan** [opendatacube/datacube-core#658]
`datacube ingest` command of `Landsat 8 NBAR/NBART` data into a datacube using the latest revision of `dask` and `distributed` `conda` packages reports `OSError: [Errno 24] Too many open files` and `distributed.scheduler - ERROR - Error in reevaluate occupancy`.

Error log:
```
distributed.worker - INFO - Waiting to connect to:            tcp://r80:19629
distributed.worker - INFO - Waiting to connect to:            tcp://r80:19629
distributed.worker - INFO - Waiting to connect to:            tcp://r80:19629
distributed.worker - INFO - Waiting to connect to:            tcp://r80:19629
tornado.application - ERROR - Exception in callback (<socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 19629)>, <function wrap.<locals>.null_wrapper at 0x2b0d5f315950>)
Traceback (most recent call last):
  File "/g/data/v10/public/modules/dea-env/20190208/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/g/data/v10/public/modules/dea-env/20190208/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/g/data/v10/public/modules/dea-env/20190208/lib/python3.6/site-packages/tornado/netutil.py", line 264, in accept_handler
    connection, address = sock.accept()
  File "/g/data/v10/public/modules/dea-env/20190208/lib/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
OSError: [Errno 24] Too many open files
distributed.scheduler - ERROR - Error in reevaluate occupancy
```

### Expected behaviour
`datacube ingest` command shall not have any failures during `ingest` process with the latest revision of `dask` and `distributed` `conda` packages.

### Actual behaviour
`datacube ingest` command does not report any errors with` Landsat 8 PQ` data. However, there are lot many `OSError` raised by the `distributed` processes.

### Environment information
Following revisions of `dask` and `distributed` packages had issues with `ingest` process:
- `Distributed` - `v1.25.3`
- `Dask` - `v1.1.1`

Last known working revisions of `dask` and `distributed` packages for `datacube ingest` are as follows:
- `Distributed` - `v1.23.3`
- `Dask` - `v0.19.3`

* Which ``datacube --version`` are you using?
datacube: 1.6.2+366.gec83e77e

* What datacube deployment/environment are you running against?
dea module: dea/20190212

**Comment by Kirill888** [comment]
looks like this was environment problem of sorts, maybe tornado was broken at a time or some 3-rd party version mismatch, closing this for now.
