### ISSUE TITLE
Address future warning from upcoming xarray datetime changes

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#662]
Running `develop` branch against recent `xarray` generates following `FutureWarning`:
 
```
xarray/core/variable.py:134: FutureWarning: Converting timezone-aware DatetimeArray to ...
   ...timezone-naive ndarray with 'datetime64[ns]' dtype. ...
   ...In the future, this will return an ndarray with 'object' dtype where each element...
   ...is a 'pandas.Timestamp' with the correct 'tz'.
	To accept the future behavior, pass 'dtype=object'.
	To keep the old behavior, pass 'dtype="datetime64[ns]"'.
  return np.asarray(pd.Series(values.ravel())).reshape(values.shape)
```

I guess this is generated from `create_storage` or `group_datasets` whenever constructing time axis.

**Comment by omad** [comment]
Hopefully this makes the _datetime conversion dance (tm)_ I've had to do with xarray less painful in the future.

Good catch on the warning.

**Comment by Kirill888** [comment]
Warning comes from converting `ds.center_time` to `numpy.datetime64`, `center_time` includes time zone info, I have only seen it being UTC, but I guess this depends on what is indexed in the database as there is nothing in the code that modifies timestamp stored in metadata that I can see. I guess the correct fix for this is to convert `center_time` to UTC, then strip tzinfo then convert that to `np.datetime64[ns]`, this would have to happen in here:

https://github.com/opendatacube/datacube-core/blob/c33012db799b5ae38277c53f4c2f934a03044e74/datacube/api/query.py#L164-L172
