### ISSUE TITLE
Change default chunking behaviour when constructing dask arrays

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#665]
Question: what chunking should be used for non-spatial dimensions that user omits in the configuration?

Currently we use this policy: "If chunk size is not specified, the entire dimension length is used, as in xarray". While this makes sense for the 2 spatial dimensions it's not ideal for non-spatial dimensions since the real chunking for those is always `1`, we then re-chunk to full dimension unless user supplied  `'time': 1` in the chunking config.

I think it's best to define default behaviour to be: use most appropriate "native chunking" for non-spatial dimensions only, which with our current implementation will mean `1` for all unspecified non-spatial dimensions (i.e. `time=1`)

**Comment by andrewdhicks** [comment]
Do we stick with the `dask` special values?
http://docs.dask.org/en/latest/array-chunks.html#automatic-chunking

> `-1`: no chunking along this dimension
> `None`: no change to the chunking along this dimension (useful for rechunk)
> `"auto"`: allow the chunking in this dimension to accomodate ideal chunk sizes

**Comment by Kirill888** [comment]
@andrewdhicks would be ideal to copy this behavior from `dask`, not sure how to go about "auto" for spatial dimensions, other than defaulting to same as `-1`, certainly `-1` worth supporting though.
