### ISSUE TITLE
Cannot index dataset directly over HTTP

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-core#666]
### Expected behaviour
I should be able to index a YAML file directly from HTTP sources like so:
datacube  dataset add http://dapds00.nci.org.au/thredds/fileServer/if87/2015-07-12/S2A_OPER_MSI_ARD_TL_EPA__20160810T192637_A000271_T52JCM_N02.04/ARD-METADATA.yaml --confirm-ignore-lineage

it appears this HTTP URL is converted into a POSIX path somewhere along the way

### Actual behaviour
ERROR No supported metadata docs found for dataset http://dapds00.nci.org.au/thredds/fileServer/if87/2015-07-12/S2A_OPER_MSI_ARD_TL_EPA__20160810T192637_A000271_T52JCM_N02.04/ARD-METADATA.yaml

... eg. Incorrect result, python stacktrace, etc. ...

### Steps to reproduce the behaviour
see above
... Include code, command line parameters as appropriate ...

### Environment information
Open Data Cube core, version 1.6.2+373.geca11ebb
Local environment
* Which ``datacube --version`` are you using?
* What datacube deployment/enviornment are you running against?

**Comment by Kirill888** [comment]
@omad is this one fixed now?

**Comment by omad** [comment]
Yep!
