### ISSUE TITLE
psycopg2 error when running `datacube -v system init`

### ISSUE THREAD

**Issue by jcrattz** [opendatacube/datacube-core#667]
### Expected behaviour
When installing datacube-core 1.6.1, the command `datacube -v system init` is to be run.
In previous installations of this version of core on Ubuntu 16.04, we received output like the following:

> Initialising database...
> 2019-02-21 11:36:13,669 29463 datacube.drivers.postgres._core INFO Ensuring user roles.
> 2019-02-21 11:36:13,689 29463 datacube.drivers.postgres._core INFO Adding role grants.
> Updated.
> Checking indexes/views.
> 2019-02-21 11:36:13,728 29463 datacube.drivers.postgres._api INFO Checking dynamic views/indexes. (rebuild views=True, indexes=False)
> Done.
> 

### Actual behaviour
The following is the output of that command for an installation on Ubuntu 18.04 Server.
To my understanding, it looks like this same version (1.6.1) has a missing function in an `agdc` namespace, whereas it previously did not experience this error.

> /home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
>   """)
> 2019-02-21 16:42:21,178 12927 datacube INFO Running datacube command: /home/localuser/Datacube/datacube_env/bin/datacube -v system init
> Initialising database...
> 2019-02-21 16:42:21,436 12927 datacube.drivers.postgres._core INFO Ensuring user roles.
> 2019-02-21 16:42:21,455 12927 datacube.drivers.postgres._core INFO Adding role grants.
> Updated.
> Checking indexes/views.
> 2019-02-21 16:42:21,481 12927 datacube.drivers.postgres._api INFO Checking dynamic views/indexes. (rebuild views=True, indexes=False)
> Traceback (most recent call last):
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
>     cursor, statement, parameters, context
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 546, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.ProgrammingError: function agdc.common_timestamp(text) does not exist
> LINE 1: ...a_type_id, agdc.dataset.metadata AS metadata_doc, "agdc.comm...
>                                                              ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/localuser/Datacube/datacube_env/bin/datacube", line 11, in <module>
>     load_entry_point('datacube', 'console_scripts', 'datacube')()
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/home/localuser/Datacube/datacube-core/datacube/ui/click.py", line 192, in new_func
>     return f(parsed_config, *args, **kwargs)
>   File "/home/localuser/Datacube/datacube-core/datacube/ui/click.py", line 222, in with_index
>     handle_exception('Error Connecting to database: %s', e)
>   File "/home/localuser/Datacube/datacube-core/datacube/ui/click.py", line 297, in handle_exception
>     raise e
>   File "/home/localuser/Datacube/datacube-core/datacube/ui/click.py", line 220, in with_index
>     return f(index, *args, **kwargs)
>   File "/home/localuser/Datacube/datacube-core/datacube/scripts/system.py", line 61, in database_init
>     rebuild_views=recreate_views or rebuild,
>   File "/home/localuser/Datacube/datacube-core/datacube/index/_metadata_types.py", line 227, in check_field_indexes
>     rebuild_views=rebuild_views,
>   File "/home/localuser/Datacube/datacube-core/datacube/drivers/postgres/_api.py", line 778, in check_dynamic_fields
>     concurrently=concurrently,
>   File "/home/localuser/Datacube/datacube-core/datacube/drivers/postgres/_api.py", line 790, in _setup_metadata_type_fields
>     rebuild_indexes=rebuild_indexes, rebuild_view=rebuild_views)
>   File "/home/localuser/Datacube/datacube-core/datacube/drivers/postgres/_dynamic.py", line 111, in check_dynamic_fields
>     _ensure_view(conn, fields, name, rebuild_view, dataset_filter)
>   File "/home/localuser/Datacube/datacube-core/datacube/drivers/postgres/_dynamic.py", line 56, in _ensure_view
>     ).where(where_expression)
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 988, in execute
>     return meth(self, multiparams, params)
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
>     distilled_params,
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1248, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
>     util.raise_from_cause(sqlalchemy_exception, exc_info)
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 374, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 128, in reraise
>     raise value.with_traceback(tb)
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
>     cursor, statement, parameters, context
>   File "/home/localuser/Datacube/datacube_env/lib/python3.6/site-packages/SQLAlchemy-1.3.0b3-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 546, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) function agdc.common_timestamp(text) does not exist
> LINE 1: ...a_type_id, agdc.dataset.metadata AS metadata_doc, "agdc.comm...
>                                                              ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
>  [SQL: 'CREATE VIEW agdc.dv_eo_dataset AS SELECT agdc.dataset.id AS id, agdc.dataset.added AS indexed_time, agdc.dataset.added_by AS indexed_by, agdc.dataset_type.name AS product, agdc.dataset.dataset_type_ref AS dataset_type_id, agdc.metadata_type.name AS metadata_type, agdc.dataset.metadata_type_ref AS metadata_type_id, agdc.dataset.metadata AS metadata_doc, "agdc.common_timestamp"(agdc.dataset.metadata #>> \'{creation_dt}\') AS creation_time, agdc.dataset.metadata #>> \'{format, name}\' AS format, agdc.dataset.metadata #>> \'{ga_label}\' AS label, "agdc.float8range"(least(CAST(agdc.dataset.metadata #>> \'{extent, coord, ur, lat}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, lr, lat}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, ul, lat}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, ll, lat}\' AS DOUBLE PRECISION)), greatest(CAST(agdc.dataset.metadata #>> \'{extent, coord, ur, lat}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, lr, lat}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, ul, lat}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, ll, lat}\' AS DOUBLE PRECISION)), \'[]\') AS lat, "agdc.float8range"(least(CAST(agdc.dataset.metadata #>> \'{extent, coord, ul, lon}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, ur, lon}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, ll, lon}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, lr, lon}\' AS DOUBLE PRECISION)), greatest(CAST(agdc.dataset.metadata #>> \'{extent, coord, ul, lon}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, ur, lon}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, ll, lon}\' AS DOUBLE PRECISION), CAST(agdc.dataset.metadata #>> \'{extent, coord, lr, lon}\' AS DOUBLE PRECISION)), \'[]\') AS lon, tstzrange(least("agdc.common_timestamp"(agdc.dataset.metadata #>> \'{extent, from_dt}\'), "agdc.common_timestamp"(agdc.dataset.metadata #>> \'{extent, center_dt}\')), greatest("agdc.common_timestamp"(agdc.dataset.metadata #>> \'{extent, to_dt}\'), "agdc.common_timestamp"(agdc.dataset.metadata #>> \'{extent, center_dt}\')), \'[]\') AS time, agdc.dataset.metadata #>> \'{platform, code}\' AS platform, agdc.dataset.metadata #>> \'{instrument, name}\' AS instrument, agdc.dataset.metadata #>> \'{product_type}\' AS product_type \nFROM agdc.dataset JOIN agdc.dataset_type ON agdc.dataset_type.id = agdc.dataset.dataset_type_ref JOIN agdc.metadata_type ON agdc.metadata_type.id = agdc.dataset_type.metadata_type_ref \nWHERE agdc.dataset.archived IS NULL AND agdc.dataset.metadata_type_ref = 1'] (Background on this error at: http://sqlalche.me/e/f405)

### Steps to reproduce the behaviour
Follow the installation instructions [here](https://github.com/ceos-seo/data_cube_ui/blob/master/docs/open_data_cube_install.md).

### Environment information
The datacube version is 1.6.1.
The environment is Ubuntu 18.04 Server.

**Comment by jeremyh** [comment]
Thanks for the report John.

I can reproduce this error by upgrading sqlalchemy to the same beta version (1.3b3), but it works when I'm on the current stable release (1.2.18).

pip should only install stable releases by default -- was anything manually installed, or did it happen from just following that datacube-ui install guide? I can't see anything obvious in that guide that would lead to it, unless Ubuntu's packaging has changed on us. (we'd like to fix it if so!)

It should work if you downgrade back to the current stable release: `pip install sqlalchemy==1.2.18`

**Comment by jcrattz** [comment]
Jeremy, I can confirm that downgrading `sqlalchemy` to version `1.2.18` resolves this issue. 

Thank you for your help!
