### ISSUE TITLE
Errors when running against the impending sqlalchemy 1.3 release (in beta)

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-core#668]
Originally reported in #667

Datacube consistently fails when run against the current beta version of sqlalchemy. [According to](https://www.sqlalchemy.org/blog/2019/02/08/sqlalchemy-1.3.0b3-released/) the sqlalchemy devs this release "1.3b3 should hopefully be the last beta release for 1.3, as no additional major changes are planned."

This isn't currently a problem, but it will break all of our builds and guides if not resolved before 1.3 is declared stable.

Manually reproduce the error with:

```
    pip install sqlalchemy==1.3b3
    datacube system init
```

- Either the sqlalchemy 1.3 beta has a bug, which we should report to them.
- Or our own code is doing something incorrect and we should fix it before 1.3 is declared stable.

**Comment by roarmstrong** [comment]
sqlalchemy 1.3.0 is now stable. Possible fix on our end here: https://github.com/opendatacube/datacube-core/pull/680 but I'm not sure if it's better to raise an issue sqlalchemy to get some change to the quoting behavior instead
