### ISSUE TITLE
Need consistent pixel de-duplication across products deriving from common source

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#674]
## Introduction

Many data sources include duplicate pixels, for example both Landsat scenes and Sentinel granules overlap for the same satellite pass. Datacube de-duplicates pixels at load time (`group_by='solar_day'`). Until recently de-duplication order was defined purely by timestamp, specifically, earlier datasets within a group took precedence over the rest. This causes problems when datasets share exactly the same timestamp (happens for some Sentinel granules), since in this case order can change from one load to another. This problem was described in #646, and addressed by fixing dataset precedence  using UUID as a sorting key after sorting by time. While this solves the problem of *"pixel de-duplication precedence might change from load to load"*, it does nothing to address *"pixel de-duplication precedence is not consistent across related products"*.

Say you compute "better cloud-mask than fmask" for Sentinel granules. Your computation is per-granule and so shares the same duplicate pixels as the source product. When loading data from this `new-cloud-mask-s2a` product and from `s2a-granules` product you really want the same de-duplication order to be applied to both products. With the current implementation this won't be the case.

## Implementation Suggestions

First off, just fixing #671 is not enough of a solution to this problem. Sure, you could supply custom ordering function that would look for some `granule_id` key in the metadata and order by that. But that means that:

1. You have to manually propagate `granule_id` key (not a generic property) to derived product
2. You need to manually supply appropriate grouping function to both products

Note that if we had a concept of "region code" (#536), we could just sort by that when available and guarantee consistency of de-duplication order across related products, assuming derived product generation took care to copy region code across to the new product. So instead of sorting by `(time, uuid)` we could sort by `(time, region_code, uuid)`, one really should not have duplicate observations of the same granule/scene at the same time.

Note that this is all about default load precedence, users should be able to overwrite that with whatever custom precedence they want, including random, hence #671 is still relevant regardless.

**Comment by emmaai** [comment]
> But that means that:
> 
>     1. You have to manually propagate `granule_id` key (not a generic property) to derived product
> 
>     2. You need to manually supply appropriate grouping function to both products

I'm not totally happy with this. The rule of grouping function should be propagated in some way so that the derived product can be loaded by the same rule without carrying the grouping function everywhere.


> Note that if we had a concept of "region code" (#536), we could just sort by that when available and guarantee consistency of de-duplication order across related products, assuming derived product generation took care to copy region code across to the new product. So instead of sorting by `(time, uuid)` we could sort by `(time, region_code, uuid)`, one really should not have duplicate observations of the same granule/scene at the same time.

This might be a better way in dealing with the issue.

**Comment by alexgleith** [comment]
What about a temporal/dimensional interpolation?

Resampling in space is vaguely equivalent, right? So you can have an implicit nearest-neighbour selector (get earliest in the day, with the caveats that you already mention) or a mean, or a median or some higher level interpolation.

Interestingly, when doing a `group_by='solar_day'`, it seems to take the datetime from the first in the group, rather than using 00:00 or 12:00 as the new 'time'. If it was set to midday, it would be plausible to do a linear interpolation between times... might be overcomplicating things, though!

**Comment by Kirill888** [comment]
@alexgleith NN resampling in time dimension is roughly what we do right now, the problem this issue is concerned with is how to treat overlapping datasets that have exactly identical timestamps, one has to pick one over another, which one? and how to make this "choice" consistent across products. With Landsat things are easy since no two scenes have exactly the same timestamp and derived datasets inherit timestamp so choice is consistent across products. This breaks down when two overlapping datasets share exactly the same timestamp, in that case we need some other property that is consistent across source and derived products to order by. Right now no such property exists.

**Comment by Kirill888** [comment]
As far as timestamp for a group goes, you are correct lowest timestamp of a group is used. This is to preserve "resolution" in time dimension for use-cases where time of day is important (Intertidal Extent Modelling needs this for example). It does create problems for other use-cases where you want to merge datasets on day-level resolution, using this behaviour as default is "reasonable" because you can always "round" more precise timestamp to day resolution, but you can not restore rounded timestamp back.
