### ISSUE TITLE
Better integration with notebook display for core data types

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#681]
# Summary

Many of datacube users work mostly in notebooks, yet none of our classes take advantage of rich display capabilities provided by the notebook environment. Here is an example of  how easy it is to add “display on a map” feature to `GeoBox` class, leveraging existing Jupyter ecosystem: 

<img width="1259" alt="GeoJSON-GeoBox" src="https://user-images.githubusercontent.com/1428024/54249381-19182580-4594-11e9-95af-097da284c744.png">

full notebook is here: https://gist.github.com/Kirill888/4ce2f64413e660d1638afa23eede6eb0

# Proposal

1. Implement `_ipython_display_` methods on important objects like `GeoBox`, `Dataset`
   - Take advantage of `GeoJSON` module when available, fallback to textual representation otherwise
2. Update documentation/example notebooks with instructions on how to best take advantage of rich display ecosystem available inside Jupyter environment
3. Update various docker files we have sitting around to include `GeoJSON` nbextension and possibly others

**Comment by Kirill888** [comment]
@alexgleith do we have extensions installed in the dask cluster already? If not, how hard is it to add them?

see:
https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/geojson-extension

**Comment by alexgleith** [comment]
We do have some installed, but we can install more!

What do you want specifically? I'll add it to our default image.

**Comment by Kirill888** [comment]
I'd like `GeoJSON` extension please, I can import it, but it doesn't display, not in a notebook nor in a lab environment.

**Comment by Kirill888** [comment]
@otto-AMA have AMA experimented with `jupyter-lab` as  opposed to just `jupyter-notebook`? Seems like there is a richer set of data visualisation extensions available in that space.

**Comment by alexgleith** [comment]
Maybe you need to be in JupyterLab?

If you go to the DEA Sandbox, and use the URL `user/yourname/lab` instead of `user/yourname/tree` it should work.

**Comment by alexgleith** [comment]
We experimented with JupyterLab, but it broke a number of things, so we haven't made it default. It's enabled, though!

**Comment by Kirill888** [comment]
@alexgleith yeah that's what I tried first, I seen no lab extensions installed in the container, tried installing in a terminal but file permissions won't let me, probably worth changing that, greater chance for user to break things, but also more flexible. I don't fully understand lab extensions, they have both python and JS parts, and it's the JS part that is missing in the case of GeoJSON.

**Comment by alexgleith** [comment]
Hmm, ok. Will look into it.

**Comment by Kirill888** [comment]
Another example displaying result of `find_datasets`:

<img width="480" alt="Screen Shot 2019-03-13 at 6 16 58 pm" src="https://user-images.githubusercontent.com/1428024/54261296-8c835c80-45bf-11e9-8487-19c0acbd6d4e.png">

**Comment by woodcockr** [comment]
Is what is being proposed along the lines of using jupyter notebook extensions like this one:
[OpenGeoscience geonotebook](https://github.com/OpenGeoscience/geonotebook)

**Comment by Kirill888** [comment]
These specific examples rely on jupyterlab GeoJSON extension^, so will only work in jupyter-lab and not in plain jupyter-notebook. I'm sure it is less capable than `geonotebook`, but is also easier to install, and so more accessible.

Better integration with popular visualisation backends would be useful though, which ones are being actively used in the community?


^https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/geojson-extension

**Comment by otto-AMA** [comment]
@Kirill888  Yes. A few of our personal dev environments run jupyter labs. I find it to be a superior drop-in replacement for jupyter notebooks in most cases.  
  
I have had some issues with the transfer-ability of bokeh plots and macros that I've eventually resolved on a case by case basis.  The integrations for jupyter labs are definitely cooler.

**Comment by otto-AMA** [comment]
@woodcockr   
Geonotebooks are really cool. Have you explored them yet?  I really think they might be the ideal research/dev environment. It can mirror the experience that helped popularize GEE, at least in terms of user experience/interaction.

**Comment by alexgleith** [comment]
That does look really cool, @otto-AMA ... we'd need some form of save function, coupled with a OWS engine that works with it, hey. A combination of Dask for computing the tiles -> save them -> index them -> OWS serving them could be great!

**Comment by woodcockr** [comment]
@otto-AMA 

> Have you explored them yet?

No, unfortunately not. You may have noticed my vision currently exceeds my grasp! I'm used to having quite a large team so usually get someone to play with these things but work changes have made that something of the past and I confess it is taking me a long time to adapt. On the bright side, I'm coding again!!

The folks here are responding well to the PC docker setup, appreciative of the fact that out of the box it has the right puzzle pieces for use in our organisation. I was thinking a geonotebook extension might be a very handy addition, especially now they can effectively index our entire internal archive MODIS and LS data for use on their desktops (though I mostly recommend they only index a portion of it at a time, and if they have sufficient fast local disk ingest that part). Tend to mirror this into the AWS setup as well to give the same experience. which reminds me, need to chat to @alexgleith about Cube-in-a-box.

So much to do, now I have more time....hmm....I'll let you know if I get to conduct an experiment.

**Comment by alexgleith** [comment]
Hey @Kirill888, we've added the GeoJSON package to both the sandboxes, if you'd like to test it?

**Comment by Kirill888** [comment]
@alexgleith seems to work
![GoeJSON-sandbox-test](https://user-images.githubusercontent.com/1428024/54789203-cb7f7500-4c85-11e9-8350-cd38528ac15b.PNG)
