### ISSUE TITLE
[Proposal] Product Summary Table

### ISSUE THREAD

**Issue by ashoka1234** [opendatacube/datacube-core#689]
### Product Summary Table

Datacube ecosystem has two database based extent summary 
implementations, one in `datacube-explorer` and another in `datacube-ows`. 
Reconciliation of the needs in those two applications into one is hard and 
can be excessive for `datacube API` itself. If the use cases of these two
applications are not fully implemented it is unlikely they will be ported to
a new implementation. This is a proposal for 
a novel implementation of `spatial and time extents` in a `datacube.summary` 
package for more general audience of datacube.
- A single summary table contains all the spatial and time summaries 
to be persisted
- Any specific summary sought should be contained in
a single row and can be retrieved fast provided a suitable `database index`
is available.
- Arbitrary types of summaries should be able to be queried. Possible 
queries may include:
    - summary for a product
    - summary of a `region_code` for a `product`
    - summary during a `time period` for a `product`
    
The `database schema` could be something like:
```sql
create table summaries (
    query jsonb not null primary key,
    time_created DateTime(timezone=True), server_default=func.now(), 
                          nullable=False,
    spatial_bounds jsonb,
    spatial_footprint jsonb,
    time_footprint jsonb
);
```

Postgres `Gin indexes` could be created for targeted fields of the `query`.
This table could be used as a cache and the practicability of this depends on 
whether the database should be `read only` for a typical user.

This issue is related to an earlier issue #366 and perhaps should replace it.

**Comment by Kirill888** [comment]
@ashoka1234 can you provide more details for roughly what structure those `jsonb` things will contain, particularly `query` bit. 

Some questions:

- I'm not seeing product_id anywhere, or is this buried in `query` somewhere? 
- What is the plan for keeping these summaries up to date?
- How we going to expose these summaries? Rough outline of expected API would be useful here.

The real problem here is that the smallest unit of information datacube is using to interface with database is a `Dataset` which is a giant json blob. There is no mechanism to expose just time or just spatial information per dataset, it comes with the giant blob of all the extra gunk. And hence SLOW. Even for larger products/queries say in 1 million datasets range, combining 1 million ranges into one single range is not a very costly operation, but reading 1 million json blobs is.

**Comment by ashoka1234** [comment]
Thanks @Kirill888 for comments.

> I'm not seeing product_id anywhere, or is this buried in query somewhere?

I am intending to keep `query` field to be as close as possible to a typical query that we supply to `Datacube.load()`. Yes `product` is to be buried in `query`. 

I haven't finalised the structure of json blobs but roughly: `spatial_bounds` could contain four bounds values or two corners, `spatial_footprint` would be `geojson` compliant `multi-polygon (cascaded union)` and `time_footprint` (or `dates`) would be a `json` array of `dates`.

> What is the plan for keeping these summaries up to date?

This is a hard one. Automation of this require `write access` to the table in which case we can make the summary table behave more like a `cache`. In the absence of `write access` to table we have to populate the `summary` table, say with monthly product summaries, product-wide summaries, and other queries involving say `region-code`. Even then if the datasets changes in the database, how do we keep summaries up to date? May be some `efficient mechanism` can verify with good probability that the summaries could be correct: for example extract `created dates` and compare with the date the summary   record added. 

> How we going to expose these summaries?

I expect this interface to be simple, for example `summary.get_summaries(**kwargs)` where `kwargs` to be passed as `query`. I intend to add other functions such as `get_product_time_min(product: str)` which are to be directly computed within the `postgres database`.

I intend to access much smaller units than `Dataset`, for example if we extract `min_offset` from the `metadata_type`, for `get_product_time_min(product: str)`, we could write something like:

```
        time_field = DateDocField('aquisition_time_min',
                                  'Min of time when dataset was acquired',
                                  DATASET.c.metadata,
                                  False,  # is it indexed ToDo
                                  offset=min_offset,
                                  selection='least')

        result = self._index._db._engine.execute(
            select([func.min(time_field.alchemy_expression)])
        ).first()
 ```

For `extents` this sort of extraction is harder, but if we are willing to parse it we could at least extract the relevant bits.
