### ISSUE TITLE
_gdfnetcdf.py - NetCDF - Set dimension issue

### ISSUE THREAD

**Issue by didierearith** [opendatacube/datacube-core#7]
Dear Team,

I found an issue in the 'set_dimension' function in _gdfnetcdf.py:
I replaced

```
            dimension_index_vector = np.around(np.arange(dimension_min, dimension_max, element_size), self.decimal_places)
```

by

```
            dimension_index_vector = np.around(np.linspace(dimension_min, dimension_max, dimension_config['dimension_elements']), self.decimal_places)
```

because when using a non-integer step, such as 0.25, the results is often not be consistent. (the number of elements doesn't match the expected one, e.g. 1001 instead 1000).

It is better to use linspace for these cases.

Kind regards,

Didier

**Comment by omad** [comment]
Closing. GDF has been deprecated.
