### ISSUE TITLE
get_data() in datacube.api.API returns empty "arrays" when "variables" is not given in the descriptor

### ISSUE THREAD

**Issue by wenjunwu** [opendatacube/datacube-core#71]
Should all available "variables" ("band data") be returned if "variables" is not given in the descriptor?

**Comment by andrewdhicks** [comment]
API now returns all variables when none are specified.
We will need to think more about what will be returned when we support band aliases.
(E.g. would we still return band_10, band_20 etc, or would we need to include all aliases as well, or just include all of the variable properties? e.g. band_10: {alias: 'blue', wavelength: ...}

**Comment by woodcockr** [comment]
Suggestion in the v2 design workshop, and in the architecture though not welled described, is for the user environment to include a "semantic" configuration  option. this would specify what aliases to use, otherwise I would suggest either all or some other default would need to be defined.

**Comment by andrewdhicks** [comment]
Thanks Rob. I saw that there was an semantic engine, but not a lot on how it could work, so having the user choose their semantic configuration makes sense. I like the idea of a sensible default fallback too, if we can get everyone to agree on what it would be.
