### ISSUE TITLE
Dataset search query processing, limits, and paging

### ISSUE THREAD

**Issue by ashoka1234** [opendatacube/datacube-core#714]
## Dataset search query language and query processing 
The datacube `dataset search` query language consists of `field_names` and `query kwargs` that 
we pass onto various search functions. Then we need to process these queries like as follows:

Firstly, for a given `query`, we select a product `p` &isin; `(query['product'] or products)`  s.t.
  * &forall; (k, v) &isin; query 
    * k &isin; search_fields(p.metadata_type) + native_fields + fixed_fields and 
  * if ('metadata_type', v) &isin; `query`, then 'metadata_type' = p.metadata_type
  * if `select_fields` are specified then &forall; f &isin; select_fields,
    * f &isin; search_fields(p.metadata_type) + native_fields + fixed_fields

Secondly, we form a`db_query(p)` for selected products
  * (k,'=', v) &isin; db_query if 
    * (k,v) &isin; query and 
    * (k,v) &notin; p.metadata (an evaluation step)
  * ('dataset_type_ref', '=', p.id) &isin; db_query
  
Thirdly, we execute the queries that we formed for each product selected.

## Single or multiple `db_queries`?
To properly implement certain search features, such as `limits` (number of datasets to be returned) and `paging`, we need to generate a single `db_query` . This can always be done by forming a union of the queries. We can also combine all the product queries into a single query if select_fields are specified and the first part of the second step is same for all the selected products, which is likely I think.

Currently the above query processing steps are too coupled in certain `dataset search` functions and it is best if we decouple these steps to separate functions to avoid duplication of code if we want to implement `limit` feature correctly and also useful for `paging`.

**Comment by uchchwhash** [comment]
As we were discussing the other day, feel free to scrape the `limit` feature if it gets in your way. I would tend to agree with @jeremyh and @Kirill888 that we need to tame this horrendous mess that you just described here, even if it means breaking backwards compatibility big time.

**Comment by Kirill888** [comment]
What we are missing is a clean separation of where `datacube-core` ends and supposedly pluggable `db backend` driver begins.

Exactly what is the contract between `datacube-core` and `db backend`? Is `limit` part of this contract? If yes is it `global` limit or `per-product` limit? None of it is clearly defined.

`limit` was added as a convenience feature to work in a common case, i.e. using `single` product query. It works well for that use case. If a given a choice to drop `limit` vs dropping `multi-product` queries, I would rather drop `multi-product` query.
