### ISSUE TITLE
Remove prepare scripts and update docs for new location

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#738]
Right now we have *prepare scripts* and related *product definitions* duplicated across several repositories. It is not clear where the most up to date version of the script/product yaml is. I think decision has been made to move prepare scripts out of this repo, I believe most scripts have been moved to this repository: [opendatacube/datacube-dataset-config](https://github.com/opendatacube/datacube-dataset-config) and that's where further development/maintenance of the scripts is performed. The next step of deleting old copies haven't been done however.

Things to do:

1. Cleanup `datacube-dataset-config` README
2. Update `datacube-core` documentation to direct to `datacube-dataset-config` repository for prepare scripts/product yamls
3. Remove prepare scripts from `datacube-core`
4. Prune product definitions from this repo keeping a minimal set
   - Develop purely "sample" definitions to replace existing product yamls, optimised for documentation value
   - Develop purely "test" definitions to define/test edge-cases and the like

**Comment by alexgleith** [comment]
This is done, right @Kirill888?

**Comment by Kirill888** [comment]
yes, except for (4)
