### ISSUE TITLE
jsonschema raised an error when validating in multiprocessing

### ISSUE THREAD

**Issue by emmaai** [opendatacube/datacube-core#748]
### Expected behaviour
N/A

### Actual behaviour
DatasetType.validate raised an error of "not finding the pointer `definitions/storage`"

### Steps to reproduce the behaviour
```from datacube.model import DatasetType as Product
    def _create_product(self, metadata_type, product_type, data_measurements, storage,
                        custom_metadata):
        product_definition = {
            'name': self.name,
            'description': 'Description for ' + self.name,
            'metadata_type': metadata_type.name,
            'metadata': {
                'product_type': product_type,
                **custom_metadata
            },
            'storage': storage,
            'measurements': data_measurements
        }
        Product.validate(product_definition)
        return Product(metadata_type, product_definition)
```
Run the function in multiprocessing, at some point (but not always), `validate`will raise the error as above.
### Environment information
The branch `develop` of Datacube
Jsonschema `2.6.0`

The problem appears to be solved after updating jsonschema to `3.0.1`

**Comment by Kirill888** [comment]
This version (`2.6.0`) is from 2017, current `dea` module on NCI includes version `3.0.1`, which is latest at the time of writing. My guess is that something "pickling related" got fixed in the last 2 years inside `jsonschema`  library.

**Comment by Kirill888** [comment]
this whole validation decorator is a weird beast.

On one hand it loads main schema at "decorate" time and adds `validate` method to the class being decorated, but it does not construct actual validator object until `validate` is called. When constructing validator object it might need to read more files from the same folder as main schema, so IO for schema files is split between "import" time and "validate" time. This certainly complicates things when using distributed computation, basically it means that not only worker environment has to have the same version of software installed, it has to be installed in the same path if your schema is referencing external files.

**Comment by emmaai** [comment]
Turned out the newer version of jsonschema doesn't help in fixing the bug. It showed up again. Is there any "fast" way to fix it?

**Comment by Kirill888** [comment]
@emmaai fast way to fix it is to not validate product, or not do product adding in worker threads, do it all ahead of time
