### ISSUE TITLE
setup fails to configure properly without "-e" in pip install 

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#76]
Using either "python setup.py install" or "pip install ." fails to configure build agdc-v2 correctly.

$ datacube-config database init
Traceback (most recent call last):
  File "/usr/local/bin/datacube-config", line 9, in <module>
    load_entry_point('datacube==0.0.0+851.g9a52c61', 'console_scripts', 'datacube-config')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2719, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2379, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2385, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/datacube-0.0.0+851.g9a52c61-py2.7.egg/datacube/**init**.py", line 4, in <module>
    **version** = get_version()
  File "/usr/local/lib/python2.7/dist-packages/datacube-0.0.0+851.g9a52c61-py2.7.egg/datacube/version.py", line 74, in get_version
    raise RuntimeError('Unknown version: Not a git repository, a python dist tarball or a git-created archive.')

sudo pip install -e . is a work around for now

**Comment by omad** [comment]
Which version of pip and setuptools do you have, and how was python installed?

```
python -c 'import setuptools; print(setuptools.__version__)'
pip --version
```

**Comment by simonaoliver** [comment]
pip 8.0.2
setuptools 19.6.2
on Ubuntu 15.04 (default python install) 2.7.9 GCC 4.9.2 on linux2
- builds prior to recent changes (5 Feb) installed without this error and no change to python environment the same setup

**Comment by wenjunwu** [comment]
bash-4.1$ diff datacube/version.py ../agdc-v2/datacube/
31,32c31,32
< GIT_ARCHIVE_REF_NAMES = 'HEAD -> develop'

## < GIT_ARCHIVE_COMMIT_HASH = '017b660'

> GIT_ARCHIVE_REF_NAMES = '$Format:%D$'
> GIT_ARCHIVE_COMMIT_HASH = '$Format:%h$'

The problem can be fixed by replacing the above two lines with fixed values.

**Comment by simonaoliver** [comment]
I've tested this on the problem platform and works with both install from git zip and from repo clone - happy to close

**Comment by wenjunwu** [comment]
+1 – it now also works on both raijin and VDI

## Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.
