### ISSUE TITLE
configuration support for temporal stacks - daily, yearly, monthly storage units

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#79]

**Comment by v0lat1le** [comment]
- **aggregation_period** parameter has been added to storage type config
- **aggregation_period** can be _year_ or _month_
- if **aggregation_period** is not specified _year_ is assumed
- **ingest** command has been added to _datacube-ingest_ replacing original behaviour
- _datacube-ingest_ **ingest** produces single time-slice storage units
- **stack** command has been added to _datacube-ingest_ for stacking storage units
