### ISSUE TITLE
'Australian Users' documentation out of date

### ISSUE THREAD

**Issue by robbibt** [opendatacube/datacube-core#794]
### Actual behaviour
The OpenDataCube read-the-docs has a page called 'Australian Users > NCI Usage Guide' which provides info on how to connect to DEA using the VDI. This page appears very out of date, referencing 'AGDC', and `agdc-py2-prod` modules.

https://datacube-core.readthedocs.io/en/datacube-1.4.1/user/nci_usage.html

Does this page even need to exist now we have a DEA read-the-docs?

**Comment by uchchwhash** [comment]
Are you looking at the latest version of the document though? Your URL refers to a much older version 1.4.1. The current version is of course 1.7.

Maybe you meant to look at https://datacube-core.readthedocs.io/en/latest/?

**Comment by robbibt** [comment]
@uchchwhash  Yes, looks like the version Google took me to is way out of date. Will close!
