### ISSUE TITLE
Importance of yml files after indexing completion

### ISSUE THREAD

**Issue by jankovicgd** [opendatacube/datacube-core#798]
Hi all, more of a question, sorry if not the right place.

I am planning on setting up a continuous indexing chain that involves several scripts, pieces of software, servers and apis etc. and the final destination is `opendatacube`.

Since the scripts are indexing and creating many yml files daily, I might want to move these to a separate directory after indexing to avoid a heavy load with already indexed files, and just index newly incoming data. Are these yml files in any way important after the columns have been filled in the database? I noticed a `url_body` field to for this exact location in the `dataset_location` table of the database and I am wondering if it is important or not. What would you recommend otherwise?

### Environment information

* 1.6.2 most likely
* running in a docker stack

**Comment by alexgleith** [comment]
Hey @jankovicgd

The .yaml files are generally used for dataset level metadata, and as such, I'd suggest that you want to keep them with your data files in case you want to index again in the future. This means the ODC implementation you have is reproducible, which is important, and the data will be potentially useable in other software, so the ODC is not the only way to use the data.

**Comment by jankovicgd** [comment]
This is definitely a good idea, however there is a whole mess of how our folders and datasets are structured currently and the load of new files coming in. Some datasets contain multiple files as separated bands in different folders and some datasets have bands inside a single file etc. My question was just if there is any loss of functionality if these yml files are moved from their path, after indexing, to another location. For the future the files would stay in another 'backup' location.

EDIT: From what I can also tell, but without any testing yet, the dataset level metadata is also written in the database and that is used when requesting metadata.

**Comment by jankovicgd** [comment]
I did some testing. The yml metadata file can be moved. I am still unclear whether indexing continually the same directory with same+new yml files would cause a drop in performance. As far as I'm concerned this issue can be closed.

**Comment by Kirill888** [comment]
@jankovicgd re-indexing same folder over and over will not change anything in the database, indexing step detects that dataset with a given UUID already exists at the same location and won't do anything at this point.
