### ISSUE TITLE
data preparation support for Landsat (GA/USGS), Sentinel-2 (L1C, L2A), Himawari8 (BRF), MODIS (CSIRO).

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#8]
Investigate how DataCube is going to support ingesting following datasets:
- Landsat from GA (L1T, NBAR, PQ, FC)
- Landsat from USGS (L1, SR)
- Sentinel-2 L1C and L2A
- Himawari-8 BRF
- MODIS from CSIRO

**Comment by v0lat1le** [comment]
GA LS *, Sentinel-2 L1C and Himawari-8 are done. For the rest separate issues will be created
