### ISSUE TITLE
Make the CRS class compatible with pyproj.CRS, rasterio.CRS and fiona

### ISSUE THREAD

**Issue by snowman2** [opendatacube/datacube-core#810]
https://github.com/opendatacube/datacube-core/blob/5ca7cf1b3cc2cad47f88cacf99da95057868c3f8/datacube/utils/geometry/_base.py#L93

Rasterio:

https://github.com/mapbox/rasterio/blob/cefb90a98ca34b9ea2c747d0beae72781485a1af/rasterio/crs.py#L448-L452

pyproj:

https://github.com/pyproj4/pyproj/blob/bbaaff08eb0ffebed5189c611ea0956c5a5aaaa3/pyproj/crs.py#L432-L433

Suggestions:
1. Add `to_wkt()` method
2. Allow creation of CRS with other CRS that have `to_wkt()` method.

**Comment by uchchwhash** [comment]
Hi @snowman2, would you expand on suggestion 2 a little?

**Comment by snowman2** [comment]
This would allow you to pass a rasterio.CRS or pyproj.CRS into the constructor and create a geocube CRS object. Reason for using the `to_wkt()` method: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems

**Comment by snowman2** [comment]
Related to: #811 #807
