### ISSUE TITLE
No validation of config in ingestor

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#826]
### Expected behaviour

When user supplies mal-formed ingestor configuration I expect errors to be reported to the user, instead exception with `KeyError` is raised.

### Actual behaviour

ingestor does not check that `src_varname` is valid for source product, resulting in errors like following (reported on slack):

```
File "/root/miniconda3/envs/odc/lib/python3.6/site-packages/datacube/scripts/ingest.py", line 153, in ensure_output_type
    output_type = morph_dataset_type(source_type, config, index, storage_format)
  File "/root/miniconda3/envs/odc/lib/python3.6/site-packages/datacube/scripts/ingest.py", line 72, in morph_dataset_type
    for spec in config['measurements']]
  File "/root/miniconda3/envs/odc/lib/python3.6/site-packages/datacube/scripts/ingest.py", line 72, in <listcomp>
    for spec in config['measurements']]
KeyError: '1'
```

### Steps to reproduce the behaviour

Create ingestor config with mis-spelled `src_varname:` attribute for one of the measurements, then run ingestor.

Error is here:

https://github.com/opendatacube/datacube-core/blob/73d98a36d69a1a4aaee8cc89945cf652a6de6260/datacube/scripts/ingest.py#L71-L72

no prior validation happened, yet code assumes that `src_varname` 
(a) exists in the config (maybe that part is checked with schema?)
(b) points to valid measurement in the source product

**Comment by jdh-ama** [comment]
I will work on this.

**Comment by jdh-ama** [comment]
We could take advantage of this library for YAML schema validation.

https://pypi.org/project/pykwalify/
http://www.kuwata-lab.com/kwalify/ruby/users-guide.01.html#schema

**Comment by Kirill888** [comment]
Thanks @jdh-ama as for schema validation we currently use is `jsonschema`

https://github.com/opendatacube/datacube-core/blob/1b649b59aa66ac6fe655f6dee0c841ff2fba9fa7/datacube/utils/documents.py#L542

Used like this here:

https://github.com/opendatacube/datacube-core/blob/1b649b59aa66ac6fe655f6dee0c841ff2fba9fa7/datacube/model/__init__.py#L394-L395

I'm not familiar with this space and there are some problems with the current approach see #748, but unless proposed library offers significantly better experience I would prefer to use existing approach for validating ingestor config.

**Comment by Kirill888** [comment]
I think that PR only addressed schema-level validation, i.e. presence/absence of keys and not whether band names in source product match configuration.
