### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#828]
Python 3.5 is now 5 years old, it is no longer being developed. There are no plans to make new releases past 3.5.9 that came out last month.

Some prominent Python libraries are starting to drop support for Python 3.5 (Django 3 for example).

Version of python3 on current stable Ubuntu is 3.6.9.

There are a number of annoying differences between Python 3.5 and newer Python3.6. Mostly to do with `pathlib.Path`, those often come up in unit tests.

There are some places in the code that are special cased for python 3.5 (to do with unicode handling). For example here:
https://github.com/opendatacube/datacube-core/blob/dc162e3d5590932279d8058f9f6ed8b12974af7c/datacube/utils/documents.py#L75-L80

Switching to 3.6+ only would also allow use of "f-Strings":

```python
print(f"Value {x} is no good")         # 3.6+
print("Value {} is no good".format(x)) # 3.5
```

Other important features that are only available in newer version of Python include

- Underscores in numeric constants `1_000_000` vs `1000000`, code readability
- Syntax for variable type annotations, becoming more important as we are adding `mypy` annotations to functions and methods
- Some async improvements that we do not have current use for

**Comment by snowman2** [comment]
Also related:
https://github.com/pydata/xarray/pull/3358

**Comment by Kirill888** [comment]
Thanks @snowman2 very useful links that I could not find yesterday. If `numpy` and `xarray` are planning on dropping 3.5 "very soon" then that makes our choice much easier.

**Comment by omad** [comment]
Awesome. That means I can start using f-strings all over the place! :D
