### ISSUE TITLE
Record the size of storage units

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-core#83]
We would like to be able to to easily generate statistics for collections, such as total size.

'Dataset' metadata has a size_bytes field, but we don't record a similar field for storage units.

**Comment by omad** [comment]
After implementing this, Greg, Jeremy and I have had some further discussion. This simply duplicates what is stored on disk, and could be calculated with a database query and bunch of filesystem stat() calls. However it will be a little easier and significantly faster to query the database, if and when we have a dashboard and reporting requirements.

For now, it can stay.

We may also want to look at including file checksums.
