### ISSUE TITLE
Change internals from using AGDC to using ODC

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#830]
It's been a few years since Open Data Cube was named, but there are still plenty of internal references to the Australian Geoscience Data Cube. It would be great to change these.

Including:
- Database Schema Name
- Created PostgreSQL roles
- Test database
- Lots of configuration references

**Comment by whatnick** [comment]
Bump

**Comment by fivejjs** [comment]
Can we also add support postgis support?

**Comment by omad** [comment]
> Can we also add support postgis support?

That would be great! And is something we would love to be working on, but is a much larger job than changing some names. However, changing names isn't completely trivial, so they may end up happening at the same time.

**Comment by SpacemanPaul** [comment]
See https://github.com/opendatacube/datacube-core/wiki/ODC-v2-Roadmap

**Comment by omad** [comment]
We're going to leave the PostgreSQL schema as `agdc` in the existing drive, but the new PostGIS driver already uses ODC for the schema.
Closing
