### ISSUE TITLE
Storage Unit search is slow

### ISSUE THREAD

**Issue by andrewdhicks** [opendatacube/datacube-core#85]
Searching for storage units can be slow, due to the list of dataset_refs.
Not including this made a sample search go from 6.5s -> 0.17s.
See `datacube/index/_storage.py:167`
Greg suggests that the query could be optimized.

**Comment by v0lat1le** [comment]
The dataset id's are required for storage unit stacking. Also for general symmetry of things :P...

I'm using array_agg and group_by to retrieve those in one query in https://github.com/data-cube/agdc-v2/blob/0b5b15d553834ac00fb4e3ef69239b7b05a4cc3e/datacube/index/postgres/_api.py#L381-L400

**Comment by jeremyh** [comment]
Yuck, I didn't realise we were doing N+1 selects. As Greg says, it could easily be put into a single query.

**Comment by jeremyh** [comment]
@andrewdhicks Does your code use the dataset id list? I'm wondering if it's worth making it optional too so that we can avoid the join when not needed (such as by returning it as a sibling rather than inside the SU object).

**Comment by andrewdhicks** [comment]
@jeremyh I'm not using it. Optional would work for me. I don't know if I'd need the dataset_id for anything later on, say for provenance tracking. Would any derived data just link back to the storage_id, or would it need the list of dataset_ids?

**Comment by jeremyh** [comment]
For the basic output API (writing a full dataset out and ingesting it), you'll need the original source dataset ids to write the provenance files.

For the in-memory output API I think you could just reference the storage unit IDs (which could then be linked easily during insert).

**Comment by jeremyh** [comment]
Initial implementation in b3087892bee2f. Will wait for feedback before closing...
