### ISSUE TITLE
Remove s3aio drivers

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#863]
`s3aio` driver was an experiment in using `zarr`-like storage on S3, before `zarr` became a well known thing.

My understanding is that it is no longer being used or developed. Nor is it a recommended way for storing/accessing imagery on S3. 

Recommended way is to use Cloud Optimized GeoTIFFs on S3, this is done by the default, rasterio based driver. It can be confusing to new users who want to utilise S3 with datacube, as they assume that s3aio is the way to go.

There is also non-trivial amount of developing overhead, mostly to do with tests and environment setup.

**Comment by woodcockr** [comment]
Agreed, we can remove this now in preparation for a ODC 2.0 Zarr support with improved data handling setup for both COGS, Zarr and other multi-dimensional formats as plugins.
