### ISSUE TITLE
`<geometry object>.simplify()` fails silently with None output, should probably raise error

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#867]
`datacube.utils.geometry.Geometry.simplify` wraps `osgeo.ogr.Simplify`, which provides C++ style interface of returning NONE on error. 

We should detect that case and raise an error to be more pythonic, currently it returns `None` on error.

Also there are no tests that call this function.

**Comment by uchchwhash** [comment]
Fixed by PR #880.
