### ISSUE TITLE
If DB_PORT is not set, config process sets port to an empty string

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-core#874]
I have an existing environment that sets up the datacube connection using this:
```
      - DB_HOSTNAME=host.docker.internal
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
```

and with the new changes to read config from environment variables over the config file, the port is required to be set with `DB_PORT=5432`.

Expected behaviour was that if the port is blank it is set to the default for Postgres.

https://github.com/opendatacube/datacube-core/blob/8481d907b198a1c8946326b8b70625a9a8523a12/datacube/config.py#L265

**Comment by Kirill888** [comment]
@alexgleith is it not set or set to an empty string?

**Comment by alexgleith** [comment]
It was not set.

**Comment by Kirill888** [comment]
@alexgleith  tests with `DB_PORT` environment variable not set show no `db_port` in  the generated config, but if `DB_PORT` is set to an empty string, then yes it ends up in the config but shouldn't. What does `env | grep DB_PORT` show in your environment?
