### ISSUE TITLE
Change Documentation Build and Publication

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#879]
## Background

As of last week, the ODC documentation build process has been broken, again. See https://readthedocs.org/projects/datacube-core/builds/

This is a **very common** problem, and **hard to debug**. The problems include:
* the docs need ODC installed to build. 
* ODC is hard to install due to the mass of geospatial and scientific binary dependencies.
* Read The Docs doesn't provide a stable or easily debugged build environment,
* and the Read The Docs environment changes regularly.

### Proposal
I think we should change the documentation builds to use Github Actions and Docker containers.

We can host the docs using [Netlify](https://netlify.com) which provides an easy to use free, CDN backed static web hosting with a custom domain.

Benefits:
        - We can use a nicer URL, eg: https://docs.opendatacube.org/
        - We get a more stable environment to build the docs in.
        - We get a more easily debugged environment to build the docs in.
        - We can ensure docs are building before merging PRs.

Drawbacks
        - The URL for the docs has to change, but we should be able to set up redirects.
        - We won't have old versions of the docs available, unless we do some extra work. However, I don't think we need them.

Does anyone have any concerns or suggestions, or should I go ahead and try to make this happen?

**Comment by robbibt** [comment]
@omad Would this be a good thing in the longer run for the DEA User Guide/dea-notebooks docs too? I don't have a good idea of how much work goes on in the background to keep that running correctly

**Comment by omad** [comment]
> @omad Would this be a good thing in the longer run for the DEA User Guide/dea-notebooks docs too? I don't have a good idea of how much work goes on in the background to keep that running correctly

At some point it might make sense to change how the DEA User Guide is compiled, but not for now. It's *far* simpler to run because it doesn't require a working ODC Install to build sucessfully.

**Comment by Kirill888** [comment]
A note about read the docs - it's building ok now. Basically after removing GDAL python bindings dependency on `datacube` it is now possible to have `datacube` installed using `pip` on the read-the-docs infrastructure. We still have a large number of complex dependencies, but those do provide binary wheels now (GDAL was the last one that didn't build on RTD).

Not saying we should just stay with read the docs forever, just wanted to highlight that the urgency for the change is much lower now.
