### ISSUE TITLE
Datacube product add is not "atomic and re-entrant"

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-core#881]
### Expected behaviour

Cancelling `datacube product add` using SIGINT , should allow re-add of the product cleanly.

### Actual behaviour

Indexes reference views by hardcoded product id's and the views are broken and the indexes are broken.

### Steps to reproduce the behaviour

Indexes reference views by hardcoded product id's and the views are broken and the indexes are broken. Run `datacube product add` , cancel it using Ctrl+C , run `datacube product add` for the same product again, it is fast but querying this data is very slow.

- Search through agdc.dataset_type to find the id for the dataset_type, which is 71 in this case
- Find the corresponding view and do a Create Script (using PGAdmin)
- Note that the ID in this is 34 (which is quite different, which is weird)

**Comment by alexgleith** [comment]
Steps to identify this issue, which causes slow dataset lookups, are as follows:

1. Connect to the database directly (I like to use PGAdmin)
2. Search through the `agdc.dataset_type` table to find the id for the dataset_type, note the ID
3. Find the corresponding view and indexes for this table, for example, `agdc.dv_<dataset_type_name>_dataset`  and look at the SQL used to create this view
4. Note that if the ID in this view is different to the ID in 2, this is bad!

**Comment by omad** [comment]
This occurs quite often because `datacube product add` on a large database is both very slow, and provides minimal progress feedback and so appears to have hung.

**Comment by Kirill888** [comment]
no idea how to address it properly, but I added Ctrl-C handler so at least users will know what the consequences of killing this process is, also forces them to use `kill -9` which is less convenient.
