### ISSUE TITLE
Delete support for zone/datum as a mechanism for declaring CRS

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#885]
This code:

https://github.com/opendatacube/datacube-core/blob/c743f66d4b6118a9b1373ce0f0e6d7879f11da7b/datacube/model/__init__.py#L239-L256

not sure what datasets out there use this style in the wild, best way to find out is to delete this code.

**Comment by jeremyh** [comment]
It's used by a few of the first products from our old collection

eg. 
- L1: https://explorer.dea.ga.gov.au/dataset/b12c5560-38d3-11e6-a187-a0000100fe80
- NBAR: https://explorer.dea.ga.gov.au/dataset/ab85cc39-c679-4fa2-a3fe-85ced4875d8f

(Hopefully to be retired in a few months when C2 support ends?)

**Comment by Kirill888** [comment]
@jeremyh  thanks, good to know, for now people will see deprecation warning when accessing crs/loading data from those products.
