### ISSUE TITLE
datacube-ingest ingest fails when chunksize depth in storage config > 1

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#89]
_ValueError: chunksize cannot exceed dimensions size_

Above error makes sense because I'm ingesting a single time slice

datacube-ingest stack doesn't know how deep to make my chunks.

Expect to be able to configure chunk depth in storage stack but can't specify depth >1 (maybe aggregate/stack depth as separate attribute in storage config?).

**Comment by v0lat1le** [comment]
Dimension size is respected when setting chunksize.
The minimum of the two is used.
