### ISSUE TITLE
 Index Data on S3(Ceph)

### ISSUE THREAD

**Issue by iliang** [opendatacube/datacube-core#896]
### Expected behaviour
Use datacube api to get dataset

### Actual behaviour
Incorrect result, Query dataset will return empty xarray.

... eg. Incorrect result, python stacktrace, etc. ...

### Steps to reproduce the behaviour
step 1
- python3 index_from_s3_bucket.py bucketname -p C1/L8/139/045/ --suffix="MTL.txt"
I can find one record in my agdc.dataset ,  agdc.dataset_location, and no record in my agdc.dataset_source.

step 2 show products
- list_of_products = dc.list_products()
products = list_of_products[list_of_products['format'] == 'GeoTiff']
products
7	ls5_level1_usgs	Landsat 5 USGS Level 1 Collection-1 OLI-TIRS	TM	LANDSAT_5	None	None	GeoTiff	None	None	None	L1TP	NaN	NaN	NaN	NaN
6	ls7_level1_usgs	Landsat 7 USGS Level 1 Collection-1 OLI-TIRS	ETM	LANDSAT_7	None	None	GeoTiff	None	None	None	L1TP	NaN	NaN	NaN	NaN
8	ls8_l1_pc_usgs	Landsat 8 USGS Level 1 Pre-Collection OLI-TIRS	OLI_TIRS	LANDSAT_8	None	None	GeoTiff	None	None	None	L1T	NaN	NaN	NaN	NaN
5	ls8_level1_usgs	Landsat 8 USGS Level 1 Collection-1 OLI-TIRS	OLI_TIRS	LANDSAT_8	None	None	GeoTiff	None	None	None	L1TP	NaN	NaN	NaN	NaN

step 3 dc.find_datasets
- <bound method Datacube.find_datasets of Datacube<index=Index<db=PostgresDb<engine=Engine(postgresql://dc_user:***@127.0.0.1:5432/datacube)>>>>

step 4 
- dss = dc.find_datasets(product="ls8_level1_usgs", latitude=(21,21.2), longitude=(86.7, 86.9))
dss
output : []

step 5
- dc.index.datasets.count(product="ls8_level1_usgs")
output : [1]

step 6
- ds, = dc.find_datasets(product="ls8_level1_usgs", limit=1) 
ds.metadata_doc
- {'id': '32fa78b4-3597-554b-9cfe-f1e85bcddd28',
 'image': {'bands': {'nir': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B5.TIF',
    'layer': 1},
   'red': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B4.TIF',
    'layer': 1},
   'blue': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B2.TIF',
    'layer': 1},
   'green': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B3.TIF',
    'layer': 1},
   'lwir1': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B10.TIF',
    'layer': 1},
   'lwir2': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B11.TIF',
    'layer': 1},
   'swir1': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B6.TIF',
    'layer': 1},
   'swir2': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B7.TIF',
    'layer': 1},
   'cirrus': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B9.TIF',
    'layer': 1},
   'quality': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_BQA.TIF',
    'layer': 1},
   'panchromatic': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B8.TIF',
    'layer': 1},
   'coastal_aerosol': {'path': 's3://dcbucket/C1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/LC08_L1TP_139045_20170304_20170316_01_T1_B1.TIF',
    'layer': 1}}},
 'label': 'LC81390452017063LGN00',
 'extent': {'coord': {'ll': {'lat': 85.8694977275825,
    'lon': 20.610041795245515},
   'lr': {'lat': 88.06045501053292, 'lon': 20.610485722030123},
   'ul': {'lat': 85.85296718933647, 'lon': 22.715665870841406},
   'ur': {'lat': 88.07596179098907, 'lon': 22.716159863683806}},
  'to_dt': '2017-03-04 04:37:24.6864810Z',
  'from_dt': '2017-03-04 04:37:24.6864810Z',
  'center_dt': '2017-03-04 04:37:24.6864810Z'},
 'format': {'name': 'GeoTiff'},
 'lineage': {'source_datasets': {}},
 'platform': {'code': 'LANDSAT_8'},
 'instrument': {'name': 'OLI_TIRS'},
 'creation_dt': '2017-03-04',
 'grid_spatial': {'projection': {'geo_ref_points': {'ll': {'x': 382200.0,
     'y': 2279400.0},
    'lr': {'x': 610500.0, 'y': 2279400.0},
    'ul': {'x': 382200.0, 'y': 2512500.0},
    'ur': {'x': 610500.0, 'y': 2512500.0}},
   'spatial_reference': 'EPSG:32645'}},
 'product_type': 'L1TP',
 'processing_level': 'L1TP'}

### Environment information
(datacube_env) localuser@:~$ pip freeze
affine==2.3.0
attrs==19.3.0
aws-sat-api==2.0.2
backcall==0.1.0
beautifulsoup4==4.8.2
bleach==3.1.1
boto3==1.12.20
botocore==1.15.20
branca==0.4.0
cachetools==4.0.0
certifi==2019.11.28
cftime==1.1.0
chardet==3.0.4
click==7.1.1
click-plugins==1.1.1
cligj==0.5.0
cloudpickle==1.3.0
cycler==0.10.0
Cython==0.29.15
dask==2.12.0
-e git+https://github.com/opendatacube/datacube-core.git@8d517db0520210a5ea590ae71edc6196ec4e0dc8#egg=datacube
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.1.1
distributed==2.12.0
docutils==0.15.2
entrypoints==0.3
folium==0.10.1
GDAL==3.0.4
hdmedians==0.13
HeapDict==1.0.1
idna==2.9
imageio==2.8.0
importlib-metadata==1.5.0
ipykernel==5.1.4
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.16.0
Jinja2==2.11.1
jmespath==0.9.5
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.0.0
jupyter-console==6.1.0
jupyter-core==4.6.3
kiwisolver==1.1.0
lark-parser==0.8.2
MarkupSafe==1.1.1
matplotlib==3.2.0
mistune==0.8.4
msgpack==1.0.0
multiprocess==0.70.9
nbconvert==5.6.1
nbformat==5.0.4
netCDF4==1.4.2
networkx==2.4
notebook==6.0.3
numpy==1.15.0
pandas==1.0.1
pandocfilters==1.4.2
parso==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
prometheus-client==0.7.1
prompt-toolkit==3.0.4
psutil==5.7.0
psycopg2==2.8.4
psycopg2-binary==2.8.4
ptyprocess==0.6.0
Pygments==2.6.1
pyparsing==2.4.6
pyrsistent==0.15.7
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3
pyzmq==19.0.0
qtconsole==4.7.1
QtPy==1.9.0
rasterio==1.1.3
requests==2.23.0
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
s3transfer==0.3.3
scikit-image==0.16.2
scipy==1.4.1
Send2Trash==1.5.0
Shapely==1.7.0
six==1.14.0
snuggs==1.4.7
sortedcontainers==2.1.0
soupsieve==2.0
SQLAlchemy==1.3.15
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
toolz==0.10.0
tornado==6.0.4
traitlets==4.3.3
urllib3==1.25.8
wcwidth==0.1.8
webencodings==0.5.1
widgetsnbextension==3.5.1
xarray==0.15.0
zict==2.0.0
zipp==3.1.0

* Which ``datacube --version`` are you using?
(datacube_env) localuser@:~$ datacube system check
Version:       1.7+247.g8d517db0
Config files:  /etc/datacube.conf,/etc/datacube.conf
Host:          127.0.0.1:5432
Database:      datacube
User:          dc_user
Environment:   None
Index Driver:  default

* What datacube deployment/enviornment are you running against?
Linux vmcore-874129-iaas 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Kirill888** [comment]
Not sure if this was reolved on slack, but this is a known issue of broken prepare scripts when using GDAL3:

https://github.com/opendatacube/datacube-dataset-config/issues/10
