### ISSUE TITLE
Azure Blob support

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-core#912]
### Expected behaviour
A user in the slack group has asked if ODC supports Azure blob store 

### Actual behaviour

ODC only supports s3 and gs cloud storage: (and vsicurl etc.) 
https://github.com/opendatacube/datacube-core/blob/develop/datacube/utils/uris.py 

### Required work 

To add support for azure blob storage we should add wasb[s]:// to:
https://github.com/opendatacube/datacube-core/blob/develop/datacube/utils/uris.py  

To enable it to actually be indexed we should probably create a wasb_to_tar script to the odc tools repo https://github.com/opendatacube/odc-tools/tree/master/apps/cloud/odc/apps/cloud

**Comment by alexgleith** [comment]
You don't think it'll work? I guess we should try! 

This identifies the URI for the Azure blob, which is `/vsiaz/` https://github.com/opendatacube/datacube-core/blob/develop/datacube/utils/uris.py#L37

**Comment by Kirill888** [comment]
Issue if not with GDAL but with python URL parsing libraries, for some reason it needs a whitelist of supported protocols. As Tom mentioned we just need another call to `register_scheme`  like this one is for `gs`. 

https://github.com/opendatacube/datacube-core/blob/e327e8f3508111635dfee2cffa36ae079384737e/datacube/utils/uris.py#L242-L244

Users can do that themselves too, but for standard cloud formats we should put in to core
