### ISSUE TITLE
Decision: Should we deprecate or document the use of multiple environment variables for defining a database connection

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-core#925]
### Description
Currently, there is a legacy method of defining the database connection that uses the following environment variables:
 - `DB_HOSTNAME=postgres`
 - `DB_USERNAME=opendatacube`
 - `DB_PASSWORD=opendatacubepassword`
 - `DB_DATABASE=opendatacube`
 - `DB_PORT=5432`

This came from the first Dockerfile, which used an entrypoint to set the values in a configuration file.

This has been replaced with code that reads environment variables directly, and that code is documented [here](https://datacube-core.readthedocs.io/en/latest/ops/config.html#configuration-via-environment-variables), but only documents using a database string, so a single environment variable `DATACUBE_DB_URL`.

The decision here is to:
1. Allow two ways of using environment variables, either the single connection string or the five separate environment variables (probably renamed to be `DATACUBE_DB_<example>`.
2. Deprecate the use of five variables, and phase out their use completely soon and only allow the single-variable configuration.

**Comment by Kirill888** [comment]
I originally put those in for backward compatibility with old Dockerfile and to ease migration of deployments

My main concerns with `DB_*` versions

1. Name is too generic so there is a possibility of clashes with user environment
2. There are too many of them so it's 5 times more likely to have something misspelled or truncated (is it `DB_USER` or `DB_USERNAME` ??) and also harder to pass into docker when running directly (not via compose)

URL syntax has some advantages over `DB_*x5` format:
1. Can be extended to include various extra db options without needing yet more environment variables
2. Can be extended to multi-db configuration, use `:space:` as a separator for example
3. If we ever get multi-db backends it's much easier to represent in URL format

**Comment by woodcockr** [comment]
I'm currently using 5 variables, mostly cause I'm lazy and haven't got around to changing to the URL format.
@Kirill888 makes some good points, have made a few of those errors myself. I'm not so sure one very long url will work for multi-db though, will get awkwardly long though I suspect preferable to multiple variables still.
I'm not overly bothered which way we go so long as its documented. If a preference is required then the URL is probably the better option - and yeah, I should go fix that in my setup...

**Comment by Kirill888** [comment]
Other option for multi-db config is to use one env var per environment:

```
DATACUBE_DB_URL=postgresql://ro_user:secret123@db.host.tld/db1
DATACUBE_DB_URL_mydb=postgresql:///mydb
```

Then in code `Datacube(env="mydb")` would connect to local server `mydb` and `Datacube()` will connect `db.host.tld`. Implementing such functionality for `5x` env vars is also possible of course but significantly more annoying to use.

Although if you do that, might as well just bring your own config file.

**Comment by alexgleith** [comment]
So, I think that we should make the use of the 5 environment variables the default.

If they are changed to ODC_DB_* then that's fine with me, so long as we have a phased deprecation.

I will often change just one of them (say, the DB name) and not the others, and it's consistent with how Postgres does it's configuration too.

So, I think document the multiple environment variables! `todo: ...`
