### ISSUE TITLE
`write_cog` producing a RasterBlockError for small < 500 pixel arrays

### ISSUE THREAD

**Issue by robbibt** [opendatacube/datacube-core#926]
### Expected behaviour
I'm trying out the `write_cog` function after getting the new `DepreciationWarning` on `write_geotiff`. I have a 500 x 500 array `da` that looks like the image below:

![image](https://user-images.githubusercontent.com/17680388/80170742-06dc3800-862c-11ea-826d-07ff4907d0c2.png)

I would like to use `write_cog` to export small (< 500 pixel) GeoTIFFs like this without raising errors or being required to specify a custom block size:

```
write_cog(da, 'output.tif')
```

### Actual behaviour

```
---------------------------------------------------------------------------
RasterBlockError                          Traceback (most recent call last)
<ipython-input-233-659d25359e6e> in <module>
----> 1 write_cog(all_time_mask_da, f'output_data/{study_area}_{output_name}/all_time_mask2.tif')
/g/data/v10/public/modules/dea/unstable/lib/python3.6/site-packages/datacube/utils/cog.py in write_cog(geo_im, fname, blocksize, overview_resampling, overview_levels, **extra_rio_opts)
    189         overview_resampling=overview_resampling,
    190         overview_levels=overview_levels,
--> 191         **extra_rio_opts)
    192 
    193 
/g/data/v10/public/modules/dea/unstable/lib/python3.6/site-packages/datacube/utils/cog.py in _write_cog(pix, geobox, fname, nodata, overwrite, blocksize, overview_resampling, overview_levels, **extra_rio_opts)
    121     with rasterio.Env(GDAL_TIFF_OVR_BLOCKSIZE=blocksize):
    122         with rasterio.MemoryFile() as mem:
--> 123             with mem.open(driver="GTiff", **tmp_opts) as tmp:
    124                 tmp.write(pix, band)
    125                 tmp.build_overviews(overview_levels, resampling)
/g/data/v10/public/modules/dea-env/20200313/lib/python3.6/site-packages/rasterio/env.py in wrapper(*args, **kwds)
    392     def wrapper(*args, **kwds):
    393         if local._env:
--> 394             return f(*args, **kwds)
    395         else:
    396             with Env.from_defaults():
/g/data/v10/public/modules/dea-env/20200313/lib/python3.6/site-packages/rasterio/io.py in open(self, driver, width, height, count, crs, transform, dtype, nodata, sharing, **kwargs)
    134                           height=height, count=count, crs=crs,
    135                           transform=transform, dtype=dtype,
--> 136                           nodata=nodata, sharing=sharing, **kwargs)
    137 
    138     def __enter__(self):
rasterio/_io.pyx in rasterio._io.DatasetWriterBase.__init__()
RasterBlockError: The height and width of dataset blocks must be multiples of 16
```

### Steps to reproduce the behaviour
Import pickled array:
[da_pickled.zip](https://github.com/opendatacube/datacube-core/files/4526386/da_pickled.zip)

Run:
```
with open('da.pickle', 'rb') as handle:
    da = pickle.load(handle)
    
write_cog(da, 'output.tif')
```

`write_cog(da, 'output.tif', blocksize=128)`  does work, however feels like a regression in functionality compared to `write_geotiff`. Most users will simply want their file exported without hassle, and won't know how to deal with that error...

### Environment information
Datacube version '1.8.0b7.dev22+gfae6fbfd' on DEA/unstable on the NCI

**Comment by robbibt** [comment]
The function appears to currently ~~hard-code~~ default the block size to 512:

https://github.com/opendatacube/datacube-core/blob/c5a7192b5a5d82dd8d1ee3cfc67732c86f6bc680/datacube/utils/cog.py#L52-L53

**Comment by Kirill888** [comment]
@robbibt it's not hard-coded, but it does default to `512` when not supplied, you can override that by passing `blocksize=256` to `write_cog`. 

Having said that, small images should be supported, so this needs fixing.

**Comment by Kirill888** [comment]
So error is here:

https://github.com/opendatacube/datacube-core/blob/c5a7192b5a5d82dd8d1ee3cfc67732c86f6bc680/datacube/utils/cog.py#L91-L92

When one of the dimensions is less than supplied/defaulted `blocksize` AND is not a multiple of 16, things will break. I think the fix can be as simple as this:

```python
 blockxsize=blocksize, 
 blockysize=blocksize, 
```
