### ISSUE TITLE
Add doc building dependencies to test runner docker

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#934]
Test runner Docker currently doesn't include all the necessary parts for building datacube documentation. It probably should.

Tasks:
- identify and install extra apt packages
- install `datacube` with `doc` option that pulls in sphinx dependencies

**Comment by omad** [comment]
I've started this already in the `dra/docs-updates` branch. It's hacky for now, but builds successfully.

https://github.com/opendatacube/datacube-core/blob/dra/docs-updates/.github/workflows/build-docs.yml#L31-L34

**Comment by omad** [comment]
I was going to fix the deploy to Netlify then make a PR today, it's an old branch that I should have had merged months ago. :(

**Comment by Kirill888** [comment]
I think that should go into Dockerfile, it will make it a bit larger, but doubt enough to notice slow down of tests. By the way `datacube[doc]` now pulls in all the needed sphinx thing, I'm pretty sure. We should probably have doc building as part of every commit, or at least on PR.

**Comment by Kirill888** [comment]
I think we should stay with read the docs for now, since we no longer have GDAL python binding dependency it is a bit more stable now and all the links/google point to that.

Or is netlify for testing doc changes on branches?

**Comment by omad** [comment]
> ... should go into Dockerfile, it will make it a bit larger, but doubt enough to notice slow down of tests.

Actually, at the moment we have a dependency on PlantUML when building the docs. It' neat, but it relies on Java so adds 573 MB to the image, too much to bake in IMO.

I want to look at removing it so docs are simpler to build. Either a script to pre-build and commit the diagrams, calling it via a remote web service, or using a lighter weight tool.

**Comment by omad** [comment]
> I think we should stay with read the docs for now, since we no longer have GDAL python binding dependency it is a bit more stable now and all the links/google point to that.

Okay, that'll make a big difference, I'll look into getting RTD running again today.

> Or is netlify for testing doc changes on branches?

I had thought about using Netlify (or any other static host) for our docs, due to the pains of keeping RTD running. But staying on RTD make sense for now.

Using it for looking at docs from PRs is a good option, since that's not possible with RTD last I checked.

**Comment by Kirill888** [comment]
RTD is running already

**Comment by omad** [comment]
Awesome!
I really need to stop living in the past and get with the times. :(

**Comment by Kirill888** [comment]
@omad so java is a bit huge, how about we go the middle road, get all the other doc building dependencies sorted: `make` and all the python libs. Then it would still be small enough Docker image and pretty useful for verifying minor doc updates locally.

**Comment by omad** [comment]
Yep, I have a plan for getting rid of java too. [sphinxcontrib-mermaid · PyPI](https://pypi.org/project/sphinxcontrib-mermaid/) *should* be able to replace PlantUML, while adding zero build time deps.
