### ISSUE TITLE
Update ingestor to generate EO3 metadata

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#944]
Now that EO3 metadata is supported natively within datacube we should update ingestor tool to generate new style metadata as well.

Only implication I see is the use of embedded lineage datasets. EO metadata captures source datasets in full (recursively includes definitions), while EO3 only references source UUIDs. For the common case of using single database this does not cause any issues. It's only a problem when adding ingested netcdfs to a different database while still wanting to retain lineage info.

**Comment by omad** [comment]
Ingestor is going to be deprecated and removed, there's no point implementing this now.
