### ISSUE TITLE
This is going to log every time they run `init`, even if they already have applied this update.

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-core#952]
This is going to log every time they run `init`, even if they already have applied this update.

By convention, I usually wrapped them in a check previously:

```python
if not pg_column_exists(engine, schema_qualified('dataset'), 'updated'):
    _LOG.info("Adding Update Triggers")
    with engine.connect() as c:
        c.execute('begin')
        install_timestamp_trigger(c)
        .... etc
```
(of course, no need to check other columns exist as they're all applied together in one transaction.)

The actual SQL looks idempotent so this is all an extremely minor gripe.

_Originally posted by @jeremyh in https://github.com/opendatacube/datacube-core/pull/951_

**Comment by omad** [comment]
This has been resolved with the new PostGIS database driver, and is a **wontfix** for the old PostgreSQL driver.
