### ISSUE TITLE
Skip include lineage verification for eo3 dataset documents

### ISSUE THREAD

**Issue by kieranricardo** [opendatacube/datacube-core#956]
### Expected behaviour

eo3 lineages of the format 

```lineage: {"name": ["UUID"]}```

Should not be verified because they don't contain information about the linked dataset document. There is a work around by adding the `--no-verify-lineage` to `datacube dataset add  ...` but this should happen by default.

### Actual behaviour

The data provided in the lineage is compared against the linked dataset document which ends up comparing:

```python
{'id': UUID', 'lineage': {'source_datasets': {}}}
```

To the full dataset document and throws this error because the two aren't equal.

```ERROR Inconsistent lineage dataset```.

### Steps to reproduce the behaviour

Add a lineage to an eo3 dataset document and run:

```
datacube dataset add ...
```

### Environment information

* Which datacube --version are you using? Open Data Cube core, version 1.8.0
* What datacube deployment/enviornment are you running against? Local datacube deployment using the setup as in https://datacube-core.readthedocs.io/en/latest/ops/db_setup.html

**Comment by kieranricardo** [comment]
@Kirill888 I'm keen to have a go at this! can you assign me?

**Comment by Kirill888** [comment]
https://github.com/opendatacube/datacube-core/blob/0bf503fe5b92acbd8125b042de8b7123866a73a6/datacube/index/hl.py#L155-L163

I'd say in code above, even if `verify_lineage` is enabled, we should skip the check if `main_ds` is of EO3 kind.

**Comment by Kirill888** [comment]
Thanks for looking into it.
