### ISSUE TITLE
Allow specifying dataset location from within the yaml document

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#990]
## Problem

Dataset document encodes location of bands relative to the location of the dataset document. When indexing with `datacube dataset add`, location of the yaml file is recorded in the database and there is no way to overwrite this value. This creates problems when trying to index public datasets that one can read, but can not write a dataset yaml file next to pixel data.

## Proposal

Add  an optional top-level field `location` of type string that contains a URI relative to which band paths are defined. When this field is present in the document, value stored there will take precedence over the actual location of the yaml file. The true location of the yaml will then not be recorded in the database, as we only have one spot for that information currently.

**Comment by Kirill888** [comment]
@jeremyh how is that?

**Comment by jeremyh** [comment]
Looks good. I'd like to see this feature.

The workarounds that people use for this are quite a pain -- such as using absolute file-paths in measurements of some NCI products.

We had this field in the original discussions -- see here in the prototype: 

https://github.com/opendatacube/odc-tools/blob/8569b31646311a6ac8a0d926a6316c877e7e9e52/docs/normalised-dataset.yaml#L11-L15

And eodatasets3's document model includes it as a field called "locations"^1: https://github.com/GeoscienceAustralia/eo-datasets/blob/eodatasets3/eodatasets3/model.py#L382-L399, though only for reading/writing, there's no api exposure.

^1 I realise now that eodatasets3 uses plural "locations", and the original proposal "location". I'm not sure if that was deliberate. But it does take an array in both forms, and the other fields are plural where a collection is taken.

**Comment by Kirill888** [comment]
I think non-plural `location`  was chosen as a most common case, note that a string is accepted, and `list[str]` is for advanced use-cases. Given that we do not really have proper support for multiple locations in `dc.load` I didn't want to add confusion with plurals.

I started implementing it at the `scripts/dataset` level, but now realise it has implications for lineage datasets embedded in the EO style docs, I think I'll ignore those.

**Comment by jeremyh** [comment]
Ah, I missed that it accepts either type. 

I'm not a big fan of unions here -- it makes the handling and testing code more complicated in the ecosystem for only a tiny drop in verbosity, and some code will inevitably be written without knowing that arrays are an option at all. Writing the type detection also has easy pitfalls -- you can't rely on checking that it's iterable, or a list. Or allow conversion from string-like things easily.

**Comment by Kirill888** [comment]
in which case I would rather drop multiple location support, since it's not really supported beyond metadata handling.

**Comment by jeremyh** [comment]
It is exposed and working in the apis: `dataset.uris` and the various `locations` methods on the Index. We use them a fair amount in collection-management. 

As an example (from this morning), our telemetry is often on multiple storage locations: https://explorer.dea.ga.gov.au/dataset/896605c4-9178-11e5-879d-ac162d791418

One reason I see this addition to documents as useful is that it would allow us to dump whole products from an Index into a json/yaml file, and then easily add them to another Index (such as a testing database) "losslessly". If we didn't support multiple locations we couldn't always accurately recreate the foreign index. 

The rest of the ODC supports multiple locations (at least all of it that I've used?), so I feel we're introducing another gotcha if we have one part that doesn't.

**Comment by jeremyh** [comment]
Though I'm ok with the union if you do prefer it strongly --  it's a pretty minor gripe from me :slightly_smiling_face:

**Comment by Kirill888** [comment]
For dataset documents in particular, we can not rely on schema validation, since there is no schema, nor could there be one (due to metadata indirection system), so checking types in Python code is a must anyway.

If we document `locations: [dataset locations]` next question would be, what does it mean to have multiple locations? And we do not have answer to that. I'm talking about users who only interface `dc.load(..)`, which is a majority.

And for advanced users like yourself, who actually understand and work with metadata objects, there is an escape option of supplying a list for `location:`.

So yes my strong preference is for `location: ""` with optional `location: []` for advanced cases.

**Comment by jeremyh** [comment]
Ok :+1:

**Comment by jeremyh** [comment]
I notice the stac folks have moved toward having separate field names rather than unions: a doc has either `datetime` or else the range fields, rather than one field as a union. That might be even cleaner?

ie. `location` is a string, `locations` is an array
