### ISSUE TITLE
Running datacube system init on an existing database fails when adding new columns

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-core#997]
### Expected behaviour
Updating the database structure should not cause the init process to fail

### Actual behaviour

An active database may have locking happening which causes the `datacube system init` command to fail. Logs:

> datacube -v system init
> 2020-07-24 01:28:43,559 362 datacube INFO Running datacube command: /env/bin/datacube -v system init
> Initialising database...
> 2020-07-24 01:28:43,808 362 datacube.drivers.postgres._core INFO Ensuring user roles.
> 2020-07-24 01:28:43,818 362 datacube.drivers.postgres._core INFO Adding role grants.
> 2020-07-24 01:28:43,839 362 datacube.drivers.postgres._core INFO Adding Update Triggers
> Traceback (most recent call last):
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
>     cursor, statement, parameters, context
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.errors.DeadlockDetected: deadlock detected
> DETAIL:  Process 16680 waits for AccessExclusiveLock on relation 16492 of database 16592; blocked by process 18866.
> Process 18866 waits for AccessShareLock on relation 16431 of database 16592; blocked by process 16680.
> HINT:  See server log for query details.
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/env/bin/datacube", line 8, in <module>
>     sys.exit(cli())
>   File "/env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/env/lib/python3.6/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/env/lib/python3.6/site-packages/datacube/ui/click.py", line 196, in new_func
>     return f(parsed_config, *args, **kwargs)
>   File "/env/lib/python3.6/site-packages/datacube/ui/click.py", line 228, in with_index
>     return f(index, *args, **kwargs)
>   File "/env/lib/python3.6/site-packages/datacube/scripts/system.py", line 48, in database_init
>     with_permissions=init_users)
>   File "/env/lib/python3.6/site-packages/datacube/index/index.py", line 60, in init_db
>     is_new = self._db.init(with_permissions=with_permissions)
>   File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_connections.py", line 182, in init
>     _core.update_schema(self._engine)
>   File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_core.py", line 166, in update_schema
>     install_timestamp_trigger(c)
>   File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_triggers.py", line 50, in install_timestamp_trigger
>     conn.execute(UPDATE_COLUMN_MIGRATE_SQL_TEMPLATE.format(schema=SCHEMA_NAME, table=name))
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1006, in execute
>     return self._execute_text(object_, multiparams, params)
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1181, in _execute_text
>     parameters,
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
>     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
>   File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
>     cursor, statement, parameters, context
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.OperationalError: (psycopg2.errors.DeadlockDetected) deadlock detected
> DETAIL:  Process 16680 waits for AccessExclusiveLock on relation 16492 of database 16592; blocked by process 18866.
> Process 18866 waits for AccessShareLock on relation 16431 of database 16592; blocked by process 16680.
> HINT:  See server log for query details.
> 
> [SQL: 
> alter table agdc.dataset_source add column if not exists updated
> timestamptz not null default now();
> ]
> (Background on this error at: http://sqlalche.me/e/13/e3q8)
> jovyan@jupyter-alexgleith:~$ datacube -v system init
> 2020-07-24 01:45:37,650 386 datacube INFO Running datacube command: /env/bin/datacube -v system init
> Initialising database...
> 2020-07-24 01:45:37,901 386 datacube.drivers.postgres._core INFO Ensuring user roles.
> 2020-07-24 01:45:37,911 386 datacube.drivers.postgres._core INFO Adding role grants.
> 2020-07-24 01:45:37,918 386 datacube.drivers.postgres._core INFO Adding Update Triggers
> Traceback (most recent call last):
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
>     cursor, statement, parameters, context
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.errors.DeadlockDetected: deadlock detected
> DETAIL:  Process 16605 waits for AccessExclusiveLock on relation 16492 of database 16592; blocked by process 18557.
> Process 18557 waits for AccessShareLock on relation 16431 of database 16592; blocked by process 16605.
> HINT:  See server log for query details.
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/env/bin/datacube", line 8, in <module>
>     sys.exit(cli())
>   File "/env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/env/lib/python3.6/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/env/lib/python3.6/site-packages/datacube/ui/click.py", line 196, in new_func
>     return f(parsed_config, *args, **kwargs)
>   File "/env/lib/python3.6/site-packages/datacube/ui/click.py", line 228, in with_index
>     return f(index, *args, **kwargs)
>   File "/env/lib/python3.6/site-packages/datacube/scripts/system.py", line 48, in database_init
>     with_permissions=init_users)
>   File "/env/lib/python3.6/site-packages/datacube/index/index.py", line 60, in init_db
>     is_new = self._db.init(with_permissions=with_permissions)
>   File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_connections.py", line 182, in init
>     _core.update_schema(self._engine)
>   File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_core.py", line 166, in update_schema
>     install_timestamp_trigger(c)
>   File "/env/lib/python3.6/site-packages/datacube/drivers/postgres/_triggers.py", line 50, in install_timestamp_trigger
>     conn.execute(UPDATE_COLUMN_MIGRATE_SQL_TEMPLATE.format(schema=SCHEMA_NAME, table=name))
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1006, in execute
>     return self._execute_text(object_, multiparams, params)
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1181, in _execute_text
>     parameters,
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
>     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
>   File "/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
>     cursor, statement, parameters, context
>   File "/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.OperationalError: (psycopg2.errors.DeadlockDetected) deadlock detected
> DETAIL:  Process 16605 waits for AccessExclusiveLock on relation 16492 of database 16592; blocked by process 18557.
> Process 18557 waits for AccessShareLock on relation 16431 of database 16592; blocked by process 16605.
> HINT:  See server log for query details.
> 
> [SQL: 
> alter table agdc.dataset_source add column if not exists updated
> timestamptz not null default now();
> ]
> (Background on this error at: http://sqlalche.me/e/13/e3q8)

### Steps to reproduce the behaviour

Run `datacube system init` on an existing database with lots of records and some activity.

### Environment information

datacube 1.8.2.dev...

**Comment by alexgleith** [comment]
This did not go well running on NCI either.

> datacube -v system init
> 2020-07-29 11:12:14,393 3122514 datacube INFO Running datacube command: /g/data/v10/public/modules/dea/unstable/bin/datacube -v system init
> Initialising database...
> 2020-07-29 11:12:15,029 3122514 datacube.drivers.postgres._core INFO Ensuring user roles.
> 2020-07-29 11:12:15,035 3122514 datacube.drivers.postgres._core INFO Adding role grants.
> 2020-07-29 11:12:15,043 3122514 datacube.drivers.postgres._core INFO Adding 'updated' fields and triggers to schema.
> Traceback (most recent call last):
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
>     cursor, statement, parameters, context
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.OperationalError: server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/g/data/v10/public/modules/dea/unstable/bin/datacube", line 8, in <module>
>     sys.exit(cli())
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/g/data/v10/public/modules/dea/unstable/lib/python3.6/site-packages/datacube/ui/click.py", line 196, in new_func
>     return f(parsed_config, *args, **kwargs)
>   File "/g/data/v10/public/modules/dea/unstable/lib/python3.6/site-packages/datacube/ui/click.py", line 228, in with_index
>     return f(index, *args, **kwargs)
>   File "/g/data/v10/public/modules/dea/unstable/lib/python3.6/site-packages/datacube/scripts/system.py", line 48, in database_init
>     with_permissions=init_users)
>   File "/g/data/v10/public/modules/dea/unstable/lib/python3.6/site-packages/datacube/index/index.py", line 60, in init_db
>     is_new = self._db.init(with_permissions=with_permissions)
>   File "/g/data/v10/public/modules/dea/unstable/lib/python3.6/site-packages/datacube/drivers/postgres/_connections.py", line 182, in init
>     _core.update_schema(self._engine)
>   File "/g/data/v10/public/modules/dea/unstable/lib/python3.6/site-packages/datacube/drivers/postgres/_core.py", line 191, in update_schema
>     install_timestamp_trigger(c)
>   File "/g/data/v10/public/modules/dea/unstable/lib/python3.6/site-packages/datacube/drivers/postgres/_core.py", line 52, in install_timestamp_trigger
>     connection.execute(UPDATE_COLUMN_MIGRATE_SQL_TEMPLATE.format(schema=SCHEMA_NAME, table=name))
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1006, in execute
>     return self._execute_text(object_, multiparams, params)
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1181, in _execute_text
>     parameters,
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
>     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
>     cursor, statement, parameters, context
>   File "/g/data/v10/public/modules/dea-env/20200713/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.
> 
> [SQL: 
> alter table agdc.dataset add column if not exists updated
> timestamptz not null default now();
> ]
> (Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by alexgleith** [comment]
The above error on NCI isn't actually of any use. The update process took an hour and still didn't complete, so I killed it.

**Comment by Kirill888** [comment]
huge databases are like that though, it will take forever to update all the indexes.

**Comment by whatnick** [comment]
Recommended new approach : 

- Leave dataset_location as it is
- Add updated field to: dataset, metadata_type and dataset_type tables
- Add triggers on above tables to update updated field
- Default to null
- No not null constraint
- Add added field to: dataset_source
- Populate with now()
- Default to now()
- Only add this field if it doesn’t exist, like how the ^ is implemented currently
- Do NOT make changes in the schema, but do comment.

It is possible some databases in use have been initialized with the current `datacube system init`, these will need to be manually rolled back. Overall datacube-core needs more managed approach to schema updats and rollbacks.
